# Generated by headerkit

type
  rtaudio_format_t* = culong
  rtaudio_stream_flags_t* = cuint
  rtaudio_stream_status_t* = cuint
  rtaudio_cb_t* = proc(a0: pointer, a1: pointer, a2: cuint, a3: cdouble, a4: rtaudio_stream_status_t, a5: pointer): cint {.cdecl.}
  rtaudio_error_enum* {.size: sizeof(cint), importc: "enum rtaudio_error", header: "rtaudio/rtaudio_c.h".} = enum
    RTAUDIO_ERROR_NONE = 0
    RTAUDIO_ERROR_WARNING = 1
    RTAUDIO_ERROR_UNKNOWN = 2
    RTAUDIO_ERROR_NO_DEVICES_FOUND = 3
    RTAUDIO_ERROR_INVALID_DEVICE = 4
    RTAUDIO_ERROR_DEVICE_DISCONNECT = 5
    RTAUDIO_ERROR_MEMORY_ERROR = 6
    RTAUDIO_ERROR_INVALID_PARAMETER = 7
    RTAUDIO_ERROR_INVALID_USE = 8
    RTAUDIO_ERROR_DRIVER_ERROR = 9
    RTAUDIO_ERROR_SYSTEM_ERROR = 10
    RTAUDIO_ERROR_THREAD_ERROR = 11
  rtaudio_error_t* = cint
  rtaudio_error_cb_t* = proc(a0: rtaudio_error_t, a1: cstring) {.cdecl.}
  rtaudio_api* {.size: sizeof(cint), importc: "enum rtaudio_api", header: "rtaudio/rtaudio_c.h".} = enum
    RTAUDIO_API_UNSPECIFIED = 0
    RTAUDIO_API_MACOSX_CORE = 1
    RTAUDIO_API_LINUX_ALSA = 2
    RTAUDIO_API_UNIX_JACK = 3
    RTAUDIO_API_LINUX_PULSE = 4
    RTAUDIO_API_LINUX_OSS = 5
    RTAUDIO_API_WINDOWS_ASIO = 6
    RTAUDIO_API_WINDOWS_WASAPI = 7
    RTAUDIO_API_WINDOWS_DS = 8
    RTAUDIO_API_DUMMY = 9
    RTAUDIO_API_NUM = 10
  rtaudio_api_t* = cint
  rtaudio_device_info* {.importc: "struct rtaudio_device_info", header: "rtaudio/rtaudio_c.h", bycopy.} = object
    id*: cuint
    output_channels*: cuint
    input_channels*: cuint
    duplex_channels*: cuint
    is_default_output*: cint
    is_default_input*: cint
    native_formats*: rtaudio_format_t
    preferred_sample_rate*: cuint
    sample_rates*: array[16, cuint]
    name*: array[512, cchar]
  rtaudio_device_info_t* = rtaudio_device_info
  rtaudio_stream_parameters* {.importc: "struct rtaudio_stream_parameters", header: "rtaudio/rtaudio_c.h", bycopy.} = object
    device_id*: cuint
    num_channels*: cuint
    first_channel*: cuint
  rtaudio_stream_parameters_t* = rtaudio_stream_parameters
  rtaudio_stream_options* {.importc: "struct rtaudio_stream_options", header: "rtaudio/rtaudio_c.h", bycopy.} = object
    flags*: rtaudio_stream_flags_t
    num_buffers*: cuint
    priority*: cint
    name*: array[512, cchar]
  rtaudio_stream_options_t* = rtaudio_stream_options
  rtaudio* {.importc: "struct rtaudio", header: "rtaudio/rtaudio_c.h", bycopy.} = object
  rtaudio_t* = ptr rtaudio

const
  RTAUDIO_FORMAT_SINT8* = 1
  RTAUDIO_FORMAT_SINT16* = 2
  RTAUDIO_FORMAT_SINT24* = 4
  RTAUDIO_FORMAT_SINT32* = 8
  RTAUDIO_FORMAT_FLOAT32* = 16
  RTAUDIO_FORMAT_FLOAT64* = 32
  RTAUDIO_FLAGS_NONINTERLEAVED* = 1
  RTAUDIO_FLAGS_MINIMIZE_LATENCY* = 2
  RTAUDIO_FLAGS_HOG_DEVICE* = 4
  RTAUDIO_FLAGS_SCHEDULE_REALTIME* = 8
  RTAUDIO_FLAGS_ALSA_USE_DEFAULT* = 16
  RTAUDIO_FLAGS_JACK_DONT_CONNECT* = 32
  RTAUDIO_STATUS_INPUT_OVERFLOW* = 1
  RTAUDIO_STATUS_OUTPUT_UNDERFLOW* = 2
  NUM_SAMPLE_RATES* = 16
  MAX_NAME_LENGTH* = 512

proc rtaudio_version*(): cstring {.importc: "rtaudio_version", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_get_num_compiled_apis*(): cuint {.importc: "rtaudio_get_num_compiled_apis", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_compiled_api*(): ptr rtaudio_api_t {.importc: "rtaudio_compiled_api", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_api_name*(api: rtaudio_api_t): cstring {.importc: "rtaudio_api_name", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_api_display_name*(api: rtaudio_api_t): cstring {.importc: "rtaudio_api_display_name", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_compiled_api_by_name*(name: cstring): rtaudio_api_t {.importc: "rtaudio_compiled_api_by_name", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_error*(audio: rtaudio_t): cstring {.importc: "rtaudio_error", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_error_type*(audio: rtaudio_t): rtaudio_error_t {.importc: "rtaudio_error_type", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_create*(api: rtaudio_api_t): rtaudio_t {.importc: "rtaudio_create", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_destroy*(audio: rtaudio_t) {.importc: "rtaudio_destroy", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_current_api*(audio: rtaudio_t): rtaudio_api_t {.importc: "rtaudio_current_api", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_device_count*(audio: rtaudio_t): cint {.importc: "rtaudio_device_count", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_get_device_id*(audio: rtaudio_t, i: cint): cuint {.importc: "rtaudio_get_device_id", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_get_device_info*(audio: rtaudio_t, id: cuint): rtaudio_device_info_t {.importc: "rtaudio_get_device_info", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_get_default_output_device*(audio: rtaudio_t): cuint {.importc: "rtaudio_get_default_output_device", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_get_default_input_device*(audio: rtaudio_t): cuint {.importc: "rtaudio_get_default_input_device", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_open_stream*(audio: rtaudio_t, output_params: ptr rtaudio_stream_parameters_t, input_params: ptr rtaudio_stream_parameters_t, format: rtaudio_format_t, sample_rate: cuint, buffer_frames: ptr cuint, cb: rtaudio_cb_t, userdata: pointer, options: ptr rtaudio_stream_options_t, errcb: rtaudio_error_cb_t): rtaudio_error_t {.importc: "rtaudio_open_stream", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_close_stream*(audio: rtaudio_t) {.importc: "rtaudio_close_stream", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_start_stream*(audio: rtaudio_t): rtaudio_error_t {.importc: "rtaudio_start_stream", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_stop_stream*(audio: rtaudio_t): rtaudio_error_t {.importc: "rtaudio_stop_stream", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_abort_stream*(audio: rtaudio_t): rtaudio_error_t {.importc: "rtaudio_abort_stream", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_is_stream_open*(audio: rtaudio_t): cint {.importc: "rtaudio_is_stream_open", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_is_stream_running*(audio: rtaudio_t): cint {.importc: "rtaudio_is_stream_running", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_get_stream_time*(audio: rtaudio_t): cdouble {.importc: "rtaudio_get_stream_time", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_set_stream_time*(audio: rtaudio_t, time: cdouble) {.importc: "rtaudio_set_stream_time", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_get_stream_latency*(audio: rtaudio_t): clong {.importc: "rtaudio_get_stream_latency", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_get_stream_sample_rate*(audio: rtaudio_t): cuint {.importc: "rtaudio_get_stream_sample_rate", header: "rtaudio/rtaudio_c.h", cdecl.}
proc rtaudio_show_warnings*(audio: rtaudio_t, show: cint) {.importc: "rtaudio_show_warnings", header: "rtaudio/rtaudio_c.h", cdecl.}
