# Generated by headerkit

type
  nng_ctx_s* {.importc: "struct nng_ctx_s", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    id*: uint32
  nng_ctx* = nng_ctx_s
  nng_dialer_s* {.importc: "struct nng_dialer_s", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    id*: uint32
  nng_dialer* = nng_dialer_s
  nng_listener_s* {.importc: "struct nng_listener_s", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    id*: uint32
  nng_listener* = nng_listener_s
  nng_pipe_s* {.importc: "struct nng_pipe_s", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    id*: uint32
  nng_pipe* = nng_pipe_s
  nng_socket_s* {.importc: "struct nng_socket_s", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    id*: uint32
  nng_socket* = nng_socket_s
  nng_duration* = int32
  nng_time* = uint64
  nng_msg* {.importc: "struct nng_msg", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
  nng_stat* {.importc: "struct nng_stat", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
  nng_aio* {.importc: "struct nng_aio", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
  nng_sockaddr_inproc* {.importc: "struct nng_sockaddr_inproc", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    sa_family*: uint16
    sa_name*: array[128, cchar]
  nng_sockaddr_path* {.importc: "struct nng_sockaddr_path", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    sa_family*: uint16
    sa_path*: array[128, cchar]
  nng_sockaddr_in6* {.importc: "struct nng_sockaddr_in6", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    sa_family*: uint16
    sa_port*: uint16
    sa_addr*: array[16, uint8]
    sa_scope*: uint32
  nng_sockaddr_in* {.importc: "struct nng_sockaddr_in", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    sa_family*: uint16
    sa_port*: uint16
    sa_addr*: uint32
  nng_sockaddr_zt* {.importc: "struct nng_sockaddr_zt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    sa_family*: uint16
    sa_nwid*: uint64
    sa_nodeid*: uint64
    sa_port*: uint32
  nng_sockaddr_abstract* {.importc: "struct nng_sockaddr_abstract", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    sa_family*: uint16
    sa_len*: uint16
    sa_name*: array[107, uint8]
  nng_sockaddr_storage* {.importc: "struct nng_sockaddr_storage", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    sa_family*: uint16
    sa_pad*: array[16, uint64]
  nng_sockaddr_ipc* = nng_sockaddr_path
  nng_sockaddr* {.importc: "union nng_sockaddr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", union.} = object
    s_family*: uint16
    s_ipc*: nng_sockaddr_ipc
    s_inproc*: nng_sockaddr_inproc
    s_in6*: nng_sockaddr_in6
    s_in*: nng_sockaddr_in
    s_zt*: nng_sockaddr_zt
    s_abstract*: nng_sockaddr_abstract
    s_storage*: nng_sockaddr_storage
  nng_sockaddr_family* {.size: sizeof(cint), importc: "enum nng_sockaddr_family", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h".} = enum
    NNG_AF_UNSPEC = 0
    NNG_AF_INPROC = 1
    NNG_AF_IPC = 2
    NNG_AF_INET = 3
    NNG_AF_INET6 = 4
    NNG_AF_ZT = 5
    NNG_AF_ABSTRACT = 6
  nng_iov* {.importc: "struct nng_iov", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    iov_buf*: pointer
    iov_len*: csize_t
  nng_pipe_ev* {.size: sizeof(cint), importc: "enum nng_pipe_ev", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h".} = enum
    NNG_PIPE_EV_ADD_PRE = 0
    NNG_PIPE_EV_ADD_POST = 1
    NNG_PIPE_EV_REM_POST = 2
    NNG_PIPE_EV_NUM = 3
  nng_pipe_cb* = proc(a0: nng_pipe, a1: nng_pipe_ev, a2: pointer) {.cdecl.}
  nng_aio_cancelfn* = proc(a0: ptr nng_aio, a1: pointer, a2: cint) {.cdecl.}
  nng_stat_type_enum* {.size: sizeof(cint), importc: "enum nng_stat_type_enum", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h".} = enum
    NNG_STAT_SCOPE = 0
    NNG_STAT_LEVEL = 1
    NNG_STAT_COUNTER = 2
    NNG_STAT_STRING = 3
    NNG_STAT_BOOLEAN = 4
    NNG_STAT_ID = 5
  nng_unit_enum* {.size: sizeof(cint), importc: "enum nng_unit_enum", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h".} = enum
    NNG_UNIT_NONE = 0
    NNG_UNIT_BYTES = 1
    NNG_UNIT_MESSAGES = 2
    NNG_UNIT_MILLIS = 3
    NNG_UNIT_EVENTS = 4
  nng_errno_enum* {.size: sizeof(cint), importc: "enum nng_errno_enum", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h".} = enum
    NNG_EINTR = 1
    NNG_ENOMEM = 2
    NNG_EINVAL = 3
    NNG_EBUSY = 4
    NNG_ETIMEDOUT = 5
    NNG_ECONNREFUSED = 6
    NNG_ECLOSED = 7
    NNG_EAGAIN = 8
    NNG_ENOTSUP = 9
    NNG_EADDRINUSE = 10
    NNG_ESTATE = 11
    NNG_ENOENT = 12
    NNG_EPROTO = 13
    NNG_EUNREACHABLE = 14
    NNG_EADDRINVAL = 15
    NNG_EPERM = 16
    NNG_EMSGSIZE = 17
    NNG_ECONNABORTED = 18
    NNG_ECONNRESET = 19
    NNG_ECANCELED = 20
    NNG_ENOFILES = 21
    NNG_ENOSPC = 22
    NNG_EEXIST = 23
    NNG_EREADONLY = 24
    NNG_EWRITEONLY = 25
    NNG_ECRYPTO = 26
    NNG_EPEERAUTH = 27
    NNG_ENOARG = 28
    NNG_EAMBIGUOUS = 29
    NNG_EBADTYPE = 30
    NNG_ECONNSHUT = 31
    NNG_EINTERNAL = 1000
    NNG_ESYSERR = 268435456
    NNG_ETRANERR = 536870912
  nng_url* {.importc: "struct nng_url", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
    u_rawurl*: ptr cchar
    u_scheme*: ptr cchar
    u_userinfo*: ptr cchar
    u_host*: ptr cchar
    u_hostname*: ptr cchar
    u_port*: ptr cchar
    u_path*: ptr cchar
    u_query*: ptr cchar
    u_fragment*: ptr cchar
    u_requri*: ptr cchar
  nng_stream* {.importc: "struct nng_stream", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
  nng_stream_dialer* {.importc: "struct nng_stream_dialer", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
  nng_stream_listener* {.importc: "struct nng_stream_listener", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
  nng_udp* {.importc: "struct nng_udp", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
  nng_init_parameter* = cint
  nng_log_level* {.size: sizeof(cint), importc: "enum nng_log_level", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h".} = enum
    NNG_LOG_NONE = 0
    NNG_LOG_ERR = 3
    NNG_LOG_WARN = 4
    NNG_LOG_NOTICE = 5
    NNG_LOG_INFO = 6
    NNG_LOG_DEBUG = 7
  nng_log_facility* {.size: sizeof(cint), importc: "enum nng_log_facility", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h".} = enum
    NNG_LOG_USER = 1
    NNG_LOG_DAEMON = 3
    NNG_LOG_AUTH = 10
    NNG_LOG_LOCAL0 = 16
    NNG_LOG_LOCAL1 = 17
    NNG_LOG_LOCAL2 = 18
    NNG_LOG_LOCAL3 = 19
    NNG_LOG_LOCAL4 = 20
    NNG_LOG_LOCAL5 = 21
    NNG_LOG_LOCAL6 = 22
    NNG_LOG_LOCAL7 = 23
  nng_logger* = proc(a0: nng_log_level, a1: nng_log_facility, a2: cstring, a3: cstring) {.cdecl.}
  nng_thread* {.importc: "struct nng_thread", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
  nng_mtx* {.importc: "struct nng_mtx", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object
  nng_cv* {.importc: "struct nng_cv", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", bycopy.} = object

const
  NNG_MAJOR_VERSION* = 1
  NNG_MINOR_VERSION* = 12
  NNG_PATCH_VERSION* = 4
  NNG_RELEASE_SUFFIX* = ""
  NNG_MAXADDRLEN* = 128
  NNG_DURATION_INFINITE* = -1
  NNG_DURATION_DEFAULT* = -2
  NNG_DURATION_ZERO* = 0
  NNG_FLAG_ALLOC* = 1
  NNG_FLAG_NONBLOCK* = 2
  NNG_OPT_SOCKNAME* = "socket-name"
  NNG_OPT_RAW* = "raw"
  NNG_OPT_PROTO* = "protocol"
  NNG_OPT_PROTONAME* = "protocol-name"
  NNG_OPT_PEER* = "peer"
  NNG_OPT_PEERNAME* = "peer-name"
  NNG_OPT_RECVBUF* = "recv-buffer"
  NNG_OPT_SENDBUF* = "send-buffer"
  NNG_OPT_RECVFD* = "recv-fd"
  NNG_OPT_SENDFD* = "send-fd"
  NNG_OPT_RECVTIMEO* = "recv-timeout"
  NNG_OPT_SENDTIMEO* = "send-timeout"
  NNG_OPT_LOCADDR* = "local-address"
  NNG_OPT_REMADDR* = "remote-address"
  NNG_OPT_URL* = "url"
  NNG_OPT_MAXTTL* = "ttl-max"
  NNG_OPT_RECVMAXSZ* = "recv-size-max"
  NNG_OPT_RECONNMINT* = "reconnect-time-min"
  NNG_OPT_RECONNMAXT* = "reconnect-time-max"
  NNG_OPT_TLS_CONFIG* = "tls-config"
  NNG_OPT_TLS_AUTH_MODE* = "tls-authmode"
  NNG_OPT_TLS_CERT_KEY_FILE* = "tls-cert-key-file"
  NNG_OPT_TLS_CA_FILE* = "tls-ca-file"
  NNG_OPT_TLS_SERVER_NAME* = "tls-server-name"
  NNG_OPT_TLS_VERIFIED* = "tls-verified"
  NNG_OPT_TLS_PEER_CN* = "tls-peer-cn"
  NNG_OPT_TLS_PEER_ALT_NAMES* = "tls-peer-alt-names"
  NNG_OPT_TCP_NODELAY* = "tcp-nodelay"
  NNG_OPT_TCP_KEEPALIVE* = "tcp-keepalive"
  NNG_OPT_TCP_BOUND_PORT* = "tcp-bound-port"
  NNG_OPT_IPC_SECURITY_DESCRIPTOR* = "ipc:security-descriptor"
  NNG_OPT_IPC_PERMISSIONS* = "ipc:permissions"
  NNG_OPT_PEER_UID* = "ipc:peer-uid"
  NNG_OPT_PEER_GID* = "ipc:peer-gid"
  NNG_OPT_PEER_PID* = "ipc:peer-pid"
  NNG_OPT_PEER_ZONEID* = "ipc:peer-zoneid"
  NNG_OPT_WS_REQUEST_HEADERS* = "ws:request-headers"
  NNG_OPT_WS_RESPONSE_HEADERS* = "ws:response-headers"
  NNG_OPT_WS_RESPONSE_HEADER* = "ws:response-header:"
  NNG_OPT_WS_REQUEST_HEADER* = "ws:request-header:"
  NNG_OPT_WS_REQUEST_URI* = "ws:request-uri"
  NNG_OPT_WS_SENDMAXFRAME* = "ws:txframe-max"
  NNG_OPT_WS_RECVMAXFRAME* = "ws:rxframe-max"
  NNG_OPT_WS_PROTOCOL* = "ws:protocol"
  NNG_OPT_WS_SEND_TEXT* = "ws:send-text"
  NNG_OPT_WS_RECV_TEXT* = "ws:recv-text"
  NNG_OPT_SOCKET_FD* = "socket:fd"
  NNG_REQ0_SELF* = 48
  NNG_REQ0_PEER* = 49
  NNG_REQ0_SELF_NAME* = "req"
  NNG_REQ0_PEER_NAME* = "rep"
  NNG_OPT_REQ_RESENDTIME* = "req:resend-time"
  NNG_OPT_REQ_RESENDTICK* = "req:resend-tick"
  NNG_REP0_SELF* = 49
  NNG_REP0_PEER* = 48
  NNG_REP0_SELF_NAME* = "rep"
  NNG_REP0_PEER_NAME* = "req"
  NNG_OPT_SUB_SUBSCRIBE* = "sub:subscribe"
  NNG_OPT_SUB_UNSUBSCRIBE* = "sub:unsubscribe"
  NNG_OPT_SUB_PREFNEW* = "sub:prefnew"
  NNG_BUS0_SELF* = 112
  NNG_BUS0_PEER* = 112
  NNG_BUS0_SELF_NAME* = "bus"
  NNG_BUS0_PEER_NAME* = "bus"
  NNG_SURVEYOR0_SELF* = 98
  NNG_SURVEYOR0_PEER* = 99
  NNG_SURVEYOR0_SELF_NAME* = "surveyor"
  NNG_SURVEYOR0_PEER_NAME* = "respondent"
  NNG_OPT_SURVEYOR_SURVEYTIME* = "surveyor:survey-time"
  NNG_RESPONDENT0_SELF* = 99
  NNG_RESPONDENT0_PEER* = 98
  NNG_RESPONDENT0_SELF_NAME* = "respondent"
  NNG_RESPONDENT0_PEER_NAME* = "surveyor"
  NNG_INIT_PARAMETER_NONE* = 0
  NNG_INIT_NUM_TASK_THREADS* = 1
  NNG_INIT_NUM_EXPIRE_THREADS* = 2
  NNG_INIT_NUM_POLLER_THREADS* = 3
  NNG_INIT_NUM_RESOLVER_THREADS* = 4
  NNG_INIT_MAX_TASK_THREADS* = 5
  NNG_INIT_MAX_EXPIRE_THREADS* = 6
  NNG_INIT_MAX_POLLER_THREADS* = 7

proc nng_fini*() {.importc: "nng_fini", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_close*(a0: nng_socket): cint {.importc: "nng_close", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_close*(a0: nng_socket): cint {.importc: "nng_socket_close", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_id*(a0: nng_socket): cint {.importc: "nng_socket_id", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_set*(a0: nng_socket, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_socket_set", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_set_bool*(a0: nng_socket, a1: cstring, a2: bool): cint {.importc: "nng_socket_set_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_set_int*(a0: nng_socket, a1: cstring, a2: cint): cint {.importc: "nng_socket_set_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_set_size*(a0: nng_socket, a1: cstring, a2: csize_t): cint {.importc: "nng_socket_set_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_set_uint64*(a0: nng_socket, a1: cstring, a2: uint64): cint {.importc: "nng_socket_set_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_set_string*(a0: nng_socket, a1: cstring, a2: cstring): cint {.importc: "nng_socket_set_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_set_ptr*(a0: nng_socket, a1: cstring, a2: pointer): cint {.importc: "nng_socket_set_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_set_ms*(a0: nng_socket, a1: cstring, a2: nng_duration): cint {.importc: "nng_socket_set_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_set_addr*(a0: nng_socket, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_socket_set_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_get*(a0: nng_socket, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_socket_get", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_get_bool*(a0: nng_socket, a1: cstring, a2: ptr bool): cint {.importc: "nng_socket_get_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_get_int*(a0: nng_socket, a1: cstring, a2: ptr cint): cint {.importc: "nng_socket_get_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_get_size*(a0: nng_socket, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_socket_get_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_get_uint64*(a0: nng_socket, a1: cstring, a2: ptr uint64): cint {.importc: "nng_socket_get_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_get_string*(a0: nng_socket, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_socket_get_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_get_ptr*(a0: nng_socket, a1: cstring, a2: ptr pointer): cint {.importc: "nng_socket_get_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_get_ms*(a0: nng_socket, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_socket_get_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_get_addr*(a0: nng_socket, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_socket_get_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_proto_id*(id: nng_socket, a1: ptr uint16): cint {.importc: "nng_socket_proto_id", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_peer_id*(id: nng_socket, a1: ptr uint16): cint {.importc: "nng_socket_peer_id", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_proto_name*(id: nng_socket, a1: ptr cstring): cint {.importc: "nng_socket_proto_name", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_peer_name*(id: nng_socket, a1: ptr cstring): cint {.importc: "nng_socket_peer_name", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_raw*(a0: nng_socket, a1: ptr bool): cint {.importc: "nng_socket_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_str_sockaddr*(sa: ptr nng_sockaddr, buf: ptr cchar, bufsz: csize_t): cstring {.importc: "nng_str_sockaddr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_notify*(a0: nng_socket, a1: nng_pipe_ev, a2: nng_pipe_cb, a3: pointer): cint {.importc: "nng_pipe_notify", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listen*(a0: nng_socket, a1: cstring, a2: ptr nng_listener, a3: cint): cint {.importc: "nng_listen", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dial*(a0: nng_socket, a1: cstring, a2: ptr nng_dialer, a3: cint): cint {.importc: "nng_dial", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_create*(a0: ptr nng_dialer, a1: nng_socket, a2: cstring): cint {.importc: "nng_dialer_create", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_create*(a0: ptr nng_listener, a1: nng_socket, a2: cstring): cint {.importc: "nng_listener_create", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_start*(a0: nng_dialer, a1: cint): cint {.importc: "nng_dialer_start", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_start*(a0: nng_listener, a1: cint): cint {.importc: "nng_listener_start", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_close*(a0: nng_dialer): cint {.importc: "nng_dialer_close", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_close*(a0: nng_listener): cint {.importc: "nng_listener_close", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_id*(a0: nng_dialer): cint {.importc: "nng_dialer_id", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_id*(a0: nng_listener): cint {.importc: "nng_listener_id", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_set*(a0: nng_dialer, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_dialer_set", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_set_bool*(a0: nng_dialer, a1: cstring, a2: bool): cint {.importc: "nng_dialer_set_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_set_int*(a0: nng_dialer, a1: cstring, a2: cint): cint {.importc: "nng_dialer_set_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_set_size*(a0: nng_dialer, a1: cstring, a2: csize_t): cint {.importc: "nng_dialer_set_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_set_uint64*(a0: nng_dialer, a1: cstring, a2: uint64): cint {.importc: "nng_dialer_set_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_set_string*(a0: nng_dialer, a1: cstring, a2: cstring): cint {.importc: "nng_dialer_set_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_set_ptr*(a0: nng_dialer, a1: cstring, a2: pointer): cint {.importc: "nng_dialer_set_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_set_ms*(a0: nng_dialer, a1: cstring, a2: nng_duration): cint {.importc: "nng_dialer_set_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_set_addr*(a0: nng_dialer, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_dialer_set_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_get*(a0: nng_dialer, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_dialer_get", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_get_bool*(a0: nng_dialer, a1: cstring, a2: ptr bool): cint {.importc: "nng_dialer_get_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_get_int*(a0: nng_dialer, a1: cstring, a2: ptr cint): cint {.importc: "nng_dialer_get_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_get_size*(a0: nng_dialer, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_dialer_get_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_get_uint64*(a0: nng_dialer, a1: cstring, a2: ptr uint64): cint {.importc: "nng_dialer_get_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_get_string*(a0: nng_dialer, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_dialer_get_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_get_ptr*(a0: nng_dialer, a1: cstring, a2: ptr pointer): cint {.importc: "nng_dialer_get_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_get_ms*(a0: nng_dialer, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_dialer_get_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_get_addr*(a0: nng_dialer, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_dialer_get_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_set*(a0: nng_listener, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_listener_set", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_set_bool*(a0: nng_listener, a1: cstring, a2: bool): cint {.importc: "nng_listener_set_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_set_int*(a0: nng_listener, a1: cstring, a2: cint): cint {.importc: "nng_listener_set_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_set_size*(a0: nng_listener, a1: cstring, a2: csize_t): cint {.importc: "nng_listener_set_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_set_uint64*(a0: nng_listener, a1: cstring, a2: uint64): cint {.importc: "nng_listener_set_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_set_string*(a0: nng_listener, a1: cstring, a2: cstring): cint {.importc: "nng_listener_set_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_set_ptr*(a0: nng_listener, a1: cstring, a2: pointer): cint {.importc: "nng_listener_set_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_set_ms*(a0: nng_listener, a1: cstring, a2: nng_duration): cint {.importc: "nng_listener_set_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_set_addr*(a0: nng_listener, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_listener_set_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_get*(a0: nng_listener, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_listener_get", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_get_bool*(a0: nng_listener, a1: cstring, a2: ptr bool): cint {.importc: "nng_listener_get_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_get_int*(a0: nng_listener, a1: cstring, a2: ptr cint): cint {.importc: "nng_listener_get_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_get_size*(a0: nng_listener, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_listener_get_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_get_uint64*(a0: nng_listener, a1: cstring, a2: ptr uint64): cint {.importc: "nng_listener_get_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_get_string*(a0: nng_listener, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_listener_get_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_get_ptr*(a0: nng_listener, a1: cstring, a2: ptr pointer): cint {.importc: "nng_listener_get_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_get_ms*(a0: nng_listener, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_listener_get_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_get_addr*(a0: nng_listener, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_listener_get_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_strerror*(a0: cint): cstring {.importc: "nng_strerror", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_send*(a0: nng_socket, a1: pointer, a2: csize_t, a3: cint): cint {.importc: "nng_send", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_recv*(a0: nng_socket, a1: pointer, a2: ptr csize_t, a3: cint): cint {.importc: "nng_recv", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_sendmsg*(a0: nng_socket, a1: ptr nng_msg, a2: cint): cint {.importc: "nng_sendmsg", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_recvmsg*(a0: nng_socket, a1: ptr ptr nng_msg, a2: cint): cint {.importc: "nng_recvmsg", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_sock_send*(a0: nng_socket, a1: ptr nng_aio) {.importc: "nng_sock_send", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_send_aio*(a0: nng_socket, a1: ptr nng_aio) {.importc: "nng_send_aio", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_sock_recv*(a0: nng_socket, a1: ptr nng_aio) {.importc: "nng_sock_recv", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_recv_aio*(a0: nng_socket, a1: ptr nng_aio) {.importc: "nng_recv_aio", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_open*(a0: ptr nng_ctx, a1: nng_socket): cint {.importc: "nng_ctx_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_close*(a0: nng_ctx): cint {.importc: "nng_ctx_close", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_id*(a0: nng_ctx): cint {.importc: "nng_ctx_id", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_recv*(a0: nng_ctx, a1: ptr nng_aio) {.importc: "nng_ctx_recv", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_recvmsg*(a0: nng_ctx, a1: ptr ptr nng_msg, a2: cint): cint {.importc: "nng_ctx_recvmsg", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_send*(a0: nng_ctx, a1: ptr nng_aio) {.importc: "nng_ctx_send", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_sendmsg*(a0: nng_ctx, a1: ptr nng_msg, a2: cint): cint {.importc: "nng_ctx_sendmsg", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_get*(a0: nng_ctx, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_ctx_get", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_get_bool*(a0: nng_ctx, a1: cstring, a2: ptr bool): cint {.importc: "nng_ctx_get_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_get_int*(a0: nng_ctx, a1: cstring, a2: ptr cint): cint {.importc: "nng_ctx_get_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_get_size*(a0: nng_ctx, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_ctx_get_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_get_uint64*(a0: nng_ctx, a1: cstring, a2: ptr uint64): cint {.importc: "nng_ctx_get_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_get_string*(a0: nng_ctx, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_ctx_get_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_get_ptr*(a0: nng_ctx, a1: cstring, a2: ptr pointer): cint {.importc: "nng_ctx_get_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_get_ms*(a0: nng_ctx, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_ctx_get_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_set*(a0: nng_ctx, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_ctx_set", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_set_bool*(a0: nng_ctx, a1: cstring, a2: bool): cint {.importc: "nng_ctx_set_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_set_int*(a0: nng_ctx, a1: cstring, a2: cint): cint {.importc: "nng_ctx_set_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_set_size*(a0: nng_ctx, a1: cstring, a2: csize_t): cint {.importc: "nng_ctx_set_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_set_uint64*(a0: nng_ctx, a1: cstring, a2: uint64): cint {.importc: "nng_ctx_set_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_set_string*(a0: nng_ctx, a1: cstring, a2: cstring): cint {.importc: "nng_ctx_set_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_set_ptr*(a0: nng_ctx, a1: cstring, a2: pointer): cint {.importc: "nng_ctx_set_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_set_ms*(a0: nng_ctx, a1: cstring, a2: nng_duration): cint {.importc: "nng_ctx_set_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_alloc*(a0: csize_t): pointer {.importc: "nng_alloc", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_free*(a0: pointer, a1: csize_t) {.importc: "nng_free", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_strdup*(a0: cstring): ptr cchar {.importc: "nng_strdup", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_strfree*(a0: ptr cchar) {.importc: "nng_strfree", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_alloc*(a0: ptr ptr nng_aio, a1: proc(a0: pointer) {.cdecl.}, a2: pointer): cint {.importc: "nng_aio_alloc", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_free*(a0: ptr nng_aio) {.importc: "nng_aio_free", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_reap*(a0: ptr nng_aio) {.importc: "nng_aio_reap", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_stop*(a0: ptr nng_aio) {.importc: "nng_aio_stop", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_result*(a0: ptr nng_aio): cint {.importc: "nng_aio_result", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_count*(a0: ptr nng_aio): csize_t {.importc: "nng_aio_count", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_cancel*(a0: ptr nng_aio) {.importc: "nng_aio_cancel", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_abort*(a0: ptr nng_aio, a1: cint) {.importc: "nng_aio_abort", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_wait*(a0: ptr nng_aio) {.importc: "nng_aio_wait", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_busy*(a0: ptr nng_aio): bool {.importc: "nng_aio_busy", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_set_msg*(a0: ptr nng_aio, a1: ptr nng_msg) {.importc: "nng_aio_set_msg", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_get_msg*(a0: ptr nng_aio): ptr nng_msg {.importc: "nng_aio_get_msg", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_set_input*(a0: ptr nng_aio, a1: cuint, a2: pointer): cint {.importc: "nng_aio_set_input", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_get_input*(a0: ptr nng_aio, a1: cuint): pointer {.importc: "nng_aio_get_input", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_set_output*(a0: ptr nng_aio, a1: cuint, a2: pointer): cint {.importc: "nng_aio_set_output", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_get_output*(a0: ptr nng_aio, a1: cuint): pointer {.importc: "nng_aio_get_output", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_set_timeout*(a0: ptr nng_aio, a1: nng_duration) {.importc: "nng_aio_set_timeout", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_set_expire*(a0: ptr nng_aio, a1: nng_time) {.importc: "nng_aio_set_expire", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_set_iov*(a0: ptr nng_aio, a1: cuint, a2: ptr nng_iov): cint {.importc: "nng_aio_set_iov", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_begin*(a0: ptr nng_aio): bool {.importc: "nng_aio_begin", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_finish*(a0: ptr nng_aio, a1: cint) {.importc: "nng_aio_finish", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_aio_defer*(a0: ptr nng_aio, a1: nng_aio_cancelfn, a2: pointer) {.importc: "nng_aio_defer", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_sleep_aio*(a0: nng_duration, a1: ptr nng_aio) {.importc: "nng_sleep_aio", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_alloc*(a0: ptr ptr nng_msg, a1: csize_t): cint {.importc: "nng_msg_alloc", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_free*(a0: ptr nng_msg) {.importc: "nng_msg_free", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_realloc*(a0: ptr nng_msg, a1: csize_t): cint {.importc: "nng_msg_realloc", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_reserve*(a0: ptr nng_msg, a1: csize_t): cint {.importc: "nng_msg_reserve", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_capacity*(a0: ptr nng_msg): csize_t {.importc: "nng_msg_capacity", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header*(a0: ptr nng_msg): pointer {.importc: "nng_msg_header", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_len*(a0: ptr nng_msg): csize_t {.importc: "nng_msg_header_len", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_body*(a0: ptr nng_msg): pointer {.importc: "nng_msg_body", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_len*(a0: ptr nng_msg): csize_t {.importc: "nng_msg_len", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_append*(a0: ptr nng_msg, a1: pointer, a2: csize_t): cint {.importc: "nng_msg_append", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_insert*(a0: ptr nng_msg, a1: pointer, a2: csize_t): cint {.importc: "nng_msg_insert", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_trim*(a0: ptr nng_msg, a1: csize_t): cint {.importc: "nng_msg_trim", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_chop*(a0: ptr nng_msg, a1: csize_t): cint {.importc: "nng_msg_chop", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_append*(a0: ptr nng_msg, a1: pointer, a2: csize_t): cint {.importc: "nng_msg_header_append", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_insert*(a0: ptr nng_msg, a1: pointer, a2: csize_t): cint {.importc: "nng_msg_header_insert", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_trim*(a0: ptr nng_msg, a1: csize_t): cint {.importc: "nng_msg_header_trim", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_chop*(a0: ptr nng_msg, a1: csize_t): cint {.importc: "nng_msg_header_chop", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_append_u16*(a0: ptr nng_msg, a1: uint16): cint {.importc: "nng_msg_header_append_u16", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_append_u32*(a0: ptr nng_msg, a1: uint32): cint {.importc: "nng_msg_header_append_u32", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_append_u64*(a0: ptr nng_msg, a1: uint64): cint {.importc: "nng_msg_header_append_u64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_insert_u16*(a0: ptr nng_msg, a1: uint16): cint {.importc: "nng_msg_header_insert_u16", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_insert_u32*(a0: ptr nng_msg, a1: uint32): cint {.importc: "nng_msg_header_insert_u32", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_insert_u64*(a0: ptr nng_msg, a1: uint64): cint {.importc: "nng_msg_header_insert_u64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_chop_u16*(a0: ptr nng_msg, a1: ptr uint16): cint {.importc: "nng_msg_header_chop_u16", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_chop_u32*(a0: ptr nng_msg, a1: ptr uint32): cint {.importc: "nng_msg_header_chop_u32", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_chop_u64*(a0: ptr nng_msg, a1: ptr uint64): cint {.importc: "nng_msg_header_chop_u64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_trim_u16*(a0: ptr nng_msg, a1: ptr uint16): cint {.importc: "nng_msg_header_trim_u16", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_trim_u32*(a0: ptr nng_msg, a1: ptr uint32): cint {.importc: "nng_msg_header_trim_u32", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_trim_u64*(a0: ptr nng_msg, a1: ptr uint64): cint {.importc: "nng_msg_header_trim_u64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_append_u16*(a0: ptr nng_msg, a1: uint16): cint {.importc: "nng_msg_append_u16", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_append_u32*(a0: ptr nng_msg, a1: uint32): cint {.importc: "nng_msg_append_u32", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_append_u64*(a0: ptr nng_msg, a1: uint64): cint {.importc: "nng_msg_append_u64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_insert_u16*(a0: ptr nng_msg, a1: uint16): cint {.importc: "nng_msg_insert_u16", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_insert_u32*(a0: ptr nng_msg, a1: uint32): cint {.importc: "nng_msg_insert_u32", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_insert_u64*(a0: ptr nng_msg, a1: uint64): cint {.importc: "nng_msg_insert_u64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_chop_u16*(a0: ptr nng_msg, a1: ptr uint16): cint {.importc: "nng_msg_chop_u16", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_chop_u32*(a0: ptr nng_msg, a1: ptr uint32): cint {.importc: "nng_msg_chop_u32", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_chop_u64*(a0: ptr nng_msg, a1: ptr uint64): cint {.importc: "nng_msg_chop_u64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_trim_u16*(a0: ptr nng_msg, a1: ptr uint16): cint {.importc: "nng_msg_trim_u16", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_trim_u32*(a0: ptr nng_msg, a1: ptr uint32): cint {.importc: "nng_msg_trim_u32", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_trim_u64*(a0: ptr nng_msg, a1: ptr uint64): cint {.importc: "nng_msg_trim_u64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_dup*(a0: ptr ptr nng_msg, a1: ptr nng_msg): cint {.importc: "nng_msg_dup", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_clear*(a0: ptr nng_msg) {.importc: "nng_msg_clear", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_header_clear*(a0: ptr nng_msg) {.importc: "nng_msg_header_clear", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_set_pipe*(a0: ptr nng_msg, a1: nng_pipe) {.importc: "nng_msg_set_pipe", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_get_pipe*(a0: ptr nng_msg): nng_pipe {.importc: "nng_msg_get_pipe", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_get*(a0: nng_pipe, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_pipe_get", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_get_bool*(a0: nng_pipe, a1: cstring, a2: ptr bool): cint {.importc: "nng_pipe_get_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_get_int*(a0: nng_pipe, a1: cstring, a2: ptr cint): cint {.importc: "nng_pipe_get_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_get_ms*(a0: nng_pipe, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_pipe_get_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_get_size*(a0: nng_pipe, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_pipe_get_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_get_uint64*(a0: nng_pipe, a1: cstring, a2: ptr uint64): cint {.importc: "nng_pipe_get_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_get_string*(a0: nng_pipe, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_pipe_get_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_get_ptr*(a0: nng_pipe, a1: cstring, a2: ptr pointer): cint {.importc: "nng_pipe_get_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_get_addr*(a0: nng_pipe, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_pipe_get_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_close*(a0: nng_pipe): cint {.importc: "nng_pipe_close", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_id*(a0: nng_pipe): cint {.importc: "nng_pipe_id", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_socket*(a0: nng_pipe): nng_socket {.importc: "nng_pipe_socket", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_dialer*(a0: nng_pipe): nng_dialer {.importc: "nng_pipe_dialer", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_listener*(a0: nng_pipe): nng_listener {.importc: "nng_pipe_listener", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stats_get*(a0: ptr ptr nng_stat): cint {.importc: "nng_stats_get", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stats_free*(a0: ptr nng_stat) {.importc: "nng_stats_free", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stats_dump*(a0: ptr nng_stat) {.importc: "nng_stats_dump", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_next*(a0: ptr nng_stat): ptr nng_stat {.importc: "nng_stat_next", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_child*(a0: ptr nng_stat): ptr nng_stat {.importc: "nng_stat_child", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_name*(a0: ptr nng_stat): cstring {.importc: "nng_stat_name", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_type*(a0: ptr nng_stat): cint {.importc: "nng_stat_type", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_find*(a0: ptr nng_stat, a1: cstring): ptr nng_stat {.importc: "nng_stat_find", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_find_socket*(a0: ptr nng_stat, a1: nng_socket): ptr nng_stat {.importc: "nng_stat_find_socket", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_find_dialer*(a0: ptr nng_stat, a1: nng_dialer): ptr nng_stat {.importc: "nng_stat_find_dialer", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_find_listener*(a0: ptr nng_stat, a1: nng_listener): ptr nng_stat {.importc: "nng_stat_find_listener", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_unit*(a0: ptr nng_stat): cint {.importc: "nng_stat_unit", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_value*(a0: ptr nng_stat): uint64 {.importc: "nng_stat_value", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_bool*(a0: ptr nng_stat): bool {.importc: "nng_stat_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_string*(a0: ptr nng_stat): cstring {.importc: "nng_stat_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_desc*(a0: ptr nng_stat): cstring {.importc: "nng_stat_desc", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stat_timestamp*(a0: ptr nng_stat): uint64 {.importc: "nng_stat_timestamp", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_device*(a0: nng_socket, a1: nng_socket): cint {.importc: "nng_device", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_device_aio*(a0: ptr nng_aio, a1: nng_socket, a2: nng_socket) {.importc: "nng_device_aio", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_url_parse*(a0: ptr ptr nng_url, a1: cstring): cint {.importc: "nng_url_parse", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_url_free*(a0: ptr nng_url) {.importc: "nng_url_free", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_url_clone*(a0: ptr ptr nng_url, a1: ptr nng_url): cint {.importc: "nng_url_clone", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_version*(): cstring {.importc: "nng_version", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_free*(a0: ptr nng_stream) {.importc: "nng_stream_free", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_close*(a0: ptr nng_stream) {.importc: "nng_stream_close", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_send*(a0: ptr nng_stream, a1: ptr nng_aio) {.importc: "nng_stream_send", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_recv*(a0: ptr nng_stream, a1: ptr nng_aio) {.importc: "nng_stream_recv", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_get*(a0: ptr nng_stream, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_stream_get", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_get_bool*(a0: ptr nng_stream, a1: cstring, a2: ptr bool): cint {.importc: "nng_stream_get_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_get_int*(a0: ptr nng_stream, a1: cstring, a2: ptr cint): cint {.importc: "nng_stream_get_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_get_ms*(a0: ptr nng_stream, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_stream_get_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_get_size*(a0: ptr nng_stream, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_stream_get_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_get_uint64*(a0: ptr nng_stream, a1: cstring, a2: ptr uint64): cint {.importc: "nng_stream_get_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_get_string*(a0: ptr nng_stream, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_stream_get_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_get_ptr*(a0: ptr nng_stream, a1: cstring, a2: ptr pointer): cint {.importc: "nng_stream_get_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_get_addr*(a0: ptr nng_stream, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_stream_get_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_set*(a0: ptr nng_stream, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_stream_set", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_set_bool*(a0: ptr nng_stream, a1: cstring, a2: bool): cint {.importc: "nng_stream_set_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_set_int*(a0: ptr nng_stream, a1: cstring, a2: cint): cint {.importc: "nng_stream_set_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_set_ms*(a0: ptr nng_stream, a1: cstring, a2: nng_duration): cint {.importc: "nng_stream_set_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_set_size*(a0: ptr nng_stream, a1: cstring, a2: csize_t): cint {.importc: "nng_stream_set_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_set_uint64*(a0: ptr nng_stream, a1: cstring, a2: uint64): cint {.importc: "nng_stream_set_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_set_string*(a0: ptr nng_stream, a1: cstring, a2: cstring): cint {.importc: "nng_stream_set_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_set_ptr*(a0: ptr nng_stream, a1: cstring, a2: pointer): cint {.importc: "nng_stream_set_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_alloc*(a0: ptr ptr nng_stream_dialer, a1: cstring): cint {.importc: "nng_stream_dialer_alloc", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_alloc_url*(a0: ptr ptr nng_stream_dialer, a1: ptr nng_url): cint {.importc: "nng_stream_dialer_alloc_url", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_free*(a0: ptr nng_stream_dialer) {.importc: "nng_stream_dialer_free", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_close*(a0: ptr nng_stream_dialer) {.importc: "nng_stream_dialer_close", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_dial*(a0: ptr nng_stream_dialer, a1: ptr nng_aio) {.importc: "nng_stream_dialer_dial", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_set*(a0: ptr nng_stream_dialer, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_stream_dialer_set", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_get*(a0: ptr nng_stream_dialer, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_stream_dialer_get", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_get_bool*(a0: ptr nng_stream_dialer, a1: cstring, a2: ptr bool): cint {.importc: "nng_stream_dialer_get_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_get_int*(a0: ptr nng_stream_dialer, a1: cstring, a2: ptr cint): cint {.importc: "nng_stream_dialer_get_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_get_ms*(a0: ptr nng_stream_dialer, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_stream_dialer_get_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_get_size*(a0: ptr nng_stream_dialer, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_stream_dialer_get_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_get_uint64*(a0: ptr nng_stream_dialer, a1: cstring, a2: ptr uint64): cint {.importc: "nng_stream_dialer_get_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_get_string*(a0: ptr nng_stream_dialer, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_stream_dialer_get_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_get_ptr*(a0: ptr nng_stream_dialer, a1: cstring, a2: ptr pointer): cint {.importc: "nng_stream_dialer_get_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_get_addr*(a0: ptr nng_stream_dialer, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_stream_dialer_get_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_set_bool*(a0: ptr nng_stream_dialer, a1: cstring, a2: bool): cint {.importc: "nng_stream_dialer_set_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_set_int*(a0: ptr nng_stream_dialer, a1: cstring, a2: cint): cint {.importc: "nng_stream_dialer_set_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_set_ms*(a0: ptr nng_stream_dialer, a1: cstring, a2: nng_duration): cint {.importc: "nng_stream_dialer_set_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_set_size*(a0: ptr nng_stream_dialer, a1: cstring, a2: csize_t): cint {.importc: "nng_stream_dialer_set_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_set_uint64*(a0: ptr nng_stream_dialer, a1: cstring, a2: uint64): cint {.importc: "nng_stream_dialer_set_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_set_string*(a0: ptr nng_stream_dialer, a1: cstring, a2: cstring): cint {.importc: "nng_stream_dialer_set_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_set_ptr*(a0: ptr nng_stream_dialer, a1: cstring, a2: pointer): cint {.importc: "nng_stream_dialer_set_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_dialer_set_addr*(a0: ptr nng_stream_dialer, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_stream_dialer_set_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_alloc*(a0: ptr ptr nng_stream_listener, a1: cstring): cint {.importc: "nng_stream_listener_alloc", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_alloc_url*(a0: ptr ptr nng_stream_listener, a1: ptr nng_url): cint {.importc: "nng_stream_listener_alloc_url", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_free*(a0: ptr nng_stream_listener) {.importc: "nng_stream_listener_free", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_close*(a0: ptr nng_stream_listener) {.importc: "nng_stream_listener_close", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_listen*(a0: ptr nng_stream_listener): cint {.importc: "nng_stream_listener_listen", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_accept*(a0: ptr nng_stream_listener, a1: ptr nng_aio) {.importc: "nng_stream_listener_accept", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_set*(a0: ptr nng_stream_listener, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_stream_listener_set", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_get*(a0: ptr nng_stream_listener, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_stream_listener_get", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_get_bool*(a0: ptr nng_stream_listener, a1: cstring, a2: ptr bool): cint {.importc: "nng_stream_listener_get_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_get_int*(a0: ptr nng_stream_listener, a1: cstring, a2: ptr cint): cint {.importc: "nng_stream_listener_get_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_get_ms*(a0: ptr nng_stream_listener, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_stream_listener_get_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_get_size*(a0: ptr nng_stream_listener, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_stream_listener_get_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_get_uint64*(a0: ptr nng_stream_listener, a1: cstring, a2: ptr uint64): cint {.importc: "nng_stream_listener_get_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_get_string*(a0: ptr nng_stream_listener, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_stream_listener_get_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_get_ptr*(a0: ptr nng_stream_listener, a1: cstring, a2: ptr pointer): cint {.importc: "nng_stream_listener_get_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_get_addr*(a0: ptr nng_stream_listener, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_stream_listener_get_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_set_bool*(a0: ptr nng_stream_listener, a1: cstring, a2: bool): cint {.importc: "nng_stream_listener_set_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_set_int*(a0: ptr nng_stream_listener, a1: cstring, a2: cint): cint {.importc: "nng_stream_listener_set_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_set_ms*(a0: ptr nng_stream_listener, a1: cstring, a2: nng_duration): cint {.importc: "nng_stream_listener_set_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_set_size*(a0: ptr nng_stream_listener, a1: cstring, a2: csize_t): cint {.importc: "nng_stream_listener_set_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_set_uint64*(a0: ptr nng_stream_listener, a1: cstring, a2: uint64): cint {.importc: "nng_stream_listener_set_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_set_string*(a0: ptr nng_stream_listener, a1: cstring, a2: cstring): cint {.importc: "nng_stream_listener_set_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_set_ptr*(a0: ptr nng_stream_listener, a1: cstring, a2: pointer): cint {.importc: "nng_stream_listener_set_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_listener_set_addr*(a0: ptr nng_stream_listener, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_stream_listener_set_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_udp_open*(udpp: ptr ptr nng_udp, sa: ptr nng_sockaddr): cint {.importc: "nng_udp_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_udp_close*(udp: ptr nng_udp) {.importc: "nng_udp_close", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_udp_sockname*(udp: ptr nng_udp, sa: ptr nng_sockaddr): cint {.importc: "nng_udp_sockname", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_udp_send*(udp: ptr nng_udp, aio: ptr nng_aio) {.importc: "nng_udp_send", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_udp_recv*(udp: ptr nng_udp, aio: ptr nng_aio) {.importc: "nng_udp_recv", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_udp_multicast_membership*(udp: ptr nng_udp, sa: ptr nng_sockaddr, join: bool): cint {.importc: "nng_udp_multicast_membership", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msg_getopt*(a0: ptr nng_msg, a1: cint, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_msg_getopt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_getopt*(a0: nng_socket, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_getopt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_getopt_bool*(a0: nng_socket, a1: cstring, a2: ptr bool): cint {.importc: "nng_getopt_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_getopt_int*(a0: nng_socket, a1: cstring, a2: ptr cint): cint {.importc: "nng_getopt_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_getopt_ms*(a0: nng_socket, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_getopt_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_getopt_size*(a0: nng_socket, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_getopt_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_getopt_uint64*(a0: nng_socket, a1: cstring, a2: ptr uint64): cint {.importc: "nng_getopt_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_getopt_ptr*(a0: nng_socket, a1: cstring, a2: ptr pointer): cint {.importc: "nng_getopt_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_getopt_string*(a0: nng_socket, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_getopt_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_setopt*(a0: nng_socket, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_setopt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_setopt_bool*(a0: nng_socket, a1: cstring, a2: bool): cint {.importc: "nng_setopt_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_setopt_int*(a0: nng_socket, a1: cstring, a2: cint): cint {.importc: "nng_setopt_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_setopt_ms*(a0: nng_socket, a1: cstring, a2: nng_duration): cint {.importc: "nng_setopt_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_setopt_size*(a0: nng_socket, a1: cstring, a2: csize_t): cint {.importc: "nng_setopt_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_setopt_uint64*(a0: nng_socket, a1: cstring, a2: uint64): cint {.importc: "nng_setopt_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_setopt_string*(a0: nng_socket, a1: cstring, a2: cstring): cint {.importc: "nng_setopt_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_setopt_ptr*(a0: nng_socket, a1: cstring, a2: pointer): cint {.importc: "nng_setopt_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_getopt*(a0: nng_ctx, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_ctx_getopt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_getopt_bool*(a0: nng_ctx, a1: cstring, a2: ptr bool): cint {.importc: "nng_ctx_getopt_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_getopt_int*(a0: nng_ctx, a1: cstring, a2: ptr cint): cint {.importc: "nng_ctx_getopt_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_getopt_ms*(a0: nng_ctx, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_ctx_getopt_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_getopt_size*(a0: nng_ctx, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_ctx_getopt_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_setopt*(a0: nng_ctx, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_ctx_setopt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_setopt_bool*(a0: nng_ctx, a1: cstring, a2: bool): cint {.importc: "nng_ctx_setopt_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_setopt_int*(a0: nng_ctx, a1: cstring, a2: cint): cint {.importc: "nng_ctx_setopt_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_setopt_ms*(a0: nng_ctx, a1: cstring, a2: nng_duration): cint {.importc: "nng_ctx_setopt_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_setopt_size*(a0: nng_ctx, a1: cstring, a2: csize_t): cint {.importc: "nng_ctx_setopt_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_getopt*(a0: nng_dialer, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_dialer_getopt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_getopt_bool*(a0: nng_dialer, a1: cstring, a2: ptr bool): cint {.importc: "nng_dialer_getopt_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_getopt_int*(a0: nng_dialer, a1: cstring, a2: ptr cint): cint {.importc: "nng_dialer_getopt_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_getopt_ms*(a0: nng_dialer, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_dialer_getopt_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_getopt_size*(a0: nng_dialer, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_dialer_getopt_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_getopt_sockaddr*(a0: nng_dialer, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_dialer_getopt_sockaddr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_getopt_uint64*(a0: nng_dialer, a1: cstring, a2: ptr uint64): cint {.importc: "nng_dialer_getopt_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_getopt_ptr*(a0: nng_dialer, a1: cstring, a2: ptr pointer): cint {.importc: "nng_dialer_getopt_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_getopt_string*(a0: nng_dialer, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_dialer_getopt_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_setopt*(a0: nng_dialer, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_dialer_setopt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_setopt_bool*(a0: nng_dialer, a1: cstring, a2: bool): cint {.importc: "nng_dialer_setopt_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_setopt_int*(a0: nng_dialer, a1: cstring, a2: cint): cint {.importc: "nng_dialer_setopt_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_setopt_ms*(a0: nng_dialer, a1: cstring, a2: nng_duration): cint {.importc: "nng_dialer_setopt_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_setopt_size*(a0: nng_dialer, a1: cstring, a2: csize_t): cint {.importc: "nng_dialer_setopt_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_setopt_uint64*(a0: nng_dialer, a1: cstring, a2: uint64): cint {.importc: "nng_dialer_setopt_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_setopt_ptr*(a0: nng_dialer, a1: cstring, a2: pointer): cint {.importc: "nng_dialer_setopt_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_setopt_string*(a0: nng_dialer, a1: cstring, a2: cstring): cint {.importc: "nng_dialer_setopt_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_getopt*(a0: nng_listener, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_listener_getopt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_getopt_bool*(a0: nng_listener, a1: cstring, a2: ptr bool): cint {.importc: "nng_listener_getopt_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_getopt_int*(a0: nng_listener, a1: cstring, a2: ptr cint): cint {.importc: "nng_listener_getopt_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_getopt_ms*(a0: nng_listener, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_listener_getopt_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_getopt_size*(a0: nng_listener, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_listener_getopt_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_getopt_sockaddr*(a0: nng_listener, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_listener_getopt_sockaddr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_getopt_uint64*(a0: nng_listener, a1: cstring, a2: ptr uint64): cint {.importc: "nng_listener_getopt_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_getopt_ptr*(a0: nng_listener, a1: cstring, a2: ptr pointer): cint {.importc: "nng_listener_getopt_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_getopt_string*(a0: nng_listener, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_listener_getopt_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_setopt*(a0: nng_listener, a1: cstring, a2: pointer, a3: csize_t): cint {.importc: "nng_listener_setopt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_setopt_bool*(a0: nng_listener, a1: cstring, a2: bool): cint {.importc: "nng_listener_setopt_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_setopt_int*(a0: nng_listener, a1: cstring, a2: cint): cint {.importc: "nng_listener_setopt_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_setopt_ms*(a0: nng_listener, a1: cstring, a2: nng_duration): cint {.importc: "nng_listener_setopt_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_setopt_size*(a0: nng_listener, a1: cstring, a2: csize_t): cint {.importc: "nng_listener_setopt_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_setopt_uint64*(a0: nng_listener, a1: cstring, a2: uint64): cint {.importc: "nng_listener_setopt_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_setopt_ptr*(a0: nng_listener, a1: cstring, a2: pointer): cint {.importc: "nng_listener_setopt_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_setopt_string*(a0: nng_listener, a1: cstring, a2: cstring): cint {.importc: "nng_listener_setopt_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_getopt*(a0: nng_pipe, a1: cstring, a2: pointer, a3: ptr csize_t): cint {.importc: "nng_pipe_getopt", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_getopt_bool*(a0: nng_pipe, a1: cstring, a2: ptr bool): cint {.importc: "nng_pipe_getopt_bool", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_getopt_int*(a0: nng_pipe, a1: cstring, a2: ptr cint): cint {.importc: "nng_pipe_getopt_int", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_getopt_ms*(a0: nng_pipe, a1: cstring, a2: ptr nng_duration): cint {.importc: "nng_pipe_getopt_ms", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_getopt_size*(a0: nng_pipe, a1: cstring, a2: ptr csize_t): cint {.importc: "nng_pipe_getopt_size", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_getopt_sockaddr*(a0: nng_pipe, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_pipe_getopt_sockaddr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_getopt_uint64*(a0: nng_pipe, a1: cstring, a2: ptr uint64): cint {.importc: "nng_pipe_getopt_uint64", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_getopt_ptr*(a0: nng_pipe, a1: cstring, a2: ptr pointer): cint {.importc: "nng_pipe_getopt_ptr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pipe_getopt_string*(a0: nng_pipe, a1: cstring, a2: ptr ptr cchar): cint {.importc: "nng_pipe_getopt_string", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_closeall*() {.importc: "nng_closeall", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stream_set_addr*(a0: ptr nng_stream, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_stream_set_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_get_addr*(a0: nng_ctx, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_ctx_get_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_ctx_set_addr*(a0: nng_ctx, a1: cstring, a2: ptr nng_sockaddr): cint {.importc: "nng_ctx_set_addr", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_init_set_parameter*(a0: nng_init_parameter, a1: uint64) {.importc: "nng_init_set_parameter", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_null_logger*(a0: nng_log_level, a1: nng_log_facility, a2: cstring, a3: cstring) {.importc: "nng_null_logger", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_stderr_logger*(a0: nng_log_level, a1: nng_log_facility, a2: cstring, a3: cstring) {.importc: "nng_stderr_logger", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_system_logger*(a0: nng_log_level, a1: nng_log_facility, a2: cstring, a3: cstring) {.importc: "nng_system_logger", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_log_set_facility*(facility: nng_log_facility) {.importc: "nng_log_set_facility", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_log_set_level*(level: nng_log_level) {.importc: "nng_log_set_level", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_log_get_level*(): nng_log_level {.importc: "nng_log_get_level", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_log_set_logger*(logger: nng_logger) {.importc: "nng_log_set_logger", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_log_err*(msgid: cstring, msg: cstring) {.importc: "nng_log_err", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", varargs, cdecl.}
proc nng_log_warn*(msgid: cstring, msg: cstring) {.importc: "nng_log_warn", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", varargs, cdecl.}
proc nng_log_notice*(msgid: cstring, msg: cstring) {.importc: "nng_log_notice", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", varargs, cdecl.}
proc nng_log_info*(msgid: cstring, msg: cstring) {.importc: "nng_log_info", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", varargs, cdecl.}
proc nng_log_debug*(msgid: cstring, msg: cstring) {.importc: "nng_log_debug", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", varargs, cdecl.}
proc nng_log_auth*(level: nng_log_level, msgid: cstring, msg: cstring) {.importc: "nng_log_auth", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", varargs, cdecl.}
proc nng_clock*(): nng_time {.importc: "nng_clock", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_msleep*(a0: nng_duration) {.importc: "nng_msleep", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_random*(): uint32 {.importc: "nng_random", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_socket_pair*(a0: array[2, cint]): cint {.importc: "nng_socket_pair", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_thread_create*(a0: ptr ptr nng_thread, a1: proc(a0: pointer) {.cdecl.}, a2: pointer): cint {.importc: "nng_thread_create", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_thread_set_name*(a0: ptr nng_thread, a1: cstring) {.importc: "nng_thread_set_name", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_thread_destroy*(a0: ptr nng_thread) {.importc: "nng_thread_destroy", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_mtx_alloc*(a0: ptr ptr nng_mtx): cint {.importc: "nng_mtx_alloc", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_mtx_free*(a0: ptr nng_mtx) {.importc: "nng_mtx_free", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_mtx_lock*(a0: ptr nng_mtx) {.importc: "nng_mtx_lock", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_mtx_unlock*(a0: ptr nng_mtx) {.importc: "nng_mtx_unlock", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_cv_alloc*(a0: ptr ptr nng_cv, a1: ptr nng_mtx): cint {.importc: "nng_cv_alloc", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_cv_free*(a0: ptr nng_cv) {.importc: "nng_cv_free", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_cv_wait*(a0: ptr nng_cv) {.importc: "nng_cv_wait", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_cv_until*(a0: ptr nng_cv, a1: nng_time): cint {.importc: "nng_cv_until", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_cv_wake*(a0: ptr nng_cv) {.importc: "nng_cv_wake", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_cv_wake1*(a0: ptr nng_cv) {.importc: "nng_cv_wake1", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_dialer_get_url*(a0: nng_dialer, a1: ptr ptr nng_url): cint {.importc: "nng_dialer_get_url", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_listener_get_url*(a0: nng_listener, a1: ptr ptr nng_url): cint {.importc: "nng_listener_get_url", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_req0_open*(a0: ptr nng_socket): cint {.importc: "nng_req0_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_req0_open_raw*(a0: ptr nng_socket): cint {.importc: "nng_req0_open_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_rep0_open*(a0: ptr nng_socket): cint {.importc: "nng_rep0_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_rep0_open_raw*(a0: ptr nng_socket): cint {.importc: "nng_rep0_open_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pub0_open*(a0: ptr nng_socket): cint {.importc: "nng_pub0_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pub0_open_raw*(a0: ptr nng_socket): cint {.importc: "nng_pub0_open_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_sub0_open*(a0: ptr nng_socket): cint {.importc: "nng_sub0_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_sub0_open_raw*(a0: ptr nng_socket): cint {.importc: "nng_sub0_open_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_sub0_socket_subscribe*(id: nng_socket, buf: pointer, sz: csize_t): cint {.importc: "nng_sub0_socket_subscribe", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_sub0_socket_unsubscribe*(id: nng_socket, buf: pointer, sz: csize_t): cint {.importc: "nng_sub0_socket_unsubscribe", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_sub0_ctx_subscribe*(id: nng_ctx, buf: pointer, sz: csize_t): cint {.importc: "nng_sub0_ctx_subscribe", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_sub0_ctx_unsubscribe*(id: nng_ctx, buf: pointer, sz: csize_t): cint {.importc: "nng_sub0_ctx_unsubscribe", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_bus0_open*(a0: ptr nng_socket): cint {.importc: "nng_bus0_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_bus0_open_raw*(a0: ptr nng_socket): cint {.importc: "nng_bus0_open_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_push0_open*(a0: ptr nng_socket): cint {.importc: "nng_push0_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_push0_open_raw*(a0: ptr nng_socket): cint {.importc: "nng_push0_open_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pull0_open*(a0: ptr nng_socket): cint {.importc: "nng_pull0_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pull0_open_raw*(a0: ptr nng_socket): cint {.importc: "nng_pull0_open_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pair0_open*(a0: ptr nng_socket): cint {.importc: "nng_pair0_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_pair0_open_raw*(a0: ptr nng_socket): cint {.importc: "nng_pair0_open_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_surveyor0_open*(a0: ptr nng_socket): cint {.importc: "nng_surveyor0_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_surveyor0_open_raw*(a0: ptr nng_socket): cint {.importc: "nng_surveyor0_open_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_respondent0_open*(a0: ptr nng_socket): cint {.importc: "nng_respondent0_open", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
proc nng_respondent0_open_raw*(a0: ptr nng_socket): cint {.importc: "nng_respondent0_open_raw", header: "/Users/eek/Development/headerkit/examples/headers/nng_all.h", cdecl.}
