"""Integration roundtrip tests: parse C headers with libclang -> IR -> Nim output."""

from __future__ import annotations

import subprocess
import textwrap
from pathlib import Path

import pytest

from headerkit.backends import get_backend, is_backend_available
from headerkit.scaffold import ScaffoldOptions
from headerkit.writers import get_writer
from headerkit.writers.nim import unit_requires_cpp, write_nim
from tests.native_build import position_independent_flags
from tests.skip_policy import (
    BACKEND_INSTALL,
    CC_INSTALL,
    CXX_INSTALL,
    NIM_INSTALL,
    missing_toolchain,
    require_program,
)

pytestmark = pytest.mark.skipif(
    not is_backend_available("libclang"),
    reason="libclang backend not available",
)


def _archiver() -> str:
    """The static-library archiver these gates build their fixtures with.

    ``ar`` ships with the same package as the C compiler on every platform the
    matrix covers, so it is reported with that remedy rather than a separate one.
    """
    return require_program("ar", "llvm-ar", install=CC_INSTALL)


def parse_and_nim(backend: pytest.FixtureRequest, code: str) -> str:
    """Parse C code and convert to Nim binding string."""
    header = backend.parse(code, "test.h")  # type: ignore[attr-defined]
    return write_nim(header)


class TestNimEmpty:
    """Verify the writer does not crash on an empty header."""

    def test_empty_header(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "")
        assert output == "# Generated by headerkit\n"


class TestNimFunctionRoundtrip:
    """Test parsing and converting functions to Nim."""

    def test_simple_function(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "int add(int a, int b);")
        assert 'proc add*(a: cint, b: cint): cint {.importc: "add", header: "test.h", cdecl.}' in output

    def test_void_function(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "void reset_system(void);")
        assert 'proc reset_system*() {.importc: "reset_system", header: "test.h", cdecl.}' in output


class TestNimStructRoundtrip:
    """Test parsing and converting struct declarations to Nim."""

    def test_simple_struct(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "struct Point { int x; int y; };")
        assert "type" in output
        assert 'Point* {.importc: "struct Point", header: "test.h", bycopy.} = object' in output
        assert "x*: cint" in output
        assert "y*: cint" in output


class TestNimEnumRoundtrip:
    """Test parsing and converting enum declarations to Nim."""

    def test_simple_enum(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "enum Color { RED = 0, GREEN = 1, BLUE = 2 };")
        assert 'Color* {.size: sizeof(cint), importc: "enum Color", header: "test.h".} = enum' in output
        assert "RED = 0" in output


class TestNimTypedefRoundtrip:
    """Test parsing and converting typedefs to Nim."""

    def test_primitive_typedef(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "typedef unsigned int uint32_custom;")
        assert "uint32_custom* = cuint" in output


class TestNimCppBuildConfiguration:
    """Prove a scaffolded C++ package compiles, links and runs.

    ``importcpp`` bindings cannot be built by Nim's default C backend: the C
    compiler is handed a C++ header and rejects ``class`` outright. These cases
    build the real thing rather than inspecting strings about it.
    """

    #: A class is the minimum shape that exercises the C++ path end to end: a
    #: constructor (no default one, so nothing can be zero-initialised), a
    #: mutating method, a const method whose value the test checks, and a method
    #: taking a reference -- which the writer renders as a ``var`` parameter, the
    #: one param shape a link probe cannot simply wrap in another ``ptr``.
    HEADER = textwrap.dedent("""\
        #pragma once

        class Counter {
        public:
            Counter(int start);
            void add(int n);
            void addFrom(int& source);
            int value() const;
        private:
            int total;
        };

        void bumpBy(int& target, int amount);
    """)

    SOURCE = textwrap.dedent("""\
        #include "counter.hpp"

        Counter::Counter(int start) : total(start) {}
        void Counter::add(int n) { total += n; }
        void Counter::addFrom(int& source) { total += source; }
        int Counter::value() const { return total; }
        void bumpBy(int& target, int amount) { target += amount; }
    """)

    @staticmethod
    def _require_toolchain() -> tuple[str, str]:
        """Return the ``nim`` and C++ driver paths, skipping visibly if either is absent."""
        nim_bin = require_program("nim", install=NIM_INSTALL)
        cxx_bin = require_program("c++", "g++", "clang++", install=CXX_INSTALL)
        return nim_bin, cxx_bin

    @staticmethod
    def _run(argv: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
        return subprocess.run(argv, cwd=cwd, capture_output=True, text=True, check=False)  # noqa: S603

    def _scaffold(self, backend, tmp_path: Path) -> tuple[Path, Path, str, str]:
        """Write the header, build a static library from it, and scaffold the package."""
        nim_bin, cxx_bin = self._require_toolchain()

        native = tmp_path / "native"
        native.mkdir()
        header = native / "counter.hpp"
        header.write_text(self.HEADER)
        (native / "counter.cpp").write_text(self.SOURCE)

        compiled = self._run([cxx_bin, *position_independent_flags(), "-c", "counter.cpp", "-o", "counter.o"], native)
        assert compiled.returncode == 0, f"building the native object failed:\n{compiled.stderr}"
        archived = self._run([_archiver(), "rcs", "libcounter.a", "counter.o"], native)
        assert archived.returncode == 0, f"archiving the native library failed:\n{archived.stderr}"

        unit = backend.parse(self.HEADER, str(header))
        assert unit_requires_cpp(unit), "the fixture must parse into a C++ unit or it tests nothing"

        layout = get_writer("nim").write_layout(
            unit,
            ScaffoldOptions(
                package_name="counter",
                target_language="nim",
                layout="package",
                options={"library": "counter", "library_dirs": str(native)},
            ),
        )
        pkg_dir = tmp_path / "pkg"
        layout.write_to_disk(pkg_dir)
        return pkg_dir, native, nim_bin, cxx_bin

    def test_generated_tripwire_compiles_links_and_runs(self, backend, tmp_path: Path) -> None:
        """The generated C++ tripwire builds and passes using only the generated nim.cfg."""
        pkg_dir, _native, nim_bin, _cxx = self._scaffold(backend, tmp_path)

        cfg = (pkg_dir / "nim.cfg").read_text()
        assert "--backend:cpp" in cfg, f"nim.cfg does not select the C++ backend:\n{cfg}"

        # `nim c`, not `nim cpp`: the generated nim.cfg must be what redirects the
        # build, because the generated .nimble test task spells the command this way.
        built = self._run([nim_bin, "c", "-r", "--hints:off", "tests/test_tripwire.nim"], pkg_dir)
        assert built.returncode == 0, (
            f"the generated tripwire failed to build or run:\n{built.stdout}\n{built.stderr}\nnim.cfg was:\n{cfg}"
        )

    def test_generated_bindings_call_through_to_the_native_library(self, backend, tmp_path: Path) -> None:
        """A consumer of the package constructs the class, mutates it, and reads a value back."""
        pkg_dir, _native, nim_bin, _cxx = self._scaffold(backend, tmp_path)

        consumer = pkg_dir / "tests" / "consumer.nim"
        consumer.write_text(
            textwrap.dedent("""\
                import counter

                var c = constructCounter(10)
                c.add(5)
                var seven = 7.cint
                c.addFrom(seven)
                var free = 0.cint
                bumpBy(free, 4)
                echo "value=", c.value()
                echo "free=", free
            """)
        )
        built = self._run([nim_bin, "c", "-r", "--hints:off", "tests/consumer.nim"], pkg_dir)
        assert built.returncode == 0, f"the consumer failed to build:\n{built.stdout}\n{built.stderr}"
        # 10 + 5 + 7, computed by the real C++ library rather than by Nim.
        assert "value=22" in built.stdout, f"the call did not reach the native library:\n{built.stdout}"
        # A free function taking `int&`: the writer renders `var cint`, which only
        # links under an `importcpp` pragma. Under `importc` Nim passes `int*` and
        # the C++ compiler rejects the call outright.
        assert "free=4" in built.stdout, f"the reference parameter did not reach the library:\n{built.stdout}"

    def test_tripwire_fails_loudly_when_the_native_library_is_missing(self, backend, tmp_path: Path) -> None:
        """Deleting the library must break the build.

        This one is caught by the linker's own "library not found", so it proves the
        generated ``-l`` flag is real -- not that the tripwire references any symbol.
        The case below is the one that proves that.
        """
        pkg_dir, native, nim_bin, _cxx = self._scaffold(backend, tmp_path)

        (native / "libcounter.a").unlink()
        built = self._run([nim_bin, "c", "-r", "--hints:off", "tests/test_tripwire.nim"], pkg_dir)
        assert built.returncode != 0, (
            "the tripwire passed with no native library present, which is the green mirage "
            f"it exists to prevent:\n{built.stdout}\n{built.stderr}"
        )

    def test_tripwire_fails_loudly_when_the_library_is_empty(self, backend, tmp_path: Path) -> None:
        """A library that exists but defines nothing must still fail the build.

        This is the case that distinguishes a tripwire which references the bound
        entry points from one that merely names a library on the link line. The
        archive is present, so the linker finds it; only an unresolved reference to
        ``Counter::add`` and friends can fail here.
        """
        pkg_dir, native, nim_bin, cxx_bin = self._scaffold(backend, tmp_path)

        (native / "empty.cpp").write_text("// defines nothing\n")
        compiled = self._run([cxx_bin, *position_independent_flags(), "-c", "empty.cpp", "-o", "empty.o"], native)
        assert compiled.returncode == 0, compiled.stderr
        (native / "libcounter.a").unlink()
        archived = self._run([_archiver(), "rcs", "libcounter.a", "empty.o"], native)
        assert archived.returncode == 0, archived.stderr
        assert (native / "libcounter.a").is_file(), "the archive must exist or this tests the previous case"

        built = self._run([nim_bin, "c", "-r", "--hints:off", "tests/test_tripwire.nim"], pkg_dir)
        assert built.returncode != 0, (
            "the tripwire built against a library defining none of the bound entry points, "
            f"so it does not establish that they link:\n{built.stdout}\n{built.stderr}"
        )


#: Source that must and must not select the C++ backend, as (label, code, filename,
#: needs_cpp). Every case goes through a real parse: a hand-built ``CType("std::string")``
#: asserts against a shape libclang never produces -- it reports that field as the bare
#: name ``string`` -- so a fixture built by hand can pass while the feature is inert.
CPP_DECISION_SOURCES: list[tuple[str, str, str, bool]] = [
    # --- C, and must stay C -------------------------------------------------
    ("c function", "int add(int a, int b);", "u.h", False),
    ("c struct", "struct Point { int x; int y; };", "u.h", False),
    ("c union", "union U { int i; float f; };", "u.h", False),
    ("c enum", "enum Color { RED, GREEN };", "u.h", False),
    ("c typedef", "typedef unsigned int u32;", "u.h", False),
    ("c function pointer", "typedef void (*cb)(int, double);", "u.h", False),
    ("c pointer param", "void take(const char *s);", "u.h", False),
    ("c array field", "struct Buf { char data[16]; };", "u.h", False),
    # A C header may name a record `vector`; the tag keyword is what settles it.
    ("c record named vector", "struct vector { float x; };\nstruct H { struct vector v; };", "u.h", False),
    # The typedef spelling of every marker. This is how C libraries usually name
    # records, and a *use* of a typedef carries no tag keyword -- so the name alone
    # is identical to the C++ spelling and only the unit's language separates them.
    ("c typedef named string", "typedef struct { int n; char *p; } string;\nint slen(string s);", "u.h", False),
    ("c typedef named vector", "typedef struct { int n; } vector;\nint vlen(vector s);", "u.h", False),
    ("c typedef named exception", "typedef struct { int code; } exception;\nint ecode(exception e);", "u.h", False),
    ("c typedef named wstring", "typedef struct { int n; } wstring;\nint wlen(wstring s);", "u.h", False),
    (
        "c typedef named basic_string",
        "typedef struct { int n; } basic_string;\nint blen(basic_string s);",
        "u.h",
        False,
    ),
    ("c typedef named unique_ptr", "typedef struct { void *p; } unique_ptr;\nvoid ufree(unique_ptr p);", "u.h", False),
    ("c typedef named shared_ptr", "typedef struct { void *p; } shared_ptr;\nvoid sfree(shared_ptr p);", "u.h", False),
    ("c typedef named weak_ptr", "typedef struct { void *p; } weak_ptr;\nvoid wfree(weak_ptr p);", "u.h", False),
    # --- C++, and must select the C++ backend -------------------------------
    ("class", "class C { public: void run(); };", "u.hpp", True),
    ("struct with method", "struct M { void run(); };", "u.hpp", True),
    ("struct with base", "struct B { int x; };\nstruct D : B { int y; };", "u.hpp", True),
    ("struct with constructor", "struct K { K(int v); int v; };", "u.hpp", True),
    ("struct with destructor", "struct T { ~T(); };", "u.hpp", True),
    ("namespaced struct", "namespace ns { struct Point { int x; }; }", "u.hpp", True),
    ("namespaced function", "namespace ns { void f(); }", "u.hpp", True),
    ("template function", "template <typename T> T identity(T v);", "u.hpp", True),
    ("scoped enum", "enum class Color { Red, Green };", "u.hpp", True),
    ("reference parameter", "void bump(int& x);", "u.hpp", True),
    ("reference return", "int& pick(int* p);", "u.hpp", True),
    # One case per entry in CPP_STDLIB_MARKERS, each through a real parse.
    ("std::string field", "#include <string>\nstruct S { std::string s; };", "u.hpp", True),
    ("std::exception base", "#include <exception>\nstruct E : std::exception { int x; };", "u.hpp", True),
    ("std::unique_ptr field", "#include <memory>\nstruct S { std::unique_ptr<int> p; };", "u.hpp", True),
    ("std::shared_ptr field", "#include <memory>\nstruct S { std::shared_ptr<int> p; };", "u.hpp", True),
    ("std::weak_ptr field", "#include <memory>\nstruct S { std::weak_ptr<int> p; };", "u.hpp", True),
    ("std::vector field", "#include <vector>\nstruct S { std::vector<int> v; };", "u.hpp", True),
    ("std::map field", "#include <map>\nstruct S { std::map<int, int> m; };", "u.hpp", True),
]


class TestCppBackendDecisionThroughTheParser:
    """`unit_requires_cpp` is measured against IR the backend actually produces."""

    @pytest.mark.parametrize(
        ("code", "filename", "needs_cpp"),
        [pytest.param(c, f, n, id=label) for label, c, f, n in CPP_DECISION_SOURCES],
    )
    def test_decision(self, backend, code: str, filename: str, needs_cpp: bool) -> None:
        unit = backend.parse(code, filename)
        assert unit.declarations, "the fixture must parse into something or it asserts nothing"
        assert unit_requires_cpp(unit) is needs_cpp

    @pytest.mark.parametrize(
        ("code", "filename"),
        [pytest.param(c, f, id=label) for label, c, f, n in CPP_DECISION_SOURCES if not n],
    )
    def test_c_sources_do_not_select_the_cpp_backend(self, backend, code: str, filename: str) -> None:
        """The C path needs no toolchain, so this assertion runs everywhere the suite does."""
        layout = get_writer("nim").write_layout(
            backend.parse(code, filename),
            ScaffoldOptions(package_name="plain", target_language="nim", layout="package"),
        )
        cfg = next(f.content for f in layout.files if f.path == "nim.cfg")
        assert "--backend:cpp" not in cfg


#: Header shapes whose Nim bindings the C backend genuinely cannot build, paired with a
#: consumer line that forces the emitted type into the generated translation unit.
#: Each needs no native library, so the compile itself is the whole assertion.
CPP_COMPILE_SHAPES: list[tuple[str, str, str]] = [
    ("class with a method", "class C { public: void run(); };", "discard sizeof(C)"),
    ("struct with a base", "struct B { int x; };\nstruct D : B { int y; };", "discard sizeof(D)"),
    ("namespaced struct", "namespace ns { struct Point { int x; }; }", "discard sizeof(Point)"),
    # One shape per C++ helper type the writer can render. Each is a record whose
    # field renders to that helper, so building it proves the helper is declared and
    # not merely referenced.
    ("std::string field", "#include <string>\nstruct S { std::string s; };", "discard sizeof(S)"),
    ("std::vector field", "#include <vector>\nstruct S { std::vector<int> v; };", "discard sizeof(S)"),
    ("std::unique_ptr field", "#include <memory>\nstruct S { std::unique_ptr<int> p; };", "discard sizeof(S)"),
    ("std::shared_ptr field", "#include <memory>\nstruct S { std::shared_ptr<int> p; };", "discard sizeof(S)"),
    ("std::weak_ptr field", "#include <memory>\nstruct S { std::weak_ptr<int> p; };", "discard sizeof(S)"),
]

#: C shapes whose generated package must build under the C backend it was given.
#: The `string`/`vector` names are the ones a spelling-only test misreads as C++;
#: compiled as C++ their functions come back mangled and the link fails.
C_COMPILE_SHAPES: list[tuple[str, str, str, str]] = [
    (
        "c typedef named vector",
        "typedef struct { int n; } vector;\nint vlen(vector s);",
        "int vlen(vector s) { return s.n; }",
        'var s: vector\ns.n = 5\necho "value=", vlen(s)',
    ),
    (
        "c record tagged string",
        "struct string { int n; };\nint slen(struct string s);",
        "int slen(struct string s) { return s.n; }",
        # Module-qualified: a C record named `string` collides with Nim's builtin.
        # That collision belongs to the writer and is not what this gate measures.
        'var s: clib.string\ns.n = 7\necho "value=", slen(s)',
    ),
]


class TestCppShapesNeedTheCppBackend:
    """Compile-gate the decision instead of asserting on the text of nim.cfg.

    Each shape is built twice from the same generated package: once as generated,
    and once with ``--backend:c`` forced on the command line. The first must build
    and the second must fail. A predicate that wrongly answered "C" for one of these
    would ship a package in exactly the state the second column measures.
    """

    @pytest.mark.parametrize(
        ("code", "consumer"),
        [pytest.param(c, u, id=label) for label, c, u in CPP_COMPILE_SHAPES],
    )
    def test_cpp_shape_builds_only_under_the_cpp_backend(
        self, backend, tmp_path: Path, code: str, consumer: str
    ) -> None:
        nim_bin, _cxx = TestNimCppBuildConfiguration._require_toolchain()
        header = tmp_path / "shape.hpp"
        header.write_text(code)
        unit = backend.parse(code, str(header))
        assert unit_requires_cpp(unit), "this shape must be classified C++ or the case tests nothing"

        pkg_dir = tmp_path / "pkg"
        get_writer("nim").write_layout(
            unit,
            ScaffoldOptions(package_name="shape", target_language="nim", layout="package"),
        ).write_to_disk(pkg_dir)
        (pkg_dir / "tests" / "consumer.nim").write_text(f"import shape\n{consumer}\n")

        run = TestNimCppBuildConfiguration._run
        # A full build, deliberately. `nim c -c` / `--compileOnly` generates the .c or
        # .cpp and stops without ever invoking the C compiler, so a gate built on it
        # passes for both backends and measures nothing: the only difference it can
        # see is the generated file's extension. These shapes need no native library,
        # so a full build costs a link of nothing and is a real compile.
        as_generated = run(
            [nim_bin, "c", "--hints:off", f"--nimcache:{tmp_path / 'nc_cpp'}", "tests/consumer.nim"], pkg_dir
        )
        assert as_generated.returncode == 0, (
            f"the generated package did not build:\n{as_generated.stdout}\n{as_generated.stderr}"
        )

        forced_c = run(
            [nim_bin, "c", "--backend:c", "--hints:off", f"--nimcache:{tmp_path / 'nc_c'}", "tests/consumer.nim"],
            pkg_dir,
        )
        assert forced_c.returncode != 0, (
            "the C backend built this shape, so it does not establish that the C++ backend "
            f"is required:\n{forced_c.stdout}\n{forced_c.stderr}"
        )


class TestTripwireHonesty:
    """A tripwire must never report success for a property it did not check."""

    def test_template_only_unit_does_not_report_a_verified_link(self, backend, tmp_path: Path) -> None:
        """No library, no -l flag, no linkable symbol: the only honest result is skipped.

        Before this was fixed the same package printed
        ``[OK] every bound entry point compiles and links`` -- a pass asserting
        ``check declared(<pkg>)``, which is true by construction.
        """
        nim_bin, _cxx = TestNimCppBuildConfiguration._require_toolchain()
        code = "template <typename T> T identity(T v);\n"
        header = tmp_path / "tmpl.hpp"
        header.write_text(code)
        unit = backend.parse(code, str(header))
        assert unit_requires_cpp(unit)

        pkg_dir = tmp_path / "pkg"
        get_writer("nim").write_layout(
            unit,
            ScaffoldOptions(package_name="tmpllib", target_language="nim", layout="package"),
        ).write_to_disk(pkg_dir)
        cfg = (pkg_dir / "nim.cfg").read_text()
        assert '--passL:"-l' not in cfg, "this case is only meaningful with no library named"

        built = TestNimCppBuildConfiguration._run(
            [nim_bin, "c", "-r", "--hints:off", f"--nimcache:{tmp_path / 'nc'}", "tests/test_tripwire.nim"], pkg_dir
        )
        assert built.returncode == 0, f"the tripwire must still build:\n{built.stdout}\n{built.stderr}"
        assert "[OK]" not in built.stdout, (
            "the tripwire reported success with no library present and nothing linkable bound:\n" + built.stdout
        )
        assert "[SKIPPED]" in built.stdout, f"expected a visible skip, got:\n{built.stdout}"

    def test_private_method_does_not_break_the_generated_package(self, backend, tmp_path: Path) -> None:
        """A probe may not reference a private member: that is a compile error, not a link one.

        The writer emits an ``importcpp`` binding for a private method regardless of
        access. Before a probe existed that declaration was inert. Probing it turns a
        latent writer gap into a package that cannot build at all, so the probe
        collector declines rather than the writer changing what it declares.
        """
        nim_bin, cxx_bin = TestNimCppBuildConfiguration._require_toolchain()
        header_code = textwrap.dedent("""\
            #pragma once
            class R {
            public:
                R(int v);
                int pub() const;
            private:
                void secret();
                int held;
            };
        """)
        native = tmp_path / "native"
        native.mkdir()
        (native / "r.hpp").write_text(header_code)
        (native / "r.cpp").write_text(
            textwrap.dedent("""\
                #include "r.hpp"
                R::R(int v) : held(v) {}
                int R::pub() const { return held; }
                void R::secret() {}
            """)
        )
        run = TestNimCppBuildConfiguration._run
        assert run([cxx_bin, *position_independent_flags(), "-c", "r.cpp", "-o", "r.o"], native).returncode == 0
        assert run([_archiver(), "rcs", "libr.a", "r.o"], native).returncode == 0

        unit = backend.parse(header_code, str(native / "r.hpp"))
        pkg_dir = tmp_path / "pkg"
        get_writer("nim").write_layout(
            unit,
            ScaffoldOptions(
                package_name="rlib",
                target_language="nim",
                layout="package",
                options={"library": "r", "library_dirs": str(native)},
            ),
        ).write_to_disk(pkg_dir)

        tripwire = (pkg_dir / "tests" / "test_tripwire.nim").read_text()
        assert "secret" not in tripwire, f"a private member must not be probed:\n{tripwire}"
        assert "pub(self[])" in tripwire, "the public members must still be probed"

        built = run(
            [nim_bin, "c", "-r", "--hints:off", f"--nimcache:{tmp_path / 'nc'}", "tests/test_tripwire.nim"], pkg_dir
        )
        assert built.returncode == 0, f"a private method broke the generated package:\n{built.stdout}\n{built.stderr}"


class TestPathsWithSpaces:
    """An include or library path containing a space must survive Nim's config parsing."""

    def test_package_in_a_directory_with_spaces_builds_and_runs(self, backend, tmp_path: Path) -> None:
        """Nim word-splits config values, so an unquoted -I reaches clang in pieces."""
        nim_bin, cxx_bin = TestNimCppBuildConfiguration._require_toolchain()
        native = tmp_path / "na tive"
        native.mkdir()
        header_code = "#pragma once\nvoid bump(int& x);\n"
        (native / "bump.hpp").write_text(header_code)
        (native / "bump.cpp").write_text('#include "bump.hpp"\nvoid bump(int& x) { x += 3; }\n')

        run = TestNimCppBuildConfiguration._run
        assert run([cxx_bin, *position_independent_flags(), "-c", "bump.cpp", "-o", "bump.o"], native).returncode == 0
        assert run([_archiver(), "rcs", "libbump.a", "bump.o"], native).returncode == 0

        unit = backend.parse(header_code, str(native / "bump.hpp"))
        pkg_dir = tmp_path / "pk g"
        get_writer("nim").write_layout(
            unit,
            ScaffoldOptions(
                package_name="bumplib",
                target_language="nim",
                layout="package",
                options={"library": "bump", "library_dirs": str(native)},
            ),
        ).write_to_disk(pkg_dir)
        assert f'-I\\"{native.resolve().as_posix()}\\"' in (pkg_dir / "nim.cfg").read_text()

        (pkg_dir / "tests" / "consumer.nim").write_text('import bumplib\nvar v = 10.cint\nbump(v)\necho "value=", v\n')
        built = run([nim_bin, "c", "-r", "--hints:off", f"--nimcache:{tmp_path / 'nc'}", "tests/consumer.nim"], pkg_dir)
        assert built.returncode == 0, f"a path with a space broke the build:\n{built.stdout}\n{built.stderr}"
        assert "value=13" in built.stdout, built.stdout


class TestCShapesStayOnTheCBackend:
    """A C header misread as C++ links against mangled names and fails.

    The `vector` and `string` cases are the ones a spelling-only test gets wrong.
    Compiled as C++ the generated package asks for `vlen(vector)` and the C library
    exports `_vlen`, which the linker reports as an undefined symbol -- so this is a
    link gate, not a compile gate, and needs a real library.
    """

    @pytest.mark.parametrize(
        ("code", "impl", "consumer"),
        [pytest.param(c, i, u, id=label) for label, c, i, u in C_COMPILE_SHAPES],
    )
    def test_c_shape_builds_and_calls_through(
        self, backend, tmp_path: Path, code: str, impl: str, consumer: str
    ) -> None:
        nim_bin, _cxx = TestNimCppBuildConfiguration._require_toolchain()
        cc_bin = require_program("cc", "gcc", "clang", install=CC_INSTALL)

        native = tmp_path / "native"
        native.mkdir()
        (native / "lib.h").write_text(code)
        (native / "lib.c").write_text(f'#include "lib.h"\n{impl}\n')

        run = TestNimCppBuildConfiguration._run
        compiled = run([cc_bin, "-x", "c", *position_independent_flags(), "-c", "lib.c", "-o", "lib.o"], native)
        assert compiled.returncode == 0, compiled.stderr
        assert run([_archiver(), "rcs", "liblib.a", "lib.o"], native).returncode == 0

        unit = backend.parse(code, str(native / "lib.h"))
        assert not unit_requires_cpp(unit), "a C header must not be classified C++"

        pkg_dir = tmp_path / "pkg"
        get_writer("nim").write_layout(
            unit,
            ScaffoldOptions(
                package_name="clib",
                target_language="nim",
                layout="package",
                options={"library": "lib", "library_dirs": str(native)},
            ),
        ).write_to_disk(pkg_dir)
        assert "--backend:cpp" not in (pkg_dir / "nim.cfg").read_text()

        (pkg_dir / "tests" / "consumer.nim").write_text(f"import clib\n{consumer}\n")
        built = run([nim_bin, "c", "-r", "--hints:off", f"--nimcache:{tmp_path / 'nc'}", "tests/consumer.nim"], pkg_dir)
        assert built.returncode == 0, f"the C package did not build or link:\n{built.stdout}\n{built.stderr}"
        assert "value=" in built.stdout, built.stdout


class TestInconclusiveTripwireReasons:
    """The reason a tripwire is inconclusive must reach the reader."""

    def test_reasons_are_printed_not_merely_written(self, backend, tmp_path: Path) -> None:
        """`checkpoint` prints only on failure, so on a skip it is dead text."""
        nim_bin, _cxx = TestNimCppBuildConfiguration._require_toolchain()
        code = "template <typename T> T identity(T v);\n"
        header = tmp_path / "tmpl.hpp"
        header.write_text(code)
        pkg_dir = tmp_path / "pkg"
        get_writer("nim").write_layout(
            backend.parse(code, str(header)),
            ScaffoldOptions(package_name="tmpllib", target_language="nim", layout="package"),
        ).write_to_disk(pkg_dir)

        built = TestNimCppBuildConfiguration._run(
            [nim_bin, "c", "-r", "--hints:off", f"--nimcache:{tmp_path / 'nc'}", "tests/test_tripwire.nim"], pkg_dir
        )
        # Both reasons, separately: one surviving echo would otherwise satisfy a
        # single substring assertion while the other stayed dead text.
        assert "no non-generic entry point and no complete class is bound" in built.stdout, (
            "the first reason never reached the reader:\n" + built.stdout
        )
        assert "nothing here establishes that the native library links" in built.stdout, (
            "the second reason never reached the reader:\n" + built.stdout
        )
        assert built.stdout.count("TRIPWIRE INCONCLUSIVE") == 2, built.stdout

    def test_generated_file_warns_that_it_exits_zero(self, backend, tmp_path: Path) -> None:
        """std/unittest counts failures only, so a skipped tripwire exits 0."""
        code = "template <typename T> T identity(T v);\n"
        layout = get_writer("nim").write_layout(
            backend.parse(code, str(tmp_path / "tmpl.hpp")),
            ScaffoldOptions(package_name="tmpllib", target_language="nim", layout="package"),
        )
        tripwire = next(f.content for f in layout.files if f.path == "tests/test_tripwire.nim")
        assert "exits 0" in tripwire, tripwire
        assert "Do not treat it as link verification" in tripwire, tripwire


#: Both parser backends, so a writer fix is proven against the IR each produces
#: rather than against the one that happened to be convenient.
NIM_BACKENDS = ("libclang", "tree-sitter")


@pytest.fixture(params=NIM_BACKENDS)
def nim_backend_name(request: pytest.FixtureRequest) -> str:
    """Run the gate once per installed parser backend."""
    name = str(request.param)
    if not is_backend_available(name):
        missing_toolchain(f"the {name} backend is not available", BACKEND_INSTALL[name])
    return name


class TestEnumWidthMatchesTheCompiler:
    """`{.size.}` is compared against `sizeof` measured by the C++ compiler itself.

    The pragma decides how many bytes every value of the enum occupies crossing the
    ABI, so asserting on the emitted text would only re-state the writer's opinion.
    These build a C++ probe, ask it, build the Nim package, ask it, and compare.
    """

    #: One per width class. `int` is the case the old hardcoded `cint` got right,
    #: and is kept so the fix is shown not to have moved it.
    UNDERLYING_TYPES = ("unsigned char", "short", "int", "long long")

    @pytest.mark.parametrize("underlying", UNDERLYING_TYPES)
    def test_emitted_size_equals_the_compilers_sizeof(
        self, nim_backend_name: str, tmp_path: Path, underlying: str
    ) -> None:
        nim_bin = require_program("nim", install=NIM_INSTALL)
        cxx_bin = require_program("c++", "g++", "clang++", install=CXX_INSTALL)
        run = TestNimCppBuildConfiguration._run

        header_code = f"#pragma once\nenum class Mode : {underlying} {{ Off = 0, On = 1 }};\n"
        native = tmp_path / "native"
        native.mkdir()
        (native / "mode.hpp").write_text(header_code)
        (native / "probe.cpp").write_text(
            '#include "mode.hpp"\n#include <cstdio>\nint main(){printf("%zu\\n", sizeof(Mode));return 0;}\n'
        )
        built = run([cxx_bin, "probe.cpp", "-o", "probe"], native)
        assert built.returncode == 0, built.stderr
        probe = run([str(native / "probe")], native)
        assert probe.returncode == 0, probe.stderr
        cxx_sizeof = int(probe.stdout.strip())

        unit = get_backend(nim_backend_name).parse(header_code, str(native / "mode.hpp"))
        pkg_dir = tmp_path / "pkg"
        get_writer("nim").write_layout(
            unit,
            ScaffoldOptions(package_name="modelib", target_language="nim", layout="package"),
        ).write_to_disk(pkg_dir)
        (pkg_dir / "tests" / "consumer.nim").write_text('import modelib\necho "size=", sizeof(Mode)\n')
        nim_built = run(
            [nim_bin, "c", "-r", "--hints:off", f"--nimcache:{tmp_path / 'nc'}", "tests/consumer.nim"], pkg_dir
        )
        assert nim_built.returncode == 0, f"{nim_built.stdout}\n{nim_built.stderr}"
        nim_sizeof = int(nim_built.stdout.split("size=")[1].split()[0])

        assert nim_sizeof == cxx_sizeof, (
            f"enum Mode : {underlying} is {cxx_sizeof} byte(s) to the C++ compiler and "
            f"{nim_sizeof} to the generated binding; every value of it crosses the ABI at "
            f"the wrong width"
        )


class TestIntegerSignednessSurvivesBothBackends:
    """A value that reads differently when signedness is lost, checked by running it.

    The two backends spell a multi-word integer differently -- libclang folds the
    qualifier into the name, tree-sitter keeps it in `qualifiers` -- so a writer
    reading the name alone rendered `unsigned char` as a *signed* Nim type under one
    of them. 255 then reads back as -1, which no assertion on the emitted text
    would notice.
    """

    HEADER = textwrap.dedent("""\
        #pragma once
        typedef unsigned char u8;
        typedef unsigned short u16;
        typedef unsigned int u32;

        u8 biggest_u8(void);
        u16 biggest_u16(void);
        u32 biggest_u32(void);
    """)

    SOURCE = textwrap.dedent("""\
        #include "widths.h"
        u8 biggest_u8(void) { return 255u; }
        u16 biggest_u16(void) { return 65535u; }
        u32 biggest_u32(void) { return 4294967295u; }
    """)

    def test_unsigned_values_survive_the_round_trip(self, nim_backend_name: str, tmp_path: Path) -> None:
        nim_bin = require_program("nim", install=NIM_INSTALL)
        cc_bin = require_program("cc", "gcc", "clang", install=CC_INSTALL)
        run = TestNimCppBuildConfiguration._run

        native = tmp_path / "native"
        native.mkdir()
        (native / "widths.h").write_text(self.HEADER)
        (native / "widths.c").write_text(self.SOURCE)
        assert (
            run(
                [cc_bin, "-x", "c", *position_independent_flags(), "-c", "widths.c", "-o", "widths.o"], native
            ).returncode
            == 0
        )
        assert run([_archiver(), "rcs", "libwidths.a", "widths.o"], native).returncode == 0

        unit = get_backend(nim_backend_name).parse(self.HEADER, str(native / "widths.h"))
        pkg_dir = tmp_path / "pkg"
        get_writer("nim").write_layout(
            unit,
            ScaffoldOptions(
                package_name="widths",
                target_language="nim",
                layout="package",
                options={"library": "widths", "library_dirs": str(native)},
            ),
        ).write_to_disk(pkg_dir)
        (pkg_dir / "tests" / "consumer.nim").write_text(
            textwrap.dedent("""\
                import widths
                echo "u8=", biggest_u8()
                echo "u16=", biggest_u16()
                echo "u32=", biggest_u32()
            """)
        )
        built = run([nim_bin, "c", "-r", "--hints:off", f"--nimcache:{tmp_path / 'nc'}", "tests/consumer.nim"], pkg_dir)
        assert built.returncode == 0, f"{built.stdout}\n{built.stderr}"
        # Signed renderings give -1, -1 and -1 respectively.
        assert "u8=255" in built.stdout, built.stdout
        assert "u16=65535" in built.stdout, built.stdout
        assert "u32=4294967295" in built.stdout, built.stdout


class TestAdditionalBasesAreReported:
    """Nim has one base per object, so the others must be named rather than dropped."""

    HEADER = textwrap.dedent("""\
        #pragma once
        struct Component { int cx; };
        struct Timer { int ty; };
        struct Logger { int lz; };
        class Editor : public Component, public virtual Timer, private Logger {
        public:
            Editor();
            int total() const;
        };
    """)

    SOURCE = textwrap.dedent("""\
        #include "editor.hpp"
        Editor::Editor() { cx = 1; ty = 2; lz = 4; }
        int Editor::total() const { return cx + ty + lz; }
    """)

    def _scaffold(self, nim_backend_name: str, tmp_path: Path) -> tuple[Path, str]:
        cxx_bin = require_program("c++", "g++", "clang++", install=CXX_INSTALL)
        run = TestNimCppBuildConfiguration._run
        native = tmp_path / "native"
        native.mkdir()
        (native / "editor.hpp").write_text(self.HEADER)
        (native / "editor.cpp").write_text(self.SOURCE)
        assert (
            run([cxx_bin, *position_independent_flags(), "-c", "editor.cpp", "-o", "editor.o"], native).returncode == 0
        )
        assert run([_archiver(), "rcs", "libeditor.a", "editor.o"], native).returncode == 0

        unit = get_backend(nim_backend_name).parse(self.HEADER, str(native / "editor.hpp"))
        editor = next(d for d in unit.declarations if getattr(d, "name", None) == "Editor")
        assert len(editor.bases) == 3, f"the fixture must carry three bases, got {editor.bases}"

        pkg_dir = tmp_path / "pkg"
        get_writer("nim").write_layout(
            unit,
            ScaffoldOptions(
                package_name="editorlib",
                target_language="nim",
                layout="package",
                options={"library": "editor", "library_dirs": str(native)},
            ),
        ).write_to_disk(pkg_dir)
        return pkg_dir, (pkg_dir / "src" / "editorlib" / "bindings.nim").read_text()

    def test_dropped_bases_are_named_in_the_bindings(self, nim_backend_name: str, tmp_path: Path) -> None:
        """A reader who cannot see that `Timer` is gone looks for its members here."""
        _pkg_dir, bindings = self._scaffold(nim_backend_name, tmp_path)
        assert "= object of Component" in bindings, bindings
        assert "UNSUPPORTED: base 'virtual Timer' of 'Editor'" in bindings, bindings
        assert "UNSUPPORTED: base 'private Logger' of 'Editor'" in bindings, bindings

    def test_the_bindings_compile_as_far_as_the_type(self, nim_backend_name: str, tmp_path: Path) -> None:
        """The diagnostics are comments, so they must not break the build."""
        nim_bin = require_program("nim", install=NIM_INSTALL)
        pkg_dir, _bindings = self._scaffold(nim_backend_name, tmp_path)
        (pkg_dir / "tests" / "consumer.nim").write_text("import editorlib\ndiscard sizeof(Editor)\n")
        built = TestNimCppBuildConfiguration._run(
            [nim_bin, "c", "--hints:off", f"--nimcache:{tmp_path / 'nc'}", "tests/consumer.nim"], pkg_dir
        )
        assert built.returncode == 0, f"{built.stdout}\n{built.stderr}"

    @pytest.mark.xfail(
        strict=True,
        reason=(
            "pre-existing: an importcpp object emitted with `of` is inheritable, so Nim "
            "emits RTTI (`m_type`) accesses that the C++ class does not have. Not specific "
            "to multiple bases and not introduced here -- a single-base class fails "
            "identically on main. Instantiating any such binding gives "
            "`error: no member named 'm_type'`. Fixing it is the subclassing/vtable work, "
            "which is deliberately not in this change."
        ),
    )
    def test_an_instance_of_an_inheriting_class_builds(self, nim_backend_name: str, tmp_path: Path) -> None:
        """Pins the defect that stops a C++ inheritance binding being usable at all.

        `sizeof` above passes because it needs no instance. The moment one exists,
        Nim reaches for the RTTI field. This is strict, so the day the writer stops
        emitting `of` for an importcpp type, this test goes red and gets deleted.
        """
        nim_bin = require_program("nim", install=NIM_INSTALL)
        pkg_dir, _bindings = self._scaffold(nim_backend_name, tmp_path)
        (pkg_dir / "tests" / "consumer.nim").write_text(
            'import editorlib\nvar e = constructEditor()\necho "total=", e.total()\n'
        )
        built = TestNimCppBuildConfiguration._run(
            [nim_bin, "c", "-r", "--hints:off", f"--nimcache:{tmp_path / 'nc'}", "tests/consumer.nim"], pkg_dir
        )
        assert built.returncode == 0, f"{built.stdout}\n{built.stderr}"
        assert "total=7" in built.stdout, built.stdout
