"""Integration roundtrip tests: parse C headers with libclang -> IR -> Nim output."""

from __future__ import annotations

import pytest

from headerkit.backends import is_backend_available
from headerkit.writers.nim import write_nim

pytestmark = pytest.mark.skipif(
    not is_backend_available("libclang"),
    reason="libclang backend not available",
)


def parse_and_nim(backend: pytest.FixtureRequest, code: str) -> str:
    """Parse C code and convert to Nim binding string."""
    header = backend.parse(code, "test.h")  # type: ignore[attr-defined]
    return write_nim(header)


class TestNimEmpty:
    """Verify the writer does not crash on an empty header."""

    def test_empty_header(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "")
        assert output == "# Generated by headerkit\n"


class TestNimFunctionRoundtrip:
    """Test parsing and converting functions to Nim."""

    def test_simple_function(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "int add(int a, int b);")
        assert 'proc add*(a: cint, b: cint): cint {.importc: "add", header: "test.h", cdecl.}' in output

    def test_void_function(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "void reset_system(void);")
        assert 'proc reset_system*() {.importc: "reset_system", header: "test.h", cdecl.}' in output


class TestNimStructRoundtrip:
    """Test parsing and converting struct declarations to Nim."""

    def test_simple_struct(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "struct Point { int x; int y; };")
        assert "type" in output
        assert 'Point* {.importc: "struct Point", header: "test.h", bycopy.} = object' in output
        assert "x*: cint" in output
        assert "y*: cint" in output


class TestNimEnumRoundtrip:
    """Test parsing and converting enum declarations to Nim."""

    def test_simple_enum(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "enum Color { RED = 0, GREEN = 1, BLUE = 2 };")
        assert 'Color* {.size: sizeof(cint), importc: "enum Color", header: "test.h".} = enum' in output
        assert "RED = 0" in output


class TestNimTypedefRoundtrip:
    """Test parsing and converting typedefs to Nim."""

    def test_primitive_typedef(self, backend: pytest.FixtureRequest) -> None:
        output = parse_and_nim(backend, "typedef unsigned int uint32_custom;")
        assert "uint32_custom* = cuint" in output
