"""Tests for the Nim writer."""

from __future__ import annotations

import textwrap

from headerkit.ir import (
    BaseSpecifier,
    Constant,
    CType,
    Enum,
    EnumValue,
    Field,
    Function,
    Header,
    Parameter,
    Pointer,
    Reference,
    Struct,
)
from headerkit.writers import get_writer
from headerkit.writers.nim import NimWriter, write_nim


class TestNimWriter:
    def test_nim_writer_registration(self) -> None:
        """Test that nim writer is registered and has correct metadata."""
        writer = get_writer("nim")
        assert isinstance(writer, NimWriter)
        assert writer.name == "nim"
        assert writer.format_description == "Nim bindings with C and C++ interop"

    def test_primitive_function_and_escape(self) -> None:
        """Test basic C function with types and keyword escaping."""
        h = Header(
            path="test.h",
            declarations=[
                Function(
                    name="type",
                    return_type=CType("int"),
                    parameters=[Parameter(name="var", type=CType("int"))],
                )
            ],
        )
        writer = NimWriter(header_path="test.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit
            {.compile: "test.h".}

            proc `type`*(`var`: cint): cint {.importc: "type", header: "test.h", cdecl.}
        """)
        assert out == expected

    def test_struct_with_fields(self) -> None:
        """Test C struct with primitive and pointer fields."""
        h = Header(
            path="test.h",
            declarations=[
                Struct(
                    name="Point",
                    fields=[
                        Field("x", CType("int")),
                        Field("y", CType("int")),
                        Field("label", Pointer(CType("char", ["const"]))),
                    ],
                )
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit
            {.compile: "test.h".}

            type
              Point* = object {.importc: "Point", header: "test.h", bycopy.}
                x*: cint
                y*: cint
                label*: cstring
        """)
        assert out == expected

    def test_cpp_class_with_templates_and_methods(self) -> None:
        """Test C++ class with template parameters, methods, inheritance, and constructors."""
        h = Header(
            path="test.hpp",
            declarations=[
                Struct(
                    name="Container",
                    template_params=["T"],
                    is_cppclass=True,
                    bases=[BaseSpecifier(name="Base")],
                    fields=[Field("value", CType("T"))],
                    constructors=[
                        Function(
                            name="Container",
                            return_type=CType("void"),
                            parameters=[Parameter("initVal", CType("T"), default_value="0")],
                        )
                    ],
                    methods=[
                        Function(
                            name="getVal",
                            return_type=CType("T"),
                            is_const=True,
                        ),
                        Function(
                            name="setVal",
                            return_type=CType("void"),
                            parameters=[Parameter("v", Reference(CType("T")))],
                        ),
                    ],
                )
            ],
        )
        out = write_nim(h, header_path="test.hpp")
        expected = textwrap.dedent("""\
            # Generated by headerkit
            {.compile: "test.hpp".}

            type
              Container[T]* = object of Base {.importcpp: "Container", header: "test.hpp", bycopy.}
                value*: T


            proc getVal*(this: Container): T {.importcpp: "#.getVal(@)", header: "test.hpp".}

            proc setVal*(this: var Container, v: var T) {.importcpp: "#.setVal(@)", header: "test.hpp".}

            proc constructContainer*(initVal: T = 0): Container {.importcpp: "Container(@)", header: "test.hpp", constructor.}
        """)
        assert out == expected

    def test_enum_and_constants(self) -> None:
        """Test enum and constant generation."""
        h = Header(
            path="test.h",
            declarations=[
                Enum(
                    name="Status",
                    values=[EnumValue("OK", 0), EnumValue("ERR", 1)],
                ),
                Constant(name="MAX_COUNT", value=100),
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit
            {.compile: "test.h".}

            type
              Status* {.size: sizeof(cint), importc: "Status", header: "test.h".} = enum
                OK = 0
                ERR = 1

            const
              MAX_COUNT* = 100
        """)
        assert out == expected

    def test_cpp_advanced_features(self) -> None:
        """Test C++ smart pointers, move semantics, operators, and container iterators."""
        h = Header(
            path="test.hpp",
            declarations=[
                Struct(
                    name="MyVector",
                    fields=[
                        Field("ptr", CType("std::shared_ptr<int>")),
                    ],
                    methods=[
                        Function(
                            name="operator[]",
                            return_type=Reference(CType("int")),
                            parameters=[Parameter("index", CType("size_t"))],
                        ),
                        Function(
                            name="push",
                            return_type=CType("void"),
                            parameters=[Parameter("val", Reference(CType("int"), is_rvalue=True))],
                        ),
                        Function(
                            name="begin",
                            return_type=Pointer(CType("int")),
                        ),
                        Function(
                            name="end",
                            return_type=Pointer(CType("int")),
                        ),
                    ],
                )
            ],
        )
        out = write_nim(h, header_path="test.hpp")
        expected = textwrap.dedent("""\
            # Generated by headerkit
            {.compile: "test.hpp".}

            type
              MyVector* = object {.importcpp: "MyVector", header: "test.hpp", bycopy.}
                `ptr`*: SharedPtr[cint]


            proc `[]`*(this: var MyVector, index: csize_t): var cint {.importcpp: "#[@]", header: "test.hpp".}

            proc push*(this: var MyVector, val: sink cint) {.importcpp: "#.push(@)", header: "test.hpp".}

            proc begin*(this: var MyVector): ptr cint {.importcpp: "#.begin(@)", header: "test.hpp".}

            proc `end`*(this: var MyVector): ptr cint {.importcpp: "#.end(@)", header: "test.hpp".}

            iterator items*(this: MyVector): auto = {.inline.}
              var it = this.begin()
              while it != this.end():
                yield it[]
                inc it
        """)
        assert out == expected
