"""Tests for the Nim writer."""

from __future__ import annotations

import os
import textwrap

import pytest

from headerkit._rename import SymbolCollisionError
from headerkit.ir import (
    BaseSpecifier,
    Constant,
    CType,
    Enum,
    EnumValue,
    Field,
    Function,
    FunctionPointer,
    Header,
    Parameter,
    Pointer,
    Reference,
    Struct,
    Typedef,
    Variable,
)
from headerkit.scaffold import ScaffoldOptions
from headerkit.writers import get_writer
from headerkit.writers.nim import (
    NimWriter,
    _cfg_path_flag,
    _type_name_requires_cpp,
    write_nim,
)
from tests.skip_policy import NIM_INSTALL, require_program


class TestNimWriter:
    def test_nim_writer_registration(self) -> None:
        """Test that nim writer is registered and has correct metadata."""
        writer = get_writer("nim")
        assert isinstance(writer, NimWriter)
        assert writer.name == "nim"
        assert writer.format_description == "Nim bindings with C and C++ interop"

    def test_primitive_function_and_escape(self) -> None:
        """Test basic C function with types and keyword escaping."""
        h = Header(
            path="test.h",
            declarations=[
                Function(
                    name="type",
                    return_type=CType("int"),
                    parameters=[Parameter(name="var", type=CType("int"))],
                )
            ],
        )
        writer = NimWriter(header_path="test.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            proc `type`*(`var`: cint): cint {.importc: "type", header: "test.h", cdecl.}
        """)
        assert out == expected

    def test_struct_with_fields(self) -> None:
        """Test C struct with primitive and pointer fields."""
        h = Header(
            path="test.h",
            declarations=[
                Struct(
                    name="Point",
                    fields=[
                        Field("x", CType("int")),
                        Field("y", CType("int")),
                        Field("label", Pointer(CType("char", ["const"]))),
                    ],
                )
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Point* {.importc: "struct Point", header: "test.h", bycopy.} = object
                x*: cint
                y*: cint
                label*: cstring
        """)
        assert out == expected

    def test_cpp_class_with_templates_and_methods(self) -> None:
        """Test C++ class with template parameters, methods, inheritance, and constructors."""
        h = Header(
            path="test.hpp",
            declarations=[
                Struct(
                    name="Container",
                    template_params=["T"],
                    is_cppclass=True,
                    bases=[BaseSpecifier(name="Base")],
                    fields=[Field("value", CType("T"))],
                    constructors=[
                        Function(
                            name="Container",
                            return_type=CType("void"),
                            parameters=[Parameter("initVal", CType("T"), default_value="0")],
                        )
                    ],
                    methods=[
                        Function(
                            name="getVal",
                            return_type=CType("T"),
                            is_const=True,
                        ),
                        Function(
                            name="setVal",
                            return_type=CType("void"),
                            parameters=[Parameter("v", Reference(CType("T")))],
                        ),
                    ],
                )
            ],
        )
        out = write_nim(h, header_path="test.hpp")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Container[T]* {.importcpp: "Container", header: "test.hpp", bycopy.} = object of Base
                value*: T


            proc getVal*[T](this: Container[T]): T {.importcpp: "#.getVal(@)", header: "test.hpp".}

            proc setVal*[T](this: var Container[T], v: var T) {.importcpp: "#.setVal(@)", header: "test.hpp".}

            proc constructContainer*[T](initVal: T = 0): Container[T] {.importcpp: "Container<'*0>(@)", header: "test.hpp", constructor.}
        """)
        assert out == expected

    def test_enum_and_constants(self) -> None:
        """Test enum and constant generation."""
        h = Header(
            path="test.h",
            declarations=[
                Enum(
                    name="Status",
                    values=[EnumValue("OK", 0), EnumValue("ERR", 1)],
                ),
                Constant(name="MAX_COUNT", value=100),
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Status* {.size: sizeof(cint), importc: "enum Status", header: "test.h".} = enum
                OK = 0
                ERR = 1

            const
              MAX_COUNT* = 100
        """)
        assert out == expected

    def test_cpp_advanced_features(self) -> None:
        """Test C++ smart pointers, move semantics, operators, and container iterators."""
        h = Header(
            path="test.hpp",
            declarations=[
                Struct(
                    name="MyVector",
                    fields=[
                        Field("ptr", CType("std::shared_ptr<int>")),
                    ],
                    methods=[
                        Function(
                            name="operator[]",
                            return_type=Reference(CType("int")),
                            parameters=[Parameter("index", CType("size_t"))],
                        ),
                        Function(
                            name="push",
                            return_type=CType("void"),
                            parameters=[Parameter("val", Reference(CType("int"), is_rvalue=True))],
                        ),
                        Function(
                            name="begin",
                            return_type=Pointer(CType("int")),
                        ),
                        Function(
                            name="end",
                            return_type=Pointer(CType("int")),
                        ),
                    ],
                )
            ],
        )
        out = write_nim(h, header_path="test.hpp")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              SharedPtr*[T] {.importcpp: "std::shared_ptr<'0>", header: "<memory>".} = object
              MyVector* {.importcpp: "MyVector", header: "test.hpp", bycopy.} = object
                `ptr`*: SharedPtr[cint]


            proc get*[T](p: SharedPtr[T]): ptr T {.importcpp: "#.get()", header: "<memory>".}

            proc reset*[T](p: var SharedPtr[T]) {.importcpp: "#.reset()", header: "<memory>".}

            proc useCount*[T](p: SharedPtr[T]): clong {.importcpp: "#.use_count()", header: "<memory>".}

            proc `[]`*(this: var MyVector, index: csize_t): var cint {.importcpp: "#[@]", header: "test.hpp".}

            proc push*(this: var MyVector, val: sink cint) {.importcpp: "#.push(@)", header: "test.hpp".}

            proc begin*(this: var MyVector): ptr cint {.importcpp: "#.begin(@)", header: "test.hpp".}

            proc `end`*(this: var MyVector): ptr cint {.importcpp: "#.end(@)", header: "test.hpp".}

            iterator items*(this: var MyVector): auto = {.inline.}
              var it = this.begin()
              while it != this.end():
                yield it[]
                inc it
        """)
        assert out == expected

    def test_typedef_output(self) -> None:
        """Test Typedef declaration rendering."""
        h = Header(
            path="types.h",
            declarations=[
                Typedef(name="ColorId", underlying_type=CType("unsigned int")),
                Typedef(name="type", underlying_type=Pointer(CType("void"))),
            ],
        )
        writer = NimWriter(header_path="types.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              ColorId* = cuint
              `type`* = pointer
        """)
        assert out == expected

    def test_variable_output(self) -> None:
        """Test extern global Variable rendering."""
        h = Header(
            path="globals.h",
            declarations=[
                Variable(name="global_dpi", type=CType("int")),
                Variable(name="yield", type=CType("double")),
            ],
        )
        writer = NimWriter(header_path="globals.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            var global_dpi* {.importc: "global_dpi", header: "globals.h".}: cint
            var `yield`* {.importc: "yield", header: "globals.h".}: cdouble
        """)
        assert out == expected

    def test_template_struct_iterators(self) -> None:
        """Test template container iterator generation."""
        h = Header(
            path="vec.hpp",
            declarations=[
                Struct(
                    name="GenericVector",
                    template_params=["T"],
                    is_cppclass=True,
                    methods=[
                        Function(name="begin", return_type=Pointer(CType("T"))),
                        Function(name="end", return_type=Pointer(CType("T"))),
                    ],
                )
            ],
        )
        writer = NimWriter(header_path="vec.hpp")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              GenericVector[T]* {.importcpp: "GenericVector", header: "vec.hpp", bycopy.} = object


            proc begin*[T](this: var GenericVector[T]): ptr T {.importcpp: "#.begin(@)", header: "vec.hpp".}

            proc `end`*[T](this: var GenericVector[T]): ptr T {.importcpp: "#.end(@)", header: "vec.hpp".}

            iterator items*[T](this: var GenericVector[T]): auto = {.inline.}
              var it = this.begin()
              while it != this.end():
                yield it[]
                inc it
        """)
        assert out == expected

    def test_multi_param_template_constructor(self) -> None:
        """Test multi-parameter template constructors generating '*0, '*1 importcpp args."""
        h = Header(
            path="pair.hpp",
            declarations=[
                Struct(
                    name="Pair",
                    template_params=["Key", "Val"],
                    is_cppclass=True,
                    constructors=[
                        Function(
                            name="Pair",
                            return_type=CType("void"),
                            parameters=[
                                Parameter(name="k", type=CType("Key")),
                                Parameter(name="v", type=CType("Val")),
                            ],
                        )
                    ],
                )
            ],
        )
        writer = NimWriter(header_path="pair.hpp")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Pair[Key, Val]* {.importcpp: "Pair", header: "pair.hpp", bycopy.} = object


            proc constructPair*[Key, Val](k: Key, v: Val): Pair[Key, Val] {.importcpp: "Pair<'*0, '*1>(@)", header: "pair.hpp", constructor.}
        """)
        assert out == expected

    def test_function_pointer_and_variadic(self) -> None:
        """Test FunctionPointer type formatting and variadic function handling."""
        fn_ptr_type = FunctionPointer(
            return_type=CType("int"),
            parameters=[Parameter("code", CType("int"))],
        )
        cb_typedef = Typedef(name="Callback", underlying_type=fn_ptr_type)
        log_fn = Function(
            name="log_message",
            return_type=CType("void"),
            parameters=[
                Parameter("level", CType("int")),
                Parameter("fmt", Pointer(CType("char"))),
            ],
            is_variadic=True,
        )
        h = Header(path="logger.h", declarations=[cb_typedef, log_fn])
        writer = NimWriter(header_path="logger.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Callback* = proc(code: cint): cint {.cdecl.}

            proc log_message*(level: cint, fmt: ptr cchar) {.importc: "log_message", header: "logger.h", varargs, cdecl.}
        """)
        assert out == expected

    def test_destructor_static_method_and_binary_operator(self) -> None:
        """Test C++ destructor, static method, and binary operator in Nim writer."""
        h = Header(
            path="math_ops.hpp",
            declarations=[
                Struct(
                    name="Vec2",
                    is_cppclass=True,
                    destructor=Function(name="~Vec2", return_type=CType("void")),
                    methods=[
                        Function(
                            name="create",
                            return_type=CType("Vec2"),
                            parameters=[Parameter("x", CType("float")), Parameter("y", CType("float"))],
                            is_static=True,
                        ),
                        Function(
                            name="operator+",
                            return_type=CType("Vec2"),
                            parameters=[Parameter("other", CType("Vec2"))],
                        ),
                    ],
                )
            ],
        )
        writer = NimWriter(header_path="math_ops.hpp")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Vec2* {.importcpp: "Vec2", header: "math_ops.hpp", bycopy.} = object


            proc create*(x: cfloat, y: cfloat): Vec2 {.importcpp: "Vec2::create(@)", header: "math_ops.hpp".}

            proc `+`*(this: var Vec2, other: Vec2): Vec2 {.importcpp: "(# + @)", header: "math_ops.hpp".}

            proc destroy*(this: var Vec2) {.importcpp: "#.~Vec2()", header: "math_ops.hpp".}
        """)
        assert out == expected

    def test_constant_none_value_skipped(self) -> None:
        """Test that constants with None value are omitted without defaulting to 0."""
        h = Header(
            path="consts.h",
            declarations=[
                Constant(name="VALID_CONST", value=42),
                Constant(name="UNDETERMINED_MACRO", value=None),
            ],
        )
        writer = NimWriter(header_path="consts.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            const
              VALID_CONST* = 42
        """)
        assert out == expected

    def test_union_struct(self) -> None:
        """Test union struct rendering with {.union.} pragma."""
        h = Header(
            path="data.h",
            declarations=[
                Struct(
                    name="DataUnion",
                    is_union=True,
                    fields=[
                        Field(name="i", type=CType("int")),
                        Field(name="f", type=CType("float")),
                    ],
                )
            ],
        )
        writer = NimWriter(header_path="data.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              DataUnion* {.importc: "union DataUnion", header: "data.h", union.} = object
                i*: cint
                f*: cfloat
        """)
        assert out == expected

    def test_anonymous_enum_emits_constants(self) -> None:
        """Test that anonymous enums emit their values into the const section."""
        h = Header(
            path="test.h",
            declarations=[
                Enum(
                    name="",
                    values=[EnumValue("FLAG_A", 1), EnumValue("FLAG_B", 2)],
                ),
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            const
              FLAG_A* = 1
              FLAG_B* = 2
        """)
        assert out == expected

    def test_typedef_self_referential_skipped(self) -> None:
        """Test that typedef struct foo foo is deduplicated when struct foo is emitted."""
        h = Header(
            path="test.h",
            declarations=[
                Struct(name="Point", fields=[Field("x", CType("int"))]),
                Typedef(name="Point", underlying_type=CType("struct Point")),
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Point* {.importc: "struct Point", header: "test.h", bycopy.} = object
                x*: cint
        """)
        assert out == expected

    def test_enum_function_collision_is_refused(self) -> None:
        """An enum and a function of one name are two symbols and one identifier.

        The writer used to emit ``status_enum`` for the type, which is a guess
        about which of the two the caller meant to reach by the name they wrote.
        ``tests/test_rename.py`` holds the rest of the collision behaviour; this
        pins that the old silent disambiguation is gone.
        """
        h = Header(
            path="test.h",
            declarations=[
                Enum(name="status", values=[EnumValue("STATUS_OK", 0)]),
                Function(name="status", return_type=CType("int")),
            ],
        )
        with pytest.raises(SymbolCollisionError) as excinfo:
            write_nim(h, header_path="test.h")
        assert "'status' (enum)" in str(excinfo.value)
        assert "'status' (function)" in str(excinfo.value)

    def test_unique_ptr_move_semantics(self) -> None:
        """Test UniquePtr type declaration with deleted =copy hook and move procs."""
        h = Header(
            path="owner.hpp",
            declarations=[
                Struct(
                    name="Owner",
                    is_cppclass=True,
                    fields=[Field("res", CType("std::unique_ptr<int>"))],
                )
            ],
        )
        out = write_nim(h, header_path="owner.hpp")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              UniquePtr*[T] {.importcpp: "std::unique_ptr<'0>", header: "<memory>".} = object
              Owner* {.importcpp: "Owner", header: "owner.hpp", bycopy.} = object
                res*: UniquePtr[cint]


            proc `=copy`*[T](dst: var UniquePtr[T], src: UniquePtr[T]) {.error: "std::unique_ptr cannot be copied in Nim; use std/moves.move() or sink".}

            proc move*[T](p: var UniquePtr[T]): UniquePtr[T] {.importcpp: "std::move(@)", header: "<utility>".}

            proc get*[T](p: UniquePtr[T]): ptr T {.importcpp: "#.get()", header: "<memory>".}

            proc reset*[T](p: var UniquePtr[T]) {.importcpp: "#.reset()", header: "<memory>".}
        """)
        assert out == expected

    def test_escape_ident_preserves_underscores(self) -> None:
        """Test that leading/trailing underscores are preserved distinctly without collisions."""
        h = Header(
            path="test.h",
            declarations=[
                Function(name="_foo", return_type=CType("void")),
                Function(name="foo_", return_type=CType("void")),
                Function(name="foo", return_type=CType("void")),
            ],
        )
        out = write_nim(h, header_path="test.h")
        assert 'proc u_foo*() {.importc: "_foo", header: "test.h", cdecl.}' in out
        assert 'proc foo_u*() {.importc: "foo_", header: "test.h", cdecl.}' in out
        assert 'proc foo*() {.importc: "foo", header: "test.h", cdecl.}' in out

    @pytest.mark.allow("subprocess")
    def test_nim_examples_compile(self, tmp_path) -> None:
        """Test that generated Nim examples compile cleanly with the Nim compiler."""
        import subprocess
        from pathlib import Path

        nim_bin = require_program("nim", install=NIM_INSTALL)

        repo_root = Path(__file__).parent.parent.parent
        example_files = [
            repo_root / "examples/nim/clap/example_plugin.nim",
            repo_root / "examples/nim/nng/example.nim",
            repo_root / "examples/nim/rtaudio/example.nim",
            repo_root / "examples/nim/rtmidi/example.nim",
        ]

        for example_file in example_files:
            assert example_file.exists(), f"Example file {example_file} missing"
            # Run nim compile check (-c compile only, no linking required)
            result = subprocess.run(
                [nim_bin, "c", "--backend:c", "-c", f"--outdir:{tmp_path}", str(example_file)],
                capture_output=True,
                text=True,
                cwd=example_file.parent,
            )
            assert result.returncode == 0, f"Failed to compile {example_file.name}:\n{result.stderr}\n{result.stdout}"


def _nim_cfg(header: Header, **options: object) -> str:
    """Scaffold ``header`` as a package and return the generated ``nim.cfg``."""
    layout = get_writer("nim").write_layout(
        header,
        ScaffoldOptions(package_name="demo", target_language="nim", layout="package", options=dict(options)),
    )
    return next(f.content for f in layout.files if f.path == "nim.cfg")


class TestCfgPathQuoting:
    """A path with a space must survive Nim's config parsing."""

    def test_path_is_single_quoted(self) -> None:
        """Nim strips the outer quotes and word-splits; the inner quotes survive."""
        assert _cfg_path_flag("-I", "/opt/na me") == '"-I\\"/opt/na me\\""'

    def test_single_quote_in_path_is_safe(self) -> None:
        """`\'` opens a character literal to Nim's config lexer, so it must not be the quote."""
        rendered = _cfg_path_flag("-I", "/opt/it's")
        assert rendered == '"-I\\"/opt/it\'s\\""', rendered

    def test_windows_separators_become_forward_slashes(self) -> None:
        """A backslash inside a Nim string literal would be read as an escape.

        Asserted on the flag the writer renders, not on `pathlib`: the separator to
        normalise is a property of the path, so this holds on any host rather than
        only on the one whose paths look like this.
        """
        rendered = _cfg_path_flag("-I", "C:\\Users\\a b")
        assert "\\\\" not in rendered, rendered
        assert rendered == '"-I\\"C:/Users/a b\\""', rendered

    def test_double_quote_in_path_is_refused(self) -> None:
        """No quoting of this exists in the format, so say so rather than emit a wrong flag."""
        with pytest.raises(ValueError, match="double quote"):
            _cfg_path_flag("-I", '/opt/sa"y')


class TestTypeNameCppDetection:
    """The C++-only test on a type name, at the granularity the parse produces."""

    @pytest.mark.parametrize(
        ("name", "in_cpp_unit", "in_c_unit"),
        [
            # Unambiguous in either language: C has no template-id and no `::`.
            ("map<int, int>", True, True),
            ("unique_ptr<int>", True, True),
            ("vector<int>", True, True),
            ("ns::Point", True, True),
            # A C tag keyword settles it wherever it appears.
            ("struct vector", False, False),
            ("union u", False, False),
            ("enum e", False, False),
            # Plain C spellings.
            ("int", False, False),
            ("unsigned long", False, False),
            ("size_t", False, False),
            # The undecidable ones. libclang reports `std::string` as the bare name
            # `string`, and a C `typedef struct {...} string;` reports the same, so
            # only the unit's language separates them.
            ("string", True, False),
            ("vector", True, False),
            ("exception", True, False),
            ("shared_ptr", True, False),
        ],
    )
    def test_type_name(self, name: str, in_cpp_unit: bool, in_c_unit: bool) -> None:
        assert _type_name_requires_cpp(name, unit_is_cpp=True) is in_cpp_unit
        assert _type_name_requires_cpp(name, unit_is_cpp=False) is in_c_unit


class TestNimCfg:
    """The generated nim.cfg carries the flags the package needs, and nothing invented."""

    def test_cpp_unit_selects_the_cpp_backend(self) -> None:
        cfg = _nim_cfg(Header(path="c.hpp", declarations=[Struct(name="C", is_cppclass=True)]))
        assert "--backend:cpp" in cfg

    def test_c_unit_does_not_select_the_cpp_backend(self) -> None:
        cfg = _nim_cfg(Header(path="c.h", declarations=[Function(name="add", return_type=CType("int"))]))
        assert "--backend:cpp" not in cfg

    def test_package_resolves_its_own_source_directory(self) -> None:
        """Without this the package builds only under nimble, which supplies srcDir."""
        assert '--path:"$config/src"' in _nim_cfg(Header(path="c.h", declarations=[]))

    def test_library_option_becomes_link_flags(self, tmp_path) -> None:
        """A real directory, not a POSIX literal: library_dirs is emitted resolved."""
        libdir = tmp_path / "counter"
        libdir.mkdir()
        cfg = _nim_cfg(
            Header(path="c.hpp", declarations=[Struct(name="C", is_cppclass=True)]),
            library="counter",
            library_dirs=str(libdir),
        )
        assert '--passL:"-lcounter"' in cfg
        assert f'--passL:"-L\\"{libdir.resolve().as_posix()}\\""' in cfg, cfg

    def test_multiple_libraries_each_get_a_flag(self) -> None:
        cfg = _nim_cfg(Header(path="c.h", declarations=[]), library=["a", "b"])
        assert '--passL:"-la"' in cfg
        assert '--passL:"-lb"' in cfg

    def test_no_library_is_declared_rather_than_guessed(self) -> None:
        """A guessed -l resolves to the wrong library or to none; say so instead."""
        cfg = _nim_cfg(Header(path="c.h", declarations=[]))
        assert '--passL:"-l' not in cfg
        assert "--writer-opt nim:library=" in cfg

    def test_header_directory_becomes_an_include_path(self, tmp_path) -> None:
        header = tmp_path / "inc" / "c.hpp"
        header.parent.mkdir()
        header.write_text("")
        cfg = _nim_cfg(Header(path=str(header), declarations=[]))
        assert f'--passC:"-I\\"{header.parent.resolve().as_posix()}\\""' in cfg, cfg

    def test_parse_include_dirs_and_defines_reach_the_config(self, tmp_path) -> None:
        """A real directory, not a POSIX literal: include paths are emitted resolved."""
        extra = tmp_path / "extra"
        extra.mkdir()
        layout = get_writer("nim").write_layout(
            Header(path="c.h", declarations=[]),
            ScaffoldOptions(
                package_name="demo",
                target_language="nim",
                layout="package",
                extra_context={"include_dirs": [str(extra)], "defines": ["FOO=1"]},
            ),
        )
        cfg = next(f.content for f in layout.files if f.path == "nim.cfg")
        assert f'--passC:"-I\\"{extra.resolve().as_posix()}\\""' in cfg, cfg
        assert '--passC:"-DFOO=1"' in cfg

    def test_library_dirs_are_resolved(self, tmp_path) -> None:
        """A relative -L resolves against the linker's working directory, not the package's."""
        libdir = tmp_path / "lib"
        libdir.mkdir()
        relative = str(libdir) + os.sep + "."
        cfg = _nim_cfg(Header(path="c.h", declarations=[]), library="demo", library_dirs=relative)
        assert f'--passL:"-L\\"{libdir.resolve().as_posix()}\\""' in cfg, cfg
        assert relative not in cfg, cfg

    def test_unordered_option_values_are_emitted_in_a_stable_order(self) -> None:
        """A set would order the flags by iteration, defeating regenerate-and-diff.

        The order asserted is the SORTED one, which is the whole claim. Comparing
        two sets built in one process establishes nothing on its own: set
        iteration order is a function of the hash seed, so within a process two
        equal sets always iterate alike and the comparison cannot fail. The
        cross-process half of the property is measured by
        ``test_the_order_is_the_same_under_a_different_hash_seed``, which is where
        the seed can actually differ.
        """
        first = _nim_cfg(Header(path="c.h", declarations=[]), library={"zlib", "png", "aaa"})
        order = [line for line in first.splitlines() if line.startswith('--passL:"-l')]
        assert order == ['--passL:"-laaa"', '--passL:"-lpng"', '--passL:"-lzlib"'], order

    def test_unordered_extra_context_values_are_emitted_in_a_stable_order(self) -> None:
        """`extra_context` bypasses option coercion, so the writer sorts it itself."""

        def cfg_for(defines: set[str]) -> str:
            layout = get_writer("nim").write_layout(
                Header(path="c.h", declarations=[]),
                ScaffoldOptions(
                    package_name="demo",
                    target_language="nim",
                    layout="package",
                    extra_context={"defines": defines},
                ),
            )
            return next(f.content for f in layout.files if f.path == "nim.cfg")

        first = cfg_for({"ZED=1", "ALPHA=1", "MID=1"})
        order = [line for line in first.splitlines() if line.startswith('--passC:"-D')]
        assert order == ['--passC:"-DALPHA=1"', '--passC:"-DMID=1"', '--passC:"-DZED=1"'], order

    def test_relatively_passed_include_dir_does_not_duplicate_the_header_directory(self, tmp_path) -> None:
        """The dedup compares resolved paths, or the same directory is emitted twice."""
        header = tmp_path / "inc" / "c.h"
        header.parent.mkdir()
        header.write_text("")
        layout = get_writer("nim").write_layout(
            Header(path=str(header), declarations=[]),
            ScaffoldOptions(
                package_name="demo",
                target_language="nim",
                layout="package",
                extra_context={"include_dirs": [str(header.parent) + os.sep + "."]},
            ),
        )
        cfg = next(f.content for f in layout.files if f.path == "nim.cfg")
        # Count the flags, not one spelling of them: an unresolved duplicate is a
        # *different* string ("<dir>/." vs "<dir>"), so counting the resolved form
        # alone would report 1 whether or not the dedup ran.
        include_flags = [line for line in cfg.splitlines() if line.startswith('--passC:"-I')]
        assert len(include_flags) == 1, include_flags
        assert f'-I\\"{header.parent.resolve().as_posix()}\\"' in include_flags[0]


class TestNimCppTripwire:
    """A C++ target gets a compile-and-link tripwire instead of a loadLib one."""

    HEADER = Header(
        path="counter.hpp",
        declarations=[
            Struct(
                name="Counter",
                is_cppclass=True,
                fields=[Field("total", CType("int"))],
                constructors=[
                    Function(name="Counter", return_type=CType("void"), parameters=[Parameter("start", CType("int"))])
                ],
                methods=[
                    Function(name="add", return_type=CType("void"), parameters=[Parameter("n", CType("int"))]),
                    Function(name="value", return_type=CType("int"), is_const=True),
                    Function(
                        name="addFrom",
                        return_type=CType("void"),
                        parameters=[Parameter("source", Reference(CType("int")))],
                    ),
                ],
            )
        ],
    )

    def _tripwire(self, header: Header) -> str:
        layout = get_writer("nim").write_layout(
            header,
            ScaffoldOptions(package_name="counter", target_language="nim", layout="package"),
        )
        return next(f.content for f in layout.files if f.path == "tests/test_tripwire.nim")

    def test_cpp_tripwire_does_not_use_dynlib(self) -> None:
        """loadLib looks for an unmangled name that an importcpp binding never has."""
        tripwire = self._tripwire(self.HEADER)
        assert "loadLib" not in tripwire
        assert "symAddr" not in tripwire

    def test_cpp_tripwire_references_every_entry_point(self) -> None:
        """Referencing each entry point is what forces the linker to resolve it."""
        tripwire = self._tripwire(self.HEADER)
        assert "add(self[], a0[])" in tripwire
        assert "discard value(self[])" in tripwire
        assert "discard constructCounter(a0[])" in tripwire

    def test_cpp_tripwire_probes_are_not_executed(self) -> None:
        """A probe that ran would dereference nil; the build is the assertion."""
        tripwire = self._tripwire(self.HEADER)
        assert "var hkRunLinkProbes = false" in tripwire
        assert "if hkRunLinkProbes:" in tripwire

    def test_reference_parameter_is_probed_by_pointer(self) -> None:
        """A `var T` parameter cannot be wrapped as `ptr var T`; `ptr T` derefs to it."""
        tripwire = self._tripwire(self.HEADER)
        assert "ptr var" not in tripwire
        assert "addFrom(self[], a0[])" in tripwire
        assert "a0: ptr cint" in tripwire

    def test_cpp_tripwire_asserts_type_completeness(self) -> None:
        """sizeof is answered by the C++ compiler, so a forward declaration fails it."""
        assert "check sizeof(Counter) > 0" in self._tripwire(self.HEADER)

    def test_c_target_keeps_the_dynlib_tripwire(self) -> None:
        """A C library does have unmangled symbols in a shared object; keep checking them."""
        tripwire = self._tripwire(Header(path="c.h", declarations=[Function(name="add", return_type=CType("int"))]))
        assert "loadLib" in tripwire
        assert 'symAddr("add")' in tripwire


class TestGeneratedPathsSurviveNimStringLiterals:
    """Every path the writer emits lands inside a Nim string literal."""

    #: A Windows path exercising both escapes Nim would otherwise read: `\U` and `\x`.
    WINDOWS_PATH = "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pkg\\shape.hpp"

    def test_header_pragma_path_has_no_backslash(self) -> None:
        """`\\U` and `\\x` in a header path are escapes to Nim, not separators.

        Left as-is the generated bindings do not parse at all:
        ``Error: expected a hex digit, but found: s; maybe prepend with 0``.
        """
        out = write_nim(Header(path=self.WINDOWS_PATH, declarations=[Function(name="f", return_type=CType("void"))]))
        assert "\\" not in out, out
        assert 'header: "C:/Users/runneradmin/AppData/Local/Temp/pkg/shape.hpp"' in out, out

    def test_cfg_flag_path_has_no_backslash(self) -> None:
        """The separators must be gone; the two escaping the inner quotes must remain.

        Asserted against the whole rendered flag. The previous form tested for two
        *consecutive* backslashes, which no path on any platform produces, so it
        passed with the normalisation patched out -- while its two siblings here
        went red under exactly that mutation.
        """
        rendered = _cfg_path_flag("-I", self.WINDOWS_PATH)
        assert rendered == '"-I\\"C:/Users/runneradmin/AppData/Local/Temp/pkg/shape.hpp\\""', rendered

    def test_posix_paths_are_untouched(self) -> None:
        """The normalisation must be a no-op where there is nothing to normalise."""
        out = write_nim(
            Header(path="/usr/include/shape.h", declarations=[Function(name="f", return_type=CType("void"))])
        )
        assert 'header: "/usr/include/shape.h"' in out, out


class TestEnumWidthProvenance:
    """A width the parser did not establish must not be presented as one it did."""

    def test_known_underlying_type_sets_the_size(self) -> None:
        out = write_nim(
            Header(
                path="e.hpp",
                declarations=[
                    Enum(name="E", values=[EnumValue("a", 0)], underlying_type="long long", underlying_type_known=True)
                ],
            ),
            header_path="e.hpp",
        )
        assert "size: sizeof(clonglong)" in out, out
        assert "UNSUPPORTED" not in out, out

    def test_absent_underlying_type_is_cint_without_a_diagnostic(self) -> None:
        """A header that declares none leaves a C enum int-compatible; that is not a guess."""
        out = write_nim(
            Header(
                path="e.h",
                declarations=[
                    Enum(name="E", values=[EnumValue("a", 0)], underlying_type=None, underlying_type_known=True)
                ],
            ),
            header_path="e.h",
        )
        assert "size: sizeof(cint)" in out, out
        assert "UNSUPPORTED" not in out, out

    def test_unestablished_underlying_type_says_the_width_is_assumed(self) -> None:
        """`known=False` means the parser may have missed a clause that is there.

        tree-sitter's C grammar has no production for `enum E : long long`, so in a
        `.h` the width is unknown and `sizeof(cint)` is four bytes whatever the
        header said. Emitting it silently is the failure mode; saying so is not.
        """
        out = write_nim(
            Header(
                path="e.h",
                declarations=[
                    Enum(name="E", values=[EnumValue("a", 0)], underlying_type=None, underlying_type_known=False)
                ],
            ),
            header_path="e.h",
        )
        assert "size: sizeof(cint)" in out, out
        assert "UNSUPPORTED: the underlying type of 'E' was not established" in out, out


class TestCvQualifiersDoNotReachTheLookup:
    """`const` describes mutability, not the type, so it must not join the name."""

    @pytest.mark.parametrize(
        ("qualifiers", "expected"),
        [
            (["unsigned"], "cuint"),
            (["const", "unsigned"], "cuint"),
            (["unsigned", "const"], "cuint"),
            (["const"], "cint"),
            (["volatile", "unsigned"], "cuint"),
            (["restrict", "unsigned"], "cuint"),
        ],
    )
    def test_cv_qualifiers_are_dropped_before_the_primitive_lookup(self, qualifiers: list[str], expected: str) -> None:
        """`const unsigned int` is not a distinct primitive; `unsigned int` is."""
        out = write_nim(
            Header(
                path="t.h",
                declarations=[Typedef(name="alias", underlying_type=CType("int", qualifiers=qualifiers))],
            ),
            header_path="t.h",
        )
        assert f"alias* = {expected}" in out, out


class TestTheRendererReadsTheUnitsLanguage:
    """``_type_name_requires_cpp`` decided correctly and the renderer ignored it.

    The predicate was given the unit's recorded language and tested both ways.
    The renderer beside it kept mapping a bare ``string`` to ``CppString``
    unconditionally, and asked ``_function_requires_cpp`` with its
    ``unit_is_cpp=True`` default rather than with the unit's answer -- so a pure C
    header declaring ``typedef char string;`` produced ``importcpp:
    "std::string"`` and ``header: "<string>"`` inside a package whose ``nim.cfg``
    correctly did *not* select the C++ backend. Consuming it against a real C
    library fails with ``fatal error: 'string' file not found``; the package is
    unusable, and every assertion anyone had written about the emitted text
    passed.
    """

    @staticmethod
    def header(language: str) -> Header:
        return Header(
            path="unit.h",
            language=language,
            declarations=[
                Typedef(name="string", underlying_type=CType("char")),
                Function(
                    name="take",
                    return_type=CType("int"),
                    parameters=[Parameter("s", Pointer(CType("string")))],
                ),
            ],
        )

    def test_a_c_unit_binds_string_as_the_c_typedef_it_is(self) -> None:
        out = write_nim(self.header("c"), header_path="unit.h")
        assert "CppString" not in out, out
        assert "std::string" not in out, out
        assert 'importc: "take"' in out, out
        assert "string* = cchar" in out, out

    def test_a_cpp_unit_still_binds_string_as_std_string(self) -> None:
        """The negative control: the C++ path must be untouched by the gate."""
        out = write_nim(
            Header(
                path="unit.hpp",
                language="cpp",
                declarations=[
                    Function(
                        name="take",
                        return_type=CType("int"),
                        parameters=[Parameter("s", Pointer(CType("string")))],
                    )
                ],
            ),
            header_path="unit.hpp",
        )
        assert 'CppString* {.importcpp: "std::string", header: "<string>".} = object' in out, out
        assert "ptr CppString" in out, out
        assert 'importcpp: "take(@)"' in out, out

    def test_the_pragma_and_the_backend_selection_agree(self) -> None:
        """One fact, read twice, must not give two answers.

        ``nim.cfg`` omitting ``--backend:cpp`` while the bindings carry
        ``importcpp`` is the exact contradiction that shipped: neither half is
        wrong on its own and the package cannot be built.
        """
        layout = get_writer("nim").write_layout(
            self.header("c"),
            ScaffoldOptions(package_name="unit", target_language="nim", layout="package"),
        )
        cfg = next(f.content for f in layout.files if f.path == "nim.cfg")
        bindings = next(f.content for f in layout.files if f.path.endswith("unit.nim"))
        assert "--backend:cpp" not in cfg, cfg
        assert "importcpp" not in bindings, bindings


@pytest.mark.allow("subprocess")
class TestSetOrderingIsStableAcrossProcesses:
    """The property is cross-process, so it is measured across processes.

    ``set`` iteration order is a function of the interpreter's hash seed. Two
    sets built inside one process therefore always iterate alike, and a
    same-process ``first == second`` comparison of two equal sets cannot fail
    whatever the writer does with them -- it reads as a regenerate-and-diff gate
    and is one only by coincidence of never having been run twice with different
    seeds.
    """

    #: Members chosen so that no observed hash seed iterates them in sorted order,
    #: and the sorted order is therefore a real claim rather than a coin flip.
    LIBRARIES = ("zlib", "png", "aaa")

    @staticmethod
    def _cfg_under_seed(seed: str) -> str:
        import subprocess
        import sys

        script = textwrap.dedent("""\
            from headerkit.ir import Header
            from headerkit.scaffold import ScaffoldOptions
            from headerkit.writers import get_writer

            layout = get_writer("nim").write_layout(
                Header(path="c.h", declarations=[]),
                ScaffoldOptions(
                    package_name="demo",
                    target_language="nim",
                    layout="package",
                    options={"library": {"zlib", "png", "aaa"}},
                    extra_context={"defines": {"ZED=1", "ALPHA=1", "MID=1"}},
                ),
            )
            print(next(f.content for f in layout.files if f.path == "nim.cfg"))
        """)
        result = subprocess.run(  # noqa: S603
            [sys.executable, "-c", script],
            capture_output=True,
            text=True,
            check=False,
            env={**os.environ, "PYTHONHASHSEED": seed},
        )
        assert result.returncode == 0, result.stderr
        return result.stdout

    def test_the_order_is_the_same_under_a_different_hash_seed(self) -> None:
        """Both paths at once: writer-option coercion and the writer's own sort."""
        # Seeds measured to iterate these members differently from one another,
        # so the two runs really do disagree about set order before the sort.
        first = self._cfg_under_seed("0")
        second = self._cfg_under_seed("1")
        assert first == second, f"the generated nim.cfg depends on the hash seed:\n{first}\n---\n{second}"
        libs = [line for line in first.splitlines() if line.startswith('--passL:"-l')]
        defines = [line for line in first.splitlines() if line.startswith('--passC:"-D')]
        assert libs == ['--passL:"-laaa"', '--passL:"-lpng"', '--passL:"-lzlib"'], libs
        assert defines == ['--passC:"-DALPHA=1"', '--passC:"-DMID=1"', '--passC:"-DZED=1"'], defines
