"""Tests for the Nim writer."""

from __future__ import annotations

import textwrap

import pytest

from headerkit.ir import (
    BaseSpecifier,
    Constant,
    CType,
    Enum,
    EnumValue,
    Field,
    Function,
    FunctionPointer,
    Header,
    Parameter,
    Pointer,
    Reference,
    Struct,
    Typedef,
    Variable,
)
from headerkit.writers import get_writer
from headerkit.writers.nim import NimWriter, write_nim
from tests.skip_policy import NIM_INSTALL, require_program


class TestNimWriter:
    def test_nim_writer_registration(self) -> None:
        """Test that nim writer is registered and has correct metadata."""
        writer = get_writer("nim")
        assert isinstance(writer, NimWriter)
        assert writer.name == "nim"
        assert writer.format_description == "Nim bindings with C and C++ interop"

    def test_primitive_function_and_escape(self) -> None:
        """Test basic C function with types and keyword escaping."""
        h = Header(
            path="test.h",
            declarations=[
                Function(
                    name="type",
                    return_type=CType("int"),
                    parameters=[Parameter(name="var", type=CType("int"))],
                )
            ],
        )
        writer = NimWriter(header_path="test.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            proc `type`*(`var`: cint): cint {.importc: "type", header: "test.h", cdecl.}
        """)
        assert out == expected

    def test_struct_with_fields(self) -> None:
        """Test C struct with primitive and pointer fields."""
        h = Header(
            path="test.h",
            declarations=[
                Struct(
                    name="Point",
                    fields=[
                        Field("x", CType("int")),
                        Field("y", CType("int")),
                        Field("label", Pointer(CType("char", ["const"]))),
                    ],
                )
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Point* {.importc: "struct Point", header: "test.h", bycopy.} = object
                x*: cint
                y*: cint
                label*: cstring
        """)
        assert out == expected

    def test_cpp_class_with_templates_and_methods(self) -> None:
        """Test C++ class with template parameters, methods, inheritance, and constructors."""
        h = Header(
            path="test.hpp",
            declarations=[
                Struct(
                    name="Container",
                    template_params=["T"],
                    is_cppclass=True,
                    bases=[BaseSpecifier(name="Base")],
                    fields=[Field("value", CType("T"))],
                    constructors=[
                        Function(
                            name="Container",
                            return_type=CType("void"),
                            parameters=[Parameter("initVal", CType("T"), default_value="0")],
                        )
                    ],
                    methods=[
                        Function(
                            name="getVal",
                            return_type=CType("T"),
                            is_const=True,
                        ),
                        Function(
                            name="setVal",
                            return_type=CType("void"),
                            parameters=[Parameter("v", Reference(CType("T")))],
                        ),
                    ],
                )
            ],
        )
        out = write_nim(h, header_path="test.hpp")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Container*[T] {.importcpp: "Container", header: "test.hpp", bycopy.} = object of Base
                value*: T


            proc getVal*[T](this: Container[T]): T {.importcpp: "#.getVal(@)", header: "test.hpp".}

            proc setVal*[T](this: var Container[T], v: var T) {.importcpp: "#.setVal(@)", header: "test.hpp".}

            proc constructContainer*[T](initVal: T = 0): Container[T] {.importcpp: "Container<'*0>(@)", header: "test.hpp", constructor.}
        """)
        assert out == expected

    def test_enum_and_constants(self) -> None:
        """Test enum and constant generation."""
        h = Header(
            path="test.h",
            declarations=[
                Enum(
                    name="Status",
                    values=[EnumValue("OK", 0), EnumValue("ERR", 1)],
                ),
                Constant(name="MAX_COUNT", value=100),
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Status* {.size: sizeof(cint), importc: "enum Status", header: "test.h".} = enum
                OK = 0
                ERR = 1

            const
              MAX_COUNT* = 100
        """)
        assert out == expected

    def test_cpp_advanced_features(self) -> None:
        """Test C++ smart pointers, move semantics, operators, and container iterators."""
        h = Header(
            path="test.hpp",
            declarations=[
                Struct(
                    name="MyVector",
                    fields=[
                        Field("ptr", CType("std::shared_ptr<int>")),
                    ],
                    methods=[
                        Function(
                            name="operator[]",
                            return_type=Reference(CType("int")),
                            parameters=[Parameter("index", CType("size_t"))],
                        ),
                        Function(
                            name="push",
                            return_type=CType("void"),
                            parameters=[Parameter("val", Reference(CType("int"), is_rvalue=True))],
                        ),
                        Function(
                            name="begin",
                            return_type=Pointer(CType("int")),
                        ),
                        Function(
                            name="end",
                            return_type=Pointer(CType("int")),
                        ),
                    ],
                )
            ],
        )
        out = write_nim(h, header_path="test.hpp")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              SharedPtr*[T] {.importcpp: "std::shared_ptr<'0>", header: "<memory>".} = object
              MyVector* {.importcpp: "MyVector", header: "test.hpp", bycopy.} = object
                `ptr`*: SharedPtr[cint]


            proc inc*[T](p: var ptr T) {.inline.} =
              p = cast[ptr T](cast[uint](p) + sizeof(T).uint)

            proc get*[T](p: SharedPtr[T]): ptr T {.importcpp: "#.get()", header: "<memory>".}

            proc reset*[T](p: var SharedPtr[T]) {.importcpp: "#.reset()", header: "<memory>".}

            proc useCount*[T](p: SharedPtr[T]): clong {.importcpp: "#.use_count()", header: "<memory>".}

            proc `[]`*(this: var MyVector, index: csize_t): var cint {.importcpp: "#[@]", header: "test.hpp".}

            proc push*(this: var MyVector, val: sink cint) {.importcpp: "#.push(@)", header: "test.hpp".}

            proc begin*(this: var MyVector): ptr cint {.importcpp: "#.begin(@)", header: "test.hpp".}

            proc `end`*(this: var MyVector): ptr cint {.importcpp: "#.end(@)", header: "test.hpp".}

            iterator items*(this: var MyVector): auto {.inline.} =
              var it = this.begin()
              while it != this.end():
                yield it[]
                inc it
        """)
        assert out == expected

    def test_typedef_output(self) -> None:
        """Test Typedef declaration rendering."""
        h = Header(
            path="types.h",
            declarations=[
                Typedef(name="ColorId", underlying_type=CType("unsigned int")),
                Typedef(name="type", underlying_type=Pointer(CType("void"))),
            ],
        )
        writer = NimWriter(header_path="types.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              ColorId* = cuint
              `type`* = pointer
        """)
        assert out == expected

    def test_variable_output(self) -> None:
        """Test extern global Variable rendering."""
        h = Header(
            path="globals.h",
            declarations=[
                Variable(name="global_dpi", type=CType("int")),
                Variable(name="yield", type=CType("double")),
            ],
        )
        writer = NimWriter(header_path="globals.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            var global_dpi* {.importc: "global_dpi", header: "globals.h".}: cint
            var `yield`* {.importc: "yield", header: "globals.h".}: cdouble
        """)
        assert out == expected

    def test_template_struct_iterators(self) -> None:
        """Test template container iterator generation."""
        h = Header(
            path="vec.hpp",
            declarations=[
                Struct(
                    name="GenericVector",
                    template_params=["T"],
                    is_cppclass=True,
                    methods=[
                        Function(name="begin", return_type=Pointer(CType("T"))),
                        Function(name="end", return_type=Pointer(CType("T"))),
                    ],
                )
            ],
        )
        writer = NimWriter(header_path="vec.hpp")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              GenericVector*[T] {.importcpp: "GenericVector", header: "vec.hpp", bycopy.} = object


            proc inc*[T](p: var ptr T) {.inline.} =
              p = cast[ptr T](cast[uint](p) + sizeof(T).uint)

            proc begin*[T](this: var GenericVector[T]): ptr T {.importcpp: "#.begin(@)", header: "vec.hpp".}

            proc `end`*[T](this: var GenericVector[T]): ptr T {.importcpp: "#.end(@)", header: "vec.hpp".}

            iterator items*[T](this: var GenericVector[T]): auto {.inline.} =
              var it = this.begin()
              while it != this.end():
                yield it[]
                inc it
        """)
        assert out == expected

    def test_multi_param_template_constructor(self) -> None:
        """Test multi-parameter template constructors generating '*0, '*1 importcpp args."""
        h = Header(
            path="pair.hpp",
            declarations=[
                Struct(
                    name="Pair",
                    template_params=["Key", "Val"],
                    is_cppclass=True,
                    constructors=[
                        Function(
                            name="Pair",
                            return_type=CType("void"),
                            parameters=[
                                Parameter(name="k", type=CType("Key")),
                                Parameter(name="v", type=CType("Val")),
                            ],
                        )
                    ],
                )
            ],
        )
        writer = NimWriter(header_path="pair.hpp")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Pair*[Key, Val] {.importcpp: "Pair", header: "pair.hpp", bycopy.} = object


            proc constructPair*[Key, Val](k: Key, v: Val): Pair[Key, Val] {.importcpp: "Pair<'*0, '*1>(@)", header: "pair.hpp", constructor.}
        """)
        assert out == expected

    def test_function_pointer_and_variadic(self) -> None:
        """Test FunctionPointer type formatting and variadic function handling."""
        fn_ptr_type = FunctionPointer(
            return_type=CType("int"),
            parameters=[Parameter("code", CType("int"))],
        )
        cb_typedef = Typedef(name="Callback", underlying_type=fn_ptr_type)
        log_fn = Function(
            name="log_message",
            return_type=CType("void"),
            parameters=[
                Parameter("level", CType("int")),
                Parameter("fmt", Pointer(CType("char"))),
            ],
            is_variadic=True,
        )
        h = Header(path="logger.h", declarations=[cb_typedef, log_fn])
        writer = NimWriter(header_path="logger.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Callback* = proc(code: cint): cint {.cdecl.}

            proc log_message*(level: cint, fmt: ptr cchar) {.importc: "log_message", header: "logger.h", varargs, cdecl.}
        """)
        assert out == expected

    def test_destructor_static_method_and_binary_operator(self) -> None:
        """Test C++ destructor, static method, and binary operator in Nim writer."""
        h = Header(
            path="math_ops.hpp",
            declarations=[
                Struct(
                    name="Vec2",
                    is_cppclass=True,
                    destructor=Function(name="~Vec2", return_type=CType("void")),
                    methods=[
                        Function(
                            name="create",
                            return_type=CType("Vec2"),
                            parameters=[Parameter("x", CType("float")), Parameter("y", CType("float"))],
                            is_static=True,
                        ),
                        Function(
                            name="operator+",
                            return_type=CType("Vec2"),
                            parameters=[Parameter("other", CType("Vec2"))],
                        ),
                    ],
                )
            ],
        )
        writer = NimWriter(header_path="math_ops.hpp")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Vec2* {.importcpp: "Vec2", header: "math_ops.hpp", bycopy.} = object


            proc create*(self_type: typedesc[Vec2], x: cfloat, y: cfloat): Vec2 {.importcpp: "Vec2::create(@)", header: "math_ops.hpp".}

            proc `+`*(this: var Vec2, other: Vec2): Vec2 {.importcpp: "(# + @)", header: "math_ops.hpp".}

            proc destroy*(this: var Vec2) {.importcpp: "#.~Vec2()", header: "math_ops.hpp".}
        """)
        assert out == expected

    def test_constant_none_value_skipped(self) -> None:
        """Test that constants with None value are omitted without defaulting to 0."""
        h = Header(
            path="consts.h",
            declarations=[
                Constant(name="VALID_CONST", value=42),
                Constant(name="UNDETERMINED_MACRO", value=None),
            ],
        )
        writer = NimWriter(header_path="consts.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            const
              VALID_CONST* = 42
        """)
        assert out == expected

    def test_union_struct(self) -> None:
        """Test union struct rendering with {.union.} pragma."""
        h = Header(
            path="data.h",
            declarations=[
                Struct(
                    name="DataUnion",
                    is_union=True,
                    fields=[
                        Field(name="i", type=CType("int")),
                        Field(name="f", type=CType("float")),
                    ],
                )
            ],
        )
        writer = NimWriter(header_path="data.h")
        out = writer.write(h)

        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              DataUnion* {.importc: "union DataUnion", header: "data.h", union.} = object
                i*: cint
                f*: cfloat
        """)
        assert out == expected

    def test_anonymous_enum_emits_constants(self) -> None:
        """Test that anonymous enums emit their values into the const section."""
        h = Header(
            path="test.h",
            declarations=[
                Enum(
                    name="",
                    values=[EnumValue("FLAG_A", 1), EnumValue("FLAG_B", 2)],
                ),
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            const
              FLAG_A* = 1
              FLAG_B* = 2
        """)
        assert out == expected

    def test_typedef_self_referential_skipped(self) -> None:
        """Test that typedef struct foo foo is deduplicated when struct foo is emitted."""
        h = Header(
            path="test.h",
            declarations=[
                Struct(name="Point", fields=[Field("x", CType("int"))]),
                Typedef(name="Point", underlying_type=CType("struct Point")),
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              Point* {.importc: "struct Point", header: "test.h", bycopy.} = object
                x*: cint
        """)
        assert out == expected

    def test_enum_function_collision_disambiguated(self) -> None:
        """Test that an enum whose name collides with a function is suffixed with _enum."""
        h = Header(
            path="test.h",
            declarations=[
                Enum(name="status", values=[EnumValue("STATUS_OK", 0)]),
                Function(name="status", return_type=CType("int")),
            ],
        )
        out = write_nim(h, header_path="test.h")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              status_enum* {.size: sizeof(cint), importc: "enum status", header: "test.h".} = enum
                STATUS_OK = 0

            proc status*(): cint {.importc: "status", header: "test.h", cdecl.}
        """)
        assert out == expected

    def test_unique_ptr_move_semantics(self) -> None:
        """Test UniquePtr type declaration with deleted =copy hook and move procs."""
        h = Header(
            path="owner.hpp",
            declarations=[
                Struct(
                    name="Owner",
                    is_cppclass=True,
                    fields=[Field("res", CType("std::unique_ptr<int>"))],
                )
            ],
        )
        out = write_nim(h, header_path="owner.hpp")
        expected = textwrap.dedent("""\
            # Generated by headerkit

            type
              UniquePtr*[T] {.importcpp: "std::unique_ptr<'0>", header: "<memory>".} = object
              Owner* {.importcpp: "Owner", header: "owner.hpp", bycopy.} = object
                res*: UniquePtr[cint]


            proc `=copy`*[T](dst: var UniquePtr[T], src: UniquePtr[T]) {.error: "std::unique_ptr cannot be copied in Nim; use std/moves.move() or sink".}

            proc move*[T](p: var UniquePtr[T]): UniquePtr[T] {.importcpp: "std::move(@)", header: "<utility>".}

            proc get*[T](p: UniquePtr[T]): ptr T {.importcpp: "#.get()", header: "<memory>".}

            proc reset*[T](p: var UniquePtr[T]) {.importcpp: "#.reset()", header: "<memory>".}
        """)
        assert out == expected

    def test_escape_ident_preserves_underscores(self) -> None:
        """Test that leading/trailing underscores are preserved distinctly without collisions."""
        h = Header(
            path="test.h",
            declarations=[
                Function(name="_foo", return_type=CType("void")),
                Function(name="foo_", return_type=CType("void")),
                Function(name="foo", return_type=CType("void")),
            ],
        )
        out = write_nim(h, header_path="test.h")
        assert 'proc u_foo*() {.importc: "_foo", header: "test.h", cdecl.}' in out
        assert 'proc foo_u*() {.importc: "foo_", header: "test.h", cdecl.}' in out
        assert 'proc foo*() {.importc: "foo", header: "test.h", cdecl.}' in out

    @pytest.mark.allow("subprocess")
    def test_nim_examples_compile(self, tmp_path) -> None:
        """Test that generated Nim examples compile cleanly with the Nim compiler."""
        import subprocess
        from pathlib import Path

        nim_bin = require_program("nim", install=NIM_INSTALL)

        repo_root = Path(__file__).parent.parent.parent
        example_files = [
            repo_root / "examples/nim/clap/example_plugin.nim",
            repo_root / "examples/nim/nng/example.nim",
            repo_root / "examples/nim/rtaudio/example.nim",
            repo_root / "examples/nim/rtmidi/example.nim",
        ]

        for example_file in example_files:
            assert example_file.exists(), f"Example file {example_file} missing"
            # Run nim compile check (-c compile only, no linking required)
            result = subprocess.run(
                [nim_bin, "c", "--backend:c", "-c", f"--outdir:{tmp_path}", str(example_file)],
                capture_output=True,
                text=True,
                cwd=example_file.parent,
            )
            assert result.returncode == 0, f"Failed to compile {example_file.name}:\n{result.stderr}\n{result.stdout}"


class TestNimAccessSpecifierFiltering:
    """Private and protected members must never be emitted by NimWriter.

    Emitting private or protected C++ members causes downstream C++ compiler errors
    because Nim importcpp procs/accessors attempt to access inaccessible C++ symbols.
    """

    def test_private_and_protected_members_are_excluded(self) -> None:
        struct = Struct(
            name="Widget",
            is_cppclass=True,
            fields=[
                Field(name="public_val", type=CType("int"), access="public"),
                Field(name="secret_val", type=CType("int"), access="private"),
                Field(name="protected_val", type=CType("int"), access="protected"),
            ],
            methods=[
                Function(name="public_method", return_type=CType("void"), access="public"),
                Function(name="secret_method", return_type=CType("void"), access="private"),
                Function(name="protected_method", return_type=CType("void"), access="protected"),
            ],
            constructors=[
                Function(name="Widget", return_type=CType("void"), access="public"),
                Function(
                    name="Widget",
                    return_type=CType("void"),
                    access="private",
                    parameters=[Parameter(name="secret", type=CType("int"))],
                ),
            ],
            bases=[
                BaseSpecifier(name="PublicBase", access="public"),
                BaseSpecifier(name="SecretBase", access="private"),
            ],
        )
        h = Header(path="widget.hpp", declarations=[struct])
        out = write_nim(h, header_path="widget.hpp")

        # Public members must be emitted
        assert "public_val*: cint" in out
        assert "public_method*" in out
        assert "proc constructWidget*()" in out
        assert "of PublicBase" in out

        # Private and protected members must be absent
        assert "secret_val" not in out
        assert "protected_val" not in out
        assert "secret_method" not in out
        assert "protected_method" not in out
        assert "SecretBase" not in out
        assert "constructWidget*(secret:" not in out

    def test_assignment_operator_does_not_crash_lexer(self) -> None:
        """operator= must not be emitted as backticked '=' which the Nim lexer rejects."""
        struct = Struct(
            name="Value",
            is_cppclass=True,
            methods=[
                Function(
                    name="operator=",
                    return_type=CType("Value"),
                    access="public",
                    parameters=[Parameter(name="other", type=CType("Value"))],
                ),
            ],
        )
        h = Header(path="val.hpp", declarations=[struct])
        out = write_nim(h, header_path="val.hpp")
        assert "`=`" not in out

    @pytest.mark.allow("subprocess")
    def test_nim_cpp_class_access_filtering_compiles(self, tmp_path) -> None:
        """Verify that emitted Nim bindings for a C++ class with private members compile and execute."""
        import subprocess

        from headerkit.backends.libclang import LibclangBackend

        nim_bin = require_program("nim", install=NIM_INSTALL)

        header_content = textwrap.dedent("""\
            #pragma once
            class Counter {
            public:
                Counter();
                void increment();
                int get_count() const;
            private:
                int count;
                void reset_internal();
            };
        """)
        header_file = tmp_path / "counter.hpp"
        header_file.write_text(header_content)

        cpp_impl = textwrap.dedent("""\
            #include "counter.hpp"
            Counter::Counter() : count(0) {}
            void Counter::increment() { count++; }
            int Counter::get_count() const { return count; }
            void Counter::reset_internal() { count = 0; }
        """)
        (tmp_path / "counter.cpp").write_text(cpp_impl)

        backend = LibclangBackend()
        unit = backend.parse(header_content, str(header_file), extra_args=["-x", "c++", "-std=c++17"])
        nim_code = write_nim(unit, header_path="counter.hpp")

        # Must have public methods, must NOT have private members
        assert "increment*" in nim_code
        assert "get_count*" in nim_code
        assert "reset_internal" not in nim_code
        assert "count*:" not in nim_code

        # Write a Nim test harness that calls the public API
        nim_harness = (
            '{.compile: "counter.cpp".}\n'
            f"{nim_code}\n"
            "var c = constructCounter()\n"
            "c.increment()\n"
            "doAssert c.get_count() == 1\n"
        )
        nim_file = tmp_path / "test_counter.nim"
        nim_file.write_text(nim_harness)

        # Compile and run with nim cpp
        res = subprocess.run(
            [nim_bin, "cpp", "-r", "--hints:off", f"--outdir:{tmp_path}", str(nim_file)],
            capture_output=True,
            text=True,
            cwd=tmp_path,
        )
        assert res.returncode == 0, f"Compilation failed:\n{res.stderr}\n{res.stdout}"

        # Negative control: verify that attempting to call a private member fails C++ compilation
        bad_harness = (
            '{.compile: "counter.cpp".}\n'
            f"{nim_code}\n"
            'proc reset_internal*(this: var Counter) {.importcpp: "#.reset_internal()", header: "counter.hpp".}\n'
            "var c = constructCounter()\n"
            "c.reset_internal()\n"
        )
        bad_file = tmp_path / "bad_counter.nim"
        bad_file.write_text(bad_harness)
        bad_res = subprocess.run(
            [nim_bin, "cpp", "--hints:off", f"--outdir:{tmp_path}", str(bad_file)],
            capture_output=True,
            text=True,
            cwd=tmp_path,
        )
        assert bad_res.returncode != 0
        assert "private" in bad_res.stderr.lower() or "error" in bad_res.stderr.lower()


class TestNimLexicalCorrectness:
    """Nim identifiers and generic syntax must satisfy Nim's lexer rules."""

    def test_underscore_sanitization_avoids_consecutive_underscores(self) -> None:
        from headerkit.writers.nim import _escape_ident

        cases = {
            "__sig": "uu_sig",
            "___sig": "u3_sig",
            "_foo": "u_foo",
            "__darwin_pthread_mutex_t": "uu_darwin_pthread_mutex_t",
            "foo__bar": "foo_bar",
            "val_": "val_u",
            "val__": "val_uu",
            "_": "u1",
            "__": "u2",
        }
        for orig, expected in cases.items():
            result = _escape_ident(orig)
            assert result == expected
            assert "__" not in result, f"Consecutive underscores in {result}"
            assert not result.startswith("_"), f"Leading underscore in {result}"
            assert not result.endswith("_"), f"Trailing underscore in {result}"

    @pytest.mark.allow("subprocess")
    def test_generic_struct_export_marker_syntax_validates_with_nim_check(self, tmp_path) -> None:
        """Export marker '*' must precede generic params: 'Tag*[T]' not 'Tag[T]*'."""
        import subprocess

        nim_bin = require_program("nim", install=NIM_INSTALL)

        struct = Struct(
            name="Tag",
            template_params=["T0"],
            is_cppclass=True,
            fields=[Field(name="val", type=CType("T0"), access="public")],
        )
        h = Header(path="tag.hpp", declarations=[struct])
        code = write_nim(h, header_path="tag.hpp")

        assert "Tag*[T0]" in code
        assert "Tag[T0]*" not in code

        nim_file = tmp_path / "test_tag.nim"
        nim_file.write_text(code)
        res = subprocess.run([nim_bin, "check", "--hints:off", str(nim_file)], capture_output=True, text=True)
        assert res.returncode == 0, f"nim check failed on generic struct declaration:\n{res.stderr}\n{code}"

    def test_deleted_methods_and_constructors_skipped(self) -> None:
        """Verify that methods, constructors, and destructors marked is_deleted are skipped."""
        s = Struct(
            name="NonCopyable",
            is_cppclass=True,
            constructors=[
                Function(name="NonCopyable", return_type=CType("void"), is_deleted=True),
                Function(name="NonCopyable", return_type=CType("void"), parameters=[Parameter("x", CType("int"))]),
            ],
            methods=[
                Function(name="clone", return_type=CType("NonCopyable"), is_deleted=True),
                Function(name="valid", return_type=CType("bool")),
            ],
            destructor=Function(name="~NonCopyable", return_type=CType("void"), is_deleted=True),
        )
        h = Header(path="test.hpp", declarations=[s])
        code = write_nim(h, header_path="test.hpp")
        assert "constructNonCopyable" in code
        assert "constructNonCopyable*()" not in code
        assert "clone" not in code
        assert "valid" in code
        assert "destroy" not in code

    def test_signature_deduplication(self) -> None:
        """Verify that identical proc signatures within a struct are deduplicated."""
        s = Struct(
            name="Overloaded",
            is_cppclass=True,
            methods=[
                Function(
                    name="get",
                    return_type=CType("int"),
                    parameters=[Parameter("key", CType("int"))],
                ),
                Function(
                    name="get",
                    return_type=CType("float"),
                    parameters=[Parameter("key", CType("int"))],
                ),
            ],
        )
        h = Header(path="test.hpp", declarations=[s])
        code = write_nim(h, header_path="test.hpp")
        assert code.count("proc get*") == 1

    def test_unnameable_return_type_fallback_to_auto(self) -> None:
        """Verify that methods returning undeclared/private types fallback to auto."""
        s = Struct(
            name="Element",
            is_cppclass=True,
            methods=[
                Function(
                    name="getSecretIterator",
                    return_type=CType("PrivateIterator"),
                ),
            ],
        )
        h = Header(path="test.hpp", declarations=[s])
        code = write_nim(h, header_path="test.hpp")
        assert "proc getSecretIterator*(this: var Element): auto" in code

    def test_scoped_enum_resolution(self) -> None:
        """Verify that nested enums with keyword names resolve properly."""
        e = Enum(
            name="Type",
            cpp_name="Expr::Type",
            values=[EnumValue("constantType", 0)],
        )
        s = Struct(
            name="Expr",
            is_cppclass=True,
            methods=[
                Function(
                    name="getType",
                    return_type=CType("enum Type"),
                    is_const=True,
                ),
            ],
        )
        h = Header(path="test.hpp", declarations=[e, s])
        code = write_nim(h, header_path="test.hpp")
        assert "Expr_Type* {.size: sizeof(cint)" in code
        assert "proc getType*(this: Expr): Expr_Type" in code
