r"""IR to Nim binding writer.

This module converts the headerkit IR (Intermediate Representation) to
Nim declaration files using ``{.importc.}`` and ``{.importcpp.}`` pragmas.

Features
--------
* C and C++ Interop -- Emits ``{.importc.}`` for C and ``{.importcpp: "...".}`` for C++
* C++ Classes & Inheritance -- Maps classes/structs with bases, methods, constructors, destructors
* Function & Type Generics -- Maps templates to Nim generics: ``type Foo[T] = object``, ``proc bar[T](x: T)``
* References & Pointers -- Maps ``Reference`` to ``var T`` / ``byref`` and ``Pointer`` to ``ptr T``
* Identifier Escaping & Style -- Handles Nim keywords with accent quotes (e.g. ``\`type\```)
"""

from __future__ import annotations

import textwrap

from headerkit.ir import (
    Array,
    Constant,
    CType,
    Enum,
    Function,
    FunctionPointer,
    Header,
    Pointer,
    Reference,
    Struct,
    Typedef,
    TypeExpr,
    Variable,
)

NIM_KEYWORDS: set[str] = {
    "addr",
    "and",
    "as",
    "asm",
    "bind",
    "block",
    "break",
    "case",
    "cast",
    "concept",
    "const",
    "continue",
    "converter",
    "defer",
    "discard",
    "distinct",
    "div",
    "do",
    "elif",
    "else",
    "end",
    "enum",
    "except",
    "export",
    "finally",
    "for",
    "from",
    "func",
    "if",
    "import",
    "in",
    "include",
    "interface",
    "is",
    "isnot",
    "iterator",
    "let",
    "macro",
    "method",
    "mixin",
    "mod",
    "nil",
    "not",
    "notin",
    "object",
    "of",
    "or",
    "out",
    "proc",
    "ptr",
    "raise",
    "ref",
    "return",
    "shl",
    "shr",
    "static",
    "template",
    "try",
    "tuple",
    "type",
    "using",
    "var",
    "when",
    "while",
    "xor",
    "yield",
}

C_TO_NIM_PRIMITIVES: dict[str, str] = {
    "void": "void",
    "char": "cchar",
    "signed char": "cschar",
    "unsigned char": "cuchar",
    "short": "cshort",
    "short int": "cshort",
    "signed short": "cshort",
    "signed short int": "cshort",
    "unsigned short": "cushort",
    "unsigned short int": "cushort",
    "int": "cint",
    "signed int": "cint",
    "signed": "cint",
    "unsigned": "cuint",
    "unsigned int": "cuint",
    "long": "clong",
    "long int": "clong",
    "signed long": "clong",
    "signed long int": "clong",
    "unsigned long": "culong",
    "unsigned long int": "culong",
    "long long": "clonglong",
    "long long int": "clonglong",
    "signed long long": "clonglong",
    "signed long long int": "clonglong",
    "unsigned long long": "culonglong",
    "unsigned long long int": "culonglong",
    "float": "cfloat",
    "double": "cdouble",
    "long double": "clongdouble",
    "bool": "bool",
    "_Bool": "bool",
    "size_t": "csize_t",
    "ssize_t": "int",
    "intptr_t": "int",
    "uintptr_t": "uint",
    "ptrdiff_t": "int",
    "int8_t": "int8",
    "int16_t": "int16",
    "int32_t": "int32",
    "int64_t": "int64",
    "uint8_t": "uint8",
    "uint16_t": "uint16",
    "uint32_t": "uint32",
    "uint64_t": "uint64",
    "cstring": "cstring",
    "void*": "pointer",
}


def _escape_ident(name: str) -> str:
    """Escape Nim keywords and invalid identifier characters."""
    if not name:
        return "anon"
    if name in NIM_KEYWORDS:
        return f"`{name}`"
    return name


class NimWriter:
    """Writer that converts headerkit IR into Nim binding modules."""

    default_output_pattern: str = "{dir}/{stem}.nim"

    def __init__(self, *, header_path: str | None = None) -> None:
        self.header_path = header_path

    @property
    def name(self) -> str:
        return "nim"

    @property
    def format_description(self) -> str:
        return "Nim bindings with C and C++ interop"

    def hash_comment_format(self) -> str:
        """Return format string for wrapping TOML cache metadata in Nim comments."""
        return "# {line}"

    def write(self, header: Header) -> str:
        """Convert parsed header IR to Nim source code."""
        lines: list[str] = []

        header_file = self.header_path or header.path or "header.h"

        lines.append(
            textwrap.dedent(f"""\
            # Generated by headerkit
            {{.compile: "{header_file}".}}
        """)
        )

        # Collect type definitions vs functions/constants
        types_section: list[str] = []
        procs_section: list[str] = []
        consts_section: list[str] = []

        for decl in header.declarations:
            if isinstance(decl, Struct):
                types_section.extend(self._write_struct(decl, header_file))
            elif isinstance(decl, Enum):
                types_section.extend(self._write_enum(decl, header_file))
            elif isinstance(decl, Typedef):
                types_section.extend(self._write_typedef(decl, header_file))
            elif isinstance(decl, Function):
                procs_section.extend(self._write_function(decl, header_file))
            elif isinstance(decl, Constant):
                consts_section.extend(self._write_constant(decl))
            elif isinstance(decl, Variable):
                procs_section.extend(self._write_variable(decl, header_file))

        if types_section:
            lines.append("type")
            for t_line in types_section:
                lines.append(f"  {t_line}" if t_line else "")
            lines.append("")

        if consts_section:
            lines.append("const")
            for c_line in consts_section:
                lines.append(f"  {c_line}" if c_line else "")
            lines.append("")

        if procs_section:
            lines.extend(procs_section)
            lines.append("")

        output = "\n".join(lines).rstrip() + "\n"
        return output

    def _format_type(self, t: TypeExpr, *, in_param: bool = False) -> str:
        """Convert IR TypeExpr to a Nim type representation."""
        if isinstance(t, CType):
            name = t.name
            if name.startswith("struct "):
                name = name[7:]
            elif name.startswith("union "):
                name = name[6:]
            elif name.startswith("enum "):
                name = name[5:]

            if name in C_TO_NIM_PRIMITIVES:
                return C_TO_NIM_PRIMITIVES[name]
            return _escape_ident(name)

        elif isinstance(t, Pointer):
            if isinstance(t.pointee, CType) and t.pointee.name == "void":
                return "pointer"
            if isinstance(t.pointee, CType) and t.pointee.name == "char" and "const" in t.pointee.qualifiers:
                return "cstring"
            target_type = self._format_type(t.pointee)
            return f"ptr {target_type}"

        elif isinstance(t, Reference):
            target_type = self._format_type(t.target)
            if in_param:
                return f"var {target_type}"
            return f"ptr {target_type}"

        elif isinstance(t, Array):
            elem = self._format_type(t.element_type)
            if t.size is not None:
                return f"array[{t.size}, {elem}]"
            return f"UncheckedArray[{elem}]"

        elif isinstance(t, FunctionPointer):
            ret = self._format_type(t.return_type)
            params = [self._format_type(p.type, in_param=True) for p in t.parameters]
            params_str = f"({', '.join(params)})" if params else "()"
            ret_str = f": {ret}" if ret != "void" else ""
            return f"proc{params_str}{ret_str} {{.cdecl.}}"

        return "pointer"

    def _write_struct(self, s: Struct, header_file: str) -> list[str]:
        """Render a Struct or class as a Nim type declaration."""
        name = s.name or "AnonObject"
        t_name = _escape_ident(name)

        # Generics
        if s.template_params:
            t_name = f"{t_name}[{', '.join(s.template_params)}]"

        pragma_parts: list[str] = []
        is_cpp = s.is_cppclass or bool(s.methods or s.bases or s.constructors or s.destructor)

        if is_cpp:
            cpp_pattern = s.cpp_name or (f"{s.namespace}::{s.name}" if s.namespace else s.name)
            pragma_parts.append(f'importcpp: "{cpp_pattern}", header: "{header_file}"')
            pragma_parts.append("bycopy")
        else:
            pragma_parts.append(f'importc: "{name}", header: "{header_file}"')
            if s.is_union:
                pragma_parts.append("union")
            else:
                pragma_parts.append("bycopy")

        if s.is_packed:
            pragma_parts.append("packed")

        pragma_str = f" {{.{', '.join(pragma_parts)}.}}" if pragma_parts else ""

        # Inheritance
        base_str = ""
        if s.bases:
            base_str = f" of {self._format_type(CType(s.bases[0].name))}"

        lines = [f"{t_name}* = object{base_str}{pragma_str}"]

        if not s.fields:
            lines[0] += ""
        else:
            for f in s.fields:
                f_name = _escape_ident(f.name)
                f_type = self._format_type(f.type)
                lines.append(f"  {f_name}*: {f_type}")

        # Methods / Constructors attached to struct
        for m in s.methods:
            lines.extend(self._write_method(s, m, header_file))

        for ctor in s.constructors:
            lines.extend(self._write_constructor(s, ctor, header_file))

        return lines

    def _write_method(self, s: Struct, m: Function, header_file: str) -> list[str]:
        """Render a C++ member method in Nim."""
        m_name = _escape_ident(m.name)
        params: list[str] = []

        # 'this' parameter
        struct_type = self._format_type(CType(s.name or "Self"))
        if not m.is_static:
            if m.is_const:
                params.append(f"this: {struct_type}")
            else:
                params.append(f"this: var {struct_type}")

        for p in m.parameters:
            p_name = _escape_ident(p.name or "arg")
            p_type = self._format_type(p.type, in_param=True)
            default_str = f" = {p.default_value}" if p.default_value else ""
            params.append(f"{p_name}: {p_type}{default_str}")

        ret_type = self._format_type(m.return_type)
        ret_str = f": {ret_type}" if ret_type != "void" else ""

        # Pragmas
        pragmas: list[str] = []
        if m.is_static:
            cpp_pattern = f"{s.name}::{m.name}(@)"
        else:
            cpp_pattern = f"#.{(m.name)}(@)"
        pragmas.append(f'importcpp: "{cpp_pattern}", header: "{header_file}"')

        # Generic parameters
        t_params = f"[{', '.join(m.template_params)}]" if m.template_params else ""

        decl = f"proc {m_name}*{t_params}({', '.join(params)}){ret_str} {{.{', '.join(pragmas)}.}}"
        return ["", decl]

    def _write_constructor(self, s: Struct, ctor: Function, header_file: str) -> list[str]:
        """Render a C++ constructor as a Nim constructProc."""
        s_name = s.name or "Object"
        proc_name = f"construct{s_name}"
        params: list[str] = []

        for p in ctor.parameters:
            p_name = _escape_ident(p.name or "arg")
            p_type = self._format_type(p.type, in_param=True)
            default_str = f" = {p.default_value}" if p.default_value else ""
            params.append(f"{p_name}: {p_type}{default_str}")

        ret_type = self._format_type(CType(s_name))
        cpp_pattern = f"{s_name}(@)"
        pragma = f'importcpp: "{cpp_pattern}", header: "{header_file}", constructor'

        decl = f"proc {proc_name}*({', '.join(params)}): {ret_type} {{.{pragma}.}}"
        return ["", decl]

    def _write_enum(self, e: Enum, header_file: str) -> list[str]:
        """Render an Enum declaration."""
        name = e.name or "AnonEnum"
        e_name = _escape_ident(name)
        lines = [f'{e_name}* {{.size: sizeof(cint), importc: "{name}", header: "{header_file}".}} = enum']
        for v in e.values:
            v_name = _escape_ident(v.name)
            if v.value is not None:
                lines.append(f"  {v_name} = {v.value}")
            else:
                lines.append(f"  {v_name}")
        return lines

    def _write_typedef(self, t: Typedef, header_file: str) -> list[str]:
        """Render a Typedef declaration."""
        t_name = _escape_ident(t.name)
        underlying = self._format_type(t.underlying_type)
        return [f"{t_name}* = {underlying}"]

    def _write_function(self, f: Function, header_file: str) -> list[str]:
        """Render a free function or function template."""
        f_name = _escape_ident(f.name)
        params: list[str] = []

        for p in f.parameters:
            p_name = _escape_ident(p.name or "arg")
            p_type = self._format_type(p.type, in_param=True)
            default_str = f" = {p.default_value}" if p.default_value else ""
            params.append(f"{p_name}: {p_type}{default_str}")

        ret_type = self._format_type(f.return_type)
        ret_str = f": {ret_type}" if ret_type != "void" else ""

        pragmas: list[str] = []
        if f.namespace:
            pragmas.append(f'importcpp: "{f.namespace}::{f.name}(@)", header: "{header_file}"')
        else:
            pragmas.append(f'importc: "{f.name}", header: "{header_file}"')

        if f.calling_convention:
            pragmas.append(f.calling_convention)
        else:
            pragmas.append("cdecl")

        t_params = f"[{', '.join(f.template_params)}]" if f.template_params else ""
        return [f"proc {f_name}*{t_params}({', '.join(params)}){ret_str} {{.{', '.join(pragmas)}.}}"]

    def _write_variable(self, v: Variable, header_file: str) -> list[str]:
        """Render an extern global variable."""
        v_name = _escape_ident(v.name)
        v_type = self._format_type(v.type)
        return [f'var {v_name}* {{.importc: "{v.name}", header: "{header_file}".}}: {v_type}']

    def _write_constant(self, c: Constant) -> list[str]:
        """Render a constant."""
        c_name = _escape_ident(c.name)
        val = c.value if c.value is not None else 0
        return [f"{c_name}* = {val}"]


def write_nim(header: Header, *, header_path: str | None = None) -> str:
    """Convenience function to generate Nim bindings from a Header IR."""
    return NimWriter(header_path=header_path).write(header)


from headerkit.writers import register_writer  # noqa: E402

register_writer("nim", NimWriter, description="Nim bindings with C and C++ interop (importc, importcpp)")
