# Generated by headerkit

type
  RtMidiWrapper* {.importc: "struct RtMidiWrapper", header: "rtmidi/rtmidi_c.h", bycopy.} = object
    `ptr`*: pointer
    data*: pointer
    ok*: bool
    msg*: cstring
  RtMidiPtr* = ptr RtMidiWrapper
  RtMidiInPtr* = ptr RtMidiWrapper
  RtMidiOutPtr* = ptr RtMidiWrapper
  RtMidiApi* {.size: sizeof(cint), importc: "enum RtMidiApi", header: "rtmidi/rtmidi_c.h".} = enum
    RTMIDI_API_UNSPECIFIED = 0
    RTMIDI_API_MACOSX_CORE = 1
    RTMIDI_API_LINUX_ALSA = 2
    RTMIDI_API_UNIX_JACK = 3
    RTMIDI_API_WINDOWS_MM = 4
    RTMIDI_API_RTMIDI_DUMMY = 5
    RTMIDI_API_WEB_MIDI_API = 6
    RTMIDI_API_WINDOWS_UWP = 7
    RTMIDI_API_ANDROID = 8
    RTMIDI_API_NUM = 9
  RtMidiErrorType* {.size: sizeof(cint), importc: "enum RtMidiErrorType", header: "rtmidi/rtmidi_c.h".} = enum
    RTMIDI_ERROR_WARNING = 0
    RTMIDI_ERROR_DEBUG_WARNING = 1
    RTMIDI_ERROR_UNSPECIFIED = 2
    RTMIDI_ERROR_NO_DEVICES_FOUND = 3
    RTMIDI_ERROR_INVALID_DEVICE = 4
    RTMIDI_ERROR_MEMORY_ERROR = 5
    RTMIDI_ERROR_INVALID_PARAMETER = 6
    RTMIDI_ERROR_INVALID_USE = 7
    RTMIDI_ERROR_DRIVER_ERROR = 8
    RTMIDI_ERROR_SYSTEM_ERROR = 9
    RTMIDI_ERROR_THREAD_ERROR = 10
  RtMidiCCallback* = proc(a0: cdouble, a1: ptr cuchar, a2: csize_t, a3: pointer) {.cdecl.}

proc rtmidi_get_version*(): cstring {.importc: "rtmidi_get_version", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_get_compiled_api*(apis: ptr RtMidiApi, apis_size: cuint): cint {.importc: "rtmidi_get_compiled_api", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_api_name*(api: RtMidiApi): cstring {.importc: "rtmidi_api_name", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_api_display_name*(api: RtMidiApi): cstring {.importc: "rtmidi_api_display_name", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_compiled_api_by_name*(name: cstring): RtMidiApi {.importc: "rtmidi_compiled_api_by_name", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_error*(`type`: RtMidiErrorType, errorString: cstring) {.importc: "rtmidi_error", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_open_port*(device: RtMidiPtr, portNumber: cuint, portName: cstring) {.importc: "rtmidi_open_port", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_open_virtual_port*(device: RtMidiPtr, portName: cstring) {.importc: "rtmidi_open_virtual_port", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_close_port*(device: RtMidiPtr) {.importc: "rtmidi_close_port", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_get_port_count*(device: RtMidiPtr): cuint {.importc: "rtmidi_get_port_count", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_get_port_name*(device: RtMidiPtr, portNumber: cuint, bufOut: ptr cchar, bufLen: ptr cint): cint {.importc: "rtmidi_get_port_name", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_in_create_default*(): RtMidiInPtr {.importc: "rtmidi_in_create_default", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_in_create*(api: RtMidiApi, clientName: cstring, queueSizeLimit: cuint): RtMidiInPtr {.importc: "rtmidi_in_create", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_in_free*(device: RtMidiInPtr) {.importc: "rtmidi_in_free", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_in_get_current_api*(device: RtMidiPtr): RtMidiApi {.importc: "rtmidi_in_get_current_api", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_in_set_callback*(device: RtMidiInPtr, callback: RtMidiCCallback, userData: pointer) {.importc: "rtmidi_in_set_callback", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_in_cancel_callback*(device: RtMidiInPtr) {.importc: "rtmidi_in_cancel_callback", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_in_ignore_types*(device: RtMidiInPtr, midiSysex: bool, midiTime: bool, midiSense: bool) {.importc: "rtmidi_in_ignore_types", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_in_get_message*(device: RtMidiInPtr, message: ptr cuchar, size: ptr csize_t): cdouble {.importc: "rtmidi_in_get_message", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_out_create_default*(): RtMidiOutPtr {.importc: "rtmidi_out_create_default", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_out_create*(api: RtMidiApi, clientName: cstring): RtMidiOutPtr {.importc: "rtmidi_out_create", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_out_free*(device: RtMidiOutPtr) {.importc: "rtmidi_out_free", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_out_get_current_api*(device: RtMidiPtr): RtMidiApi {.importc: "rtmidi_out_get_current_api", header: "rtmidi/rtmidi_c.h", cdecl.}
proc rtmidi_out_send_message*(device: RtMidiOutPtr, message: ptr cuchar, length: cint): cint {.importc: "rtmidi_out_send_message", header: "rtmidi/rtmidi_c.h", cdecl.}
