# Generated by headerkit

type
  clap_version* {.importc: "struct clap_version", header: "clap/clap.h", bycopy.} = object
    major*: uint32
    minor*: uint32
    revision*: uint32
  clap_version_t* = clap_version
  clap_plugin_entry* {.importc: "struct clap_plugin_entry", header: "clap/clap.h", bycopy.} = object
    clap_version*: clap_version_t
    init*: proc(a0: cstring): bool {.cdecl.}
    deinit*: proc() {.cdecl.}
    get_factory*: proc(a0: cstring): pointer {.cdecl.}
  clap_plugin_entry_t* = clap_plugin_entry
  clap_host* {.importc: "struct clap_host", header: "clap/clap.h", bycopy.} = object
    clap_version*: clap_version_t
    host_data*: pointer
    name*: cstring
    vendor*: cstring
    url*: cstring
    version*: cstring
    get_extension*: proc(a0: ptr clap_host, a1: cstring): pointer {.cdecl.}
    request_restart*: proc(a0: ptr clap_host) {.cdecl.}
    request_process*: proc(a0: ptr clap_host) {.cdecl.}
    request_callback*: proc(a0: ptr clap_host) {.cdecl.}
  clap_host_t* = clap_host
  clap_beattime* = int64
  clap_sectime* = int64
  clap_id* = uint32
  clap_event_header* {.importc: "struct clap_event_header", header: "clap/clap.h", bycopy.} = object
    size*: uint32
    time*: uint32
    space_id*: uint16
    `type`*: uint16
    flags*: uint32
  clap_event_header_t* = clap_event_header
  clap_event_flags* {.size: sizeof(cint), importc: "enum clap_event_flags", header: "clap/clap.h".} = enum
    CLAP_EVENT_IS_LIVE = 1
    CLAP_EVENT_DONT_RECORD = 2
  clap_event_note* {.importc: "struct clap_event_note", header: "clap/clap.h", bycopy.} = object
    header*: clap_event_header_t
    note_id*: int32
    port_index*: int16
    channel*: int16
    key*: int16
    velocity*: cdouble
  clap_event_note_t* = clap_event_note
  clap_note_expression* = int32
  clap_event_note_expression* {.importc: "struct clap_event_note_expression", header: "clap/clap.h", bycopy.} = object
    header*: clap_event_header_t
    expression_id*: clap_note_expression
    note_id*: int32
    port_index*: int16
    channel*: int16
    key*: int16
    value*: cdouble
  clap_event_note_expression_t* = clap_event_note_expression
  clap_event_param_value* {.importc: "struct clap_event_param_value", header: "clap/clap.h", bycopy.} = object
    header*: clap_event_header_t
    param_id*: clap_id
    cookie*: pointer
    note_id*: int32
    port_index*: int16
    channel*: int16
    key*: int16
    value*: cdouble
  clap_event_param_value_t* = clap_event_param_value
  clap_event_param_mod* {.importc: "struct clap_event_param_mod", header: "clap/clap.h", bycopy.} = object
    header*: clap_event_header_t
    param_id*: clap_id
    cookie*: pointer
    note_id*: int32
    port_index*: int16
    channel*: int16
    key*: int16
    amount*: cdouble
  clap_event_param_mod_t* = clap_event_param_mod
  clap_event_param_gesture* {.importc: "struct clap_event_param_gesture", header: "clap/clap.h", bycopy.} = object
    header*: clap_event_header_t
    param_id*: clap_id
  clap_event_param_gesture_t* = clap_event_param_gesture
  clap_transport_flags* {.size: sizeof(cint), importc: "enum clap_transport_flags", header: "clap/clap.h".} = enum
    CLAP_TRANSPORT_HAS_TEMPO = 1
    CLAP_TRANSPORT_HAS_BEATS_TIMELINE = 2
    CLAP_TRANSPORT_HAS_SECONDS_TIMELINE = 4
    CLAP_TRANSPORT_HAS_TIME_SIGNATURE = 8
    CLAP_TRANSPORT_IS_PLAYING = 16
    CLAP_TRANSPORT_IS_RECORDING = 32
    CLAP_TRANSPORT_IS_LOOP_ACTIVE = 64
    CLAP_TRANSPORT_IS_WITHIN_PRE_ROLL = 128
  clap_event_transport* {.importc: "struct clap_event_transport", header: "clap/clap.h", bycopy.} = object
    header*: clap_event_header_t
    flags*: uint32
    song_pos_beats*: clap_beattime
    song_pos_seconds*: clap_sectime
    tempo*: cdouble
    tempo_inc*: cdouble
    loop_start_beats*: clap_beattime
    loop_end_beats*: clap_beattime
    loop_start_seconds*: clap_sectime
    loop_end_seconds*: clap_sectime
    bar_start*: clap_beattime
    bar_number*: int32
    tsig_num*: uint16
    tsig_denom*: uint16
  clap_event_transport_t* = clap_event_transport
  clap_event_midi* {.importc: "struct clap_event_midi", header: "clap/clap.h", bycopy.} = object
    header*: clap_event_header_t
    port_index*: uint16
    data*: array[3, uint8]
  clap_event_midi_t* = clap_event_midi
  clap_event_midi_sysex* {.importc: "struct clap_event_midi_sysex", header: "clap/clap.h", bycopy.} = object
    header*: clap_event_header_t
    port_index*: uint16
    buffer*: ptr uint8
    size*: uint32
  clap_event_midi_sysex_t* = clap_event_midi_sysex
  clap_event_midi2* {.importc: "struct clap_event_midi2", header: "clap/clap.h", bycopy.} = object
    header*: clap_event_header_t
    port_index*: uint16
    data*: array[4, uint32]
  clap_event_midi2_t* = clap_event_midi2
  clap_input_events* {.importc: "struct clap_input_events", header: "clap/clap.h", bycopy.} = object
    ctx*: pointer
    size*: proc(a0: ptr clap_input_events): uint32 {.cdecl.}
    get*: proc(a0: ptr clap_input_events, a1: uint32): ptr clap_event_header_t {.cdecl.}
  clap_input_events_t* = clap_input_events
  clap_output_events* {.importc: "struct clap_output_events", header: "clap/clap.h", bycopy.} = object
    ctx*: pointer
    try_push*: proc(a0: ptr clap_output_events, a1: ptr clap_event_header_t): bool {.cdecl.}
  clap_output_events_t* = clap_output_events
  clap_audio_buffer* {.importc: "struct clap_audio_buffer", header: "clap/clap.h", bycopy.} = object
    data32*: ptr ptr cfloat
    data64*: ptr ptr cdouble
    channel_count*: uint32
    latency*: uint32
    constant_mask*: uint64
  clap_audio_buffer_t* = clap_audio_buffer
  clap_process_status* = int32
  clap_process* {.importc: "struct clap_process", header: "clap/clap.h", bycopy.} = object
    steady_time*: int64
    frames_count*: uint32
    transport*: ptr clap_event_transport_t
    audio_inputs*: ptr clap_audio_buffer_t
    audio_outputs*: ptr clap_audio_buffer_t
    audio_inputs_count*: uint32
    audio_outputs_count*: uint32
    in_events*: ptr clap_input_events_t
    out_events*: ptr clap_output_events_t
  clap_process_t* = clap_process
  clap_plugin_descriptor* {.importc: "struct clap_plugin_descriptor", header: "clap/clap.h", bycopy.} = object
    clap_version*: clap_version_t
    id*: cstring
    name*: cstring
    vendor*: cstring
    url*: cstring
    manual_url*: cstring
    support_url*: cstring
    version*: cstring
    description*: cstring
    features*: ptr cstring
  clap_plugin_descriptor_t* = clap_plugin_descriptor
  clap_plugin* {.importc: "struct clap_plugin", header: "clap/clap.h", bycopy.} = object
    desc*: ptr clap_plugin_descriptor_t
    plugin_data*: pointer
    init*: proc(a0: ptr clap_plugin): bool {.cdecl.}
    destroy*: proc(a0: ptr clap_plugin) {.cdecl.}
    activate*: proc(a0: ptr clap_plugin, a1: cdouble, a2: uint32, a3: uint32): bool {.cdecl.}
    deactivate*: proc(a0: ptr clap_plugin) {.cdecl.}
    start_processing*: proc(a0: ptr clap_plugin): bool {.cdecl.}
    stop_processing*: proc(a0: ptr clap_plugin) {.cdecl.}
    reset*: proc(a0: ptr clap_plugin) {.cdecl.}
    process*: proc(a0: ptr clap_plugin, a1: ptr clap_process_t): clap_process_status {.cdecl.}
    get_extension*: proc(a0: ptr clap_plugin, a1: cstring): pointer {.cdecl.}
    on_main_thread*: proc(a0: ptr clap_plugin) {.cdecl.}
  clap_plugin_t* = clap_plugin
  clap_plugin_factory* {.importc: "struct clap_plugin_factory", header: "clap/clap.h", bycopy.} = object
    get_plugin_count*: proc(a0: ptr clap_plugin_factory): uint32 {.cdecl.}
    get_plugin_descriptor*: proc(a0: ptr clap_plugin_factory, a1: uint32): ptr clap_plugin_descriptor_t {.cdecl.}
    create_plugin*: proc(a0: ptr clap_plugin_factory, a1: ptr clap_host_t, a2: cstring): ptr clap_plugin_t {.cdecl.}
  clap_plugin_factory_t* = clap_plugin_factory
  clap_timestamp* = uint64
  clap_universal_plugin_id* {.importc: "struct clap_universal_plugin_id", header: "clap/clap.h", bycopy.} = object
    abi*: cstring
    id*: cstring
  clap_universal_plugin_id_t* = clap_universal_plugin_id
  clap_preset_discovery_location_kind* {.size: sizeof(cint), importc: "enum clap_preset_discovery_location_kind", header: "clap/clap.h".} = enum
    CLAP_PRESET_DISCOVERY_LOCATION_FILE = 0
    CLAP_PRESET_DISCOVERY_LOCATION_PLUGIN = 1
  clap_preset_discovery_flags* {.size: sizeof(cint), importc: "enum clap_preset_discovery_flags", header: "clap/clap.h".} = enum
    CLAP_PRESET_DISCOVERY_IS_FACTORY_CONTENT = 1
    CLAP_PRESET_DISCOVERY_IS_USER_CONTENT = 2
    CLAP_PRESET_DISCOVERY_IS_DEMO_CONTENT = 4
    CLAP_PRESET_DISCOVERY_IS_FAVORITE = 8
  clap_preset_discovery_metadata_receiver* {.importc: "struct clap_preset_discovery_metadata_receiver", header: "clap/clap.h", bycopy.} = object
    receiver_data*: pointer
    on_error*: proc(a0: ptr clap_preset_discovery_metadata_receiver, a1: int32, a2: cstring) {.cdecl.}
    begin_preset*: proc(a0: ptr clap_preset_discovery_metadata_receiver, a1: cstring, a2: cstring): bool {.cdecl.}
    add_plugin_id*: proc(a0: ptr clap_preset_discovery_metadata_receiver, a1: ptr clap_universal_plugin_id_t) {.cdecl.}
    set_soundpack_id*: proc(a0: ptr clap_preset_discovery_metadata_receiver, a1: cstring) {.cdecl.}
    set_flags*: proc(a0: ptr clap_preset_discovery_metadata_receiver, a1: uint32) {.cdecl.}
    add_creator*: proc(a0: ptr clap_preset_discovery_metadata_receiver, a1: cstring) {.cdecl.}
    set_description*: proc(a0: ptr clap_preset_discovery_metadata_receiver, a1: cstring) {.cdecl.}
    set_timestamps*: proc(a0: ptr clap_preset_discovery_metadata_receiver, a1: clap_timestamp, a2: clap_timestamp) {.cdecl.}
    add_feature*: proc(a0: ptr clap_preset_discovery_metadata_receiver, a1: cstring) {.cdecl.}
    add_extra_info*: proc(a0: ptr clap_preset_discovery_metadata_receiver, a1: cstring, a2: cstring) {.cdecl.}
  clap_preset_discovery_metadata_receiver_t* = clap_preset_discovery_metadata_receiver
  clap_preset_discovery_filetype* {.importc: "struct clap_preset_discovery_filetype", header: "clap/clap.h", bycopy.} = object
    name*: cstring
    description*: cstring
    file_extension*: cstring
  clap_preset_discovery_filetype_t* = clap_preset_discovery_filetype
  clap_preset_discovery_location* {.importc: "struct clap_preset_discovery_location", header: "clap/clap.h", bycopy.} = object
    flags*: uint32
    name*: cstring
    kind*: uint32
    location*: cstring
  clap_preset_discovery_location_t* = clap_preset_discovery_location
  clap_preset_discovery_soundpack* {.importc: "struct clap_preset_discovery_soundpack", header: "clap/clap.h", bycopy.} = object
    flags*: uint32
    id*: cstring
    name*: cstring
    description*: cstring
    homepage_url*: cstring
    vendor*: cstring
    image_path*: cstring
    release_timestamp*: clap_timestamp
  clap_preset_discovery_soundpack_t* = clap_preset_discovery_soundpack
  clap_preset_discovery_provider_descriptor* {.importc: "struct clap_preset_discovery_provider_descriptor", header: "clap/clap.h", bycopy.} = object
    clap_version*: clap_version_t
    id*: cstring
    name*: cstring
    vendor*: cstring
  clap_preset_discovery_provider_descriptor_t* = clap_preset_discovery_provider_descriptor
  clap_preset_discovery_provider* {.importc: "struct clap_preset_discovery_provider", header: "clap/clap.h", bycopy.} = object
    desc*: ptr clap_preset_discovery_provider_descriptor_t
    provider_data*: pointer
    init*: proc(a0: ptr clap_preset_discovery_provider): bool {.cdecl.}
    destroy*: proc(a0: ptr clap_preset_discovery_provider) {.cdecl.}
    get_metadata*: proc(a0: ptr clap_preset_discovery_provider, a1: uint32, a2: cstring, a3: ptr clap_preset_discovery_metadata_receiver_t): bool {.cdecl.}
    get_extension*: proc(a0: ptr clap_preset_discovery_provider, a1: cstring): pointer {.cdecl.}
  clap_preset_discovery_provider_t* = clap_preset_discovery_provider
  clap_preset_discovery_indexer* {.importc: "struct clap_preset_discovery_indexer", header: "clap/clap.h", bycopy.} = object
    clap_version*: clap_version_t
    name*: cstring
    vendor*: cstring
    url*: cstring
    version*: cstring
    indexer_data*: pointer
    declare_filetype*: proc(a0: ptr clap_preset_discovery_indexer, a1: ptr clap_preset_discovery_filetype_t): bool {.cdecl.}
    declare_location*: proc(a0: ptr clap_preset_discovery_indexer, a1: ptr clap_preset_discovery_location_t): bool {.cdecl.}
    declare_soundpack*: proc(a0: ptr clap_preset_discovery_indexer, a1: ptr clap_preset_discovery_soundpack_t): bool {.cdecl.}
    get_extension*: proc(a0: ptr clap_preset_discovery_indexer, a1: cstring): pointer {.cdecl.}
  clap_preset_discovery_indexer_t* = clap_preset_discovery_indexer
  clap_preset_discovery_factory* {.importc: "struct clap_preset_discovery_factory", header: "clap/clap.h", bycopy.} = object
    count*: proc(a0: ptr clap_preset_discovery_factory): uint32 {.cdecl.}
    get_descriptor*: proc(a0: ptr clap_preset_discovery_factory, a1: uint32): ptr clap_preset_discovery_provider_descriptor_t {.cdecl.}
    create*: proc(a0: ptr clap_preset_discovery_factory, a1: ptr clap_preset_discovery_indexer_t, a2: cstring): ptr clap_preset_discovery_provider_t {.cdecl.}
  clap_preset_discovery_factory_t* = clap_preset_discovery_factory
  clap_ambisonic_ordering* {.size: sizeof(cint), importc: "enum clap_ambisonic_ordering", header: "clap/clap.h".} = enum
    CLAP_AMBISONIC_ORDERING_FUMA = 0
    CLAP_AMBISONIC_ORDERING_ACN = 1
  clap_ambisonic_normalization* {.size: sizeof(cint), importc: "enum clap_ambisonic_normalization", header: "clap/clap.h".} = enum
    CLAP_AMBISONIC_NORMALIZATION_MAXN = 0
    CLAP_AMBISONIC_NORMALIZATION_SN3D = 1
    CLAP_AMBISONIC_NORMALIZATION_N3D = 2
    CLAP_AMBISONIC_NORMALIZATION_SN2D = 3
    CLAP_AMBISONIC_NORMALIZATION_N2D = 4
  clap_ambisonic_config* {.importc: "struct clap_ambisonic_config", header: "clap/clap.h", bycopy.} = object
    ordering*: uint32
    normalization*: uint32
  clap_ambisonic_config_t* = clap_ambisonic_config
  clap_plugin_ambisonic* {.importc: "struct clap_plugin_ambisonic", header: "clap/clap.h", bycopy.} = object
    is_config_supported*: proc(a0: ptr clap_plugin_t, a1: ptr clap_ambisonic_config_t): bool {.cdecl.}
    get_config*: proc(a0: ptr clap_plugin_t, a1: bool, a2: uint32, a3: ptr clap_ambisonic_config_t): bool {.cdecl.}
  clap_plugin_ambisonic_t* = clap_plugin_ambisonic
  clap_host_ambisonic* {.importc: "struct clap_host_ambisonic", header: "clap/clap.h", bycopy.} = object
    changed*: proc(a0: ptr clap_host_t) {.cdecl.}
  clap_host_ambisonic_t* = clap_host_ambisonic
  clap_plugin_audio_ports_activation* {.importc: "struct clap_plugin_audio_ports_activation", header: "clap/clap.h", bycopy.} = object
    can_activate_while_processing*: proc(a0: ptr clap_plugin_t): bool {.cdecl.}
    set_active*: proc(a0: ptr clap_plugin_t, a1: bool, a2: uint32, a3: bool, a4: uint32): bool {.cdecl.}
  clap_plugin_audio_ports_activation_t* = clap_plugin_audio_ports_activation
  clap_audio_port_info* {.importc: "struct clap_audio_port_info", header: "clap/clap.h", bycopy.} = object
    id*: clap_id
    name*: array[256, cchar]
    flags*: uint32
    channel_count*: uint32
    port_type*: cstring
    in_place_pair*: clap_id
  clap_audio_port_info_t* = clap_audio_port_info
  clap_plugin_audio_ports* {.importc: "struct clap_plugin_audio_ports", header: "clap/clap.h", bycopy.} = object
    count*: proc(a0: ptr clap_plugin_t, a1: bool): uint32 {.cdecl.}
    get*: proc(a0: ptr clap_plugin_t, a1: uint32, a2: bool, a3: ptr clap_audio_port_info_t): bool {.cdecl.}
  clap_plugin_audio_ports_t* = clap_plugin_audio_ports
  clap_host_audio_ports* {.importc: "struct clap_host_audio_ports", header: "clap/clap.h", bycopy.} = object
    is_rescan_flag_supported*: proc(a0: ptr clap_host_t, a1: uint32): bool {.cdecl.}
    rescan*: proc(a0: ptr clap_host_t, a1: uint32) {.cdecl.}
  clap_host_audio_ports_t* = clap_host_audio_ports
  clap_audio_ports_config* {.importc: "struct clap_audio_ports_config", header: "clap/clap.h", bycopy.} = object
    id*: clap_id
    name*: array[256, cchar]
    input_port_count*: uint32
    output_port_count*: uint32
    has_main_input*: bool
    main_input_channel_count*: uint32
    main_input_port_type*: cstring
    has_main_output*: bool
    main_output_channel_count*: uint32
    main_output_port_type*: cstring
  clap_audio_ports_config_t* = clap_audio_ports_config
  clap_plugin_audio_ports_config* {.importc: "struct clap_plugin_audio_ports_config", header: "clap/clap.h", bycopy.} = object
    count*: proc(a0: ptr clap_plugin_t): uint32 {.cdecl.}
    get*: proc(a0: ptr clap_plugin_t, a1: uint32, a2: ptr clap_audio_ports_config_t): bool {.cdecl.}
    select*: proc(a0: ptr clap_plugin_t, a1: clap_id): bool {.cdecl.}
  clap_plugin_audio_ports_config_t* = clap_plugin_audio_ports_config
  clap_plugin_audio_ports_config_info* {.importc: "struct clap_plugin_audio_ports_config_info", header: "clap/clap.h", bycopy.} = object
    current_config*: proc(a0: ptr clap_plugin_t): clap_id {.cdecl.}
    get*: proc(a0: ptr clap_plugin_t, a1: clap_id, a2: uint32, a3: bool, a4: ptr clap_audio_port_info_t): bool {.cdecl.}
  clap_plugin_audio_ports_config_info_t* = clap_plugin_audio_ports_config_info
  clap_host_audio_ports_config* {.importc: "struct clap_host_audio_ports_config", header: "clap/clap.h", bycopy.} = object
    rescan*: proc(a0: ptr clap_host_t) {.cdecl.}
  clap_host_audio_ports_config_t* = clap_host_audio_ports_config
  clap_audio_port_configuration_request* {.importc: "struct clap_audio_port_configuration_request", header: "clap/clap.h", bycopy.} = object
    is_input*: bool
    port_index*: uint32
    channel_count*: uint32
    port_type*: cstring
    port_details*: pointer
  clap_audio_port_configuration_request_t* = clap_audio_port_configuration_request
  clap_plugin_configurable_audio_ports* {.importc: "struct clap_plugin_configurable_audio_ports", header: "clap/clap.h", bycopy.} = object
    can_apply_configuration*: proc(a0: ptr clap_plugin_t, a1: ptr clap_audio_port_configuration_request, a2: uint32): bool {.cdecl.}
    apply_configuration*: proc(a0: ptr clap_plugin_t, a1: ptr clap_audio_port_configuration_request, a2: uint32): bool {.cdecl.}
  clap_plugin_configurable_audio_ports_t* = clap_plugin_configurable_audio_ports
  clap_context_menu_target* {.importc: "struct clap_context_menu_target", header: "clap/clap.h", bycopy.} = object
    kind*: uint32
    id*: clap_id
  clap_context_menu_target_t* = clap_context_menu_target
  clap_context_menu_item_kind_t* = uint32
  clap_context_menu_entry* {.importc: "struct clap_context_menu_entry", header: "clap/clap.h", bycopy.} = object
    label*: cstring
    is_enabled*: bool
    action_id*: clap_id
  clap_context_menu_entry_t* = clap_context_menu_entry
  clap_context_menu_check_entry* {.importc: "struct clap_context_menu_check_entry", header: "clap/clap.h", bycopy.} = object
    label*: cstring
    is_enabled*: bool
    is_checked*: bool
    action_id*: clap_id
  clap_context_menu_check_entry_t* = clap_context_menu_check_entry
  clap_context_menu_item_title* {.importc: "struct clap_context_menu_item_title", header: "clap/clap.h", bycopy.} = object
    title*: cstring
    is_enabled*: bool
  clap_context_menu_item_title_t* = clap_context_menu_item_title
  clap_context_menu_submenu* {.importc: "struct clap_context_menu_submenu", header: "clap/clap.h", bycopy.} = object
    label*: cstring
    is_enabled*: bool
  clap_context_menu_submenu_t* = clap_context_menu_submenu
  clap_context_menu_builder* {.importc: "struct clap_context_menu_builder", header: "clap/clap.h", bycopy.} = object
    ctx*: pointer
    add_item*: proc(a0: ptr clap_context_menu_builder, a1: clap_context_menu_item_kind_t, a2: pointer): bool {.cdecl.}
    supports*: proc(a0: ptr clap_context_menu_builder, a1: clap_context_menu_item_kind_t): bool {.cdecl.}
  clap_context_menu_builder_t* = clap_context_menu_builder
  clap_plugin_context_menu* {.importc: "struct clap_plugin_context_menu", header: "clap/clap.h", bycopy.} = object
    populate*: proc(a0: ptr clap_plugin_t, a1: ptr clap_context_menu_target_t, a2: ptr clap_context_menu_builder_t): bool {.cdecl.}
    perform*: proc(a0: ptr clap_plugin_t, a1: ptr clap_context_menu_target_t, a2: clap_id): bool {.cdecl.}
  clap_plugin_context_menu_t* = clap_plugin_context_menu
  clap_host_context_menu* {.importc: "struct clap_host_context_menu", header: "clap/clap.h", bycopy.} = object
    populate*: proc(a0: ptr clap_host_t, a1: ptr clap_context_menu_target_t, a2: ptr clap_context_menu_builder_t): bool {.cdecl.}
    perform*: proc(a0: ptr clap_host_t, a1: ptr clap_context_menu_target_t, a2: clap_id): bool {.cdecl.}
    can_popup*: proc(a0: ptr clap_host_t): bool {.cdecl.}
    popup*: proc(a0: ptr clap_host_t, a1: ptr clap_context_menu_target_t, a2: int32, a3: int32, a4: int32): bool {.cdecl.}
  clap_host_context_menu_t* = clap_host_context_menu
  clap_host_event_registry* {.importc: "struct clap_host_event_registry", header: "clap/clap.h", bycopy.} = object
    query*: proc(a0: ptr clap_host_t, a1: cstring, a2: ptr uint16): bool {.cdecl.}
  clap_host_event_registry_t* = clap_host_event_registry
  clap_hwnd* = pointer
  clap_nsview* = pointer
  clap_uiview* = pointer
  clap_xwnd* = culong
  clap_window* {.importc: "struct clap_window", header: "clap/clap.h", bycopy.} = object
    api*: cstring
    anon*: pointer
  clap_window_t* = clap_window
  clap_gui_resize_hints* {.importc: "struct clap_gui_resize_hints", header: "clap/clap.h", bycopy.} = object
    can_resize_horizontally*: bool
    can_resize_vertically*: bool
    preserve_aspect_ratio*: bool
    aspect_ratio_width*: uint32
    aspect_ratio_height*: uint32
  clap_gui_resize_hints_t* = clap_gui_resize_hints
  clap_plugin_gui* {.importc: "struct clap_plugin_gui", header: "clap/clap.h", bycopy.} = object
    is_api_supported*: proc(a0: ptr clap_plugin_t, a1: cstring, a2: bool): bool {.cdecl.}
    get_preferred_api*: proc(a0: ptr clap_plugin_t, a1: ptr cstring, a2: ptr bool): bool {.cdecl.}
    create*: proc(a0: ptr clap_plugin_t, a1: cstring, a2: bool): bool {.cdecl.}
    destroy*: proc(a0: ptr clap_plugin_t) {.cdecl.}
    set_scale*: proc(a0: ptr clap_plugin_t, a1: cdouble): bool {.cdecl.}
    get_size*: proc(a0: ptr clap_plugin_t, a1: ptr uint32, a2: ptr uint32): bool {.cdecl.}
    can_resize*: proc(a0: ptr clap_plugin_t): bool {.cdecl.}
    get_resize_hints*: proc(a0: ptr clap_plugin_t, a1: ptr clap_gui_resize_hints_t): bool {.cdecl.}
    adjust_size*: proc(a0: ptr clap_plugin_t, a1: ptr uint32, a2: ptr uint32): bool {.cdecl.}
    set_size*: proc(a0: ptr clap_plugin_t, a1: uint32, a2: uint32): bool {.cdecl.}
    set_parent*: proc(a0: ptr clap_plugin_t, a1: ptr clap_window_t): bool {.cdecl.}
    set_transient*: proc(a0: ptr clap_plugin_t, a1: ptr clap_window_t): bool {.cdecl.}
    suggest_title*: proc(a0: ptr clap_plugin_t, a1: cstring) {.cdecl.}
    show*: proc(a0: ptr clap_plugin_t): bool {.cdecl.}
    hide*: proc(a0: ptr clap_plugin_t): bool {.cdecl.}
  clap_plugin_gui_t* = clap_plugin_gui
  clap_host_gui* {.importc: "struct clap_host_gui", header: "clap/clap.h", bycopy.} = object
    resize_hints_changed*: proc(a0: ptr clap_host_t) {.cdecl.}
    request_resize*: proc(a0: ptr clap_host_t, a1: uint32, a2: uint32): bool {.cdecl.}
    request_show*: proc(a0: ptr clap_host_t): bool {.cdecl.}
    request_hide*: proc(a0: ptr clap_host_t): bool {.cdecl.}
    closed*: proc(a0: ptr clap_host_t, a1: bool) {.cdecl.}
  clap_host_gui_t* = clap_host_gui
  clap_plugin_latency* {.importc: "struct clap_plugin_latency", header: "clap/clap.h", bycopy.} = object
    get*: proc(a0: ptr clap_plugin_t): uint32 {.cdecl.}
  clap_plugin_latency_t* = clap_plugin_latency
  clap_host_latency* {.importc: "struct clap_host_latency", header: "clap/clap.h", bycopy.} = object
    changed*: proc(a0: ptr clap_host_t) {.cdecl.}
  clap_host_latency_t* = clap_host_latency
  clap_log_severity* = int32
  clap_host_log* {.importc: "struct clap_host_log", header: "clap/clap.h", bycopy.} = object
    log*: proc(a0: ptr clap_host_t, a1: clap_log_severity, a2: cstring) {.cdecl.}
  clap_host_log_t* = clap_host_log
  clap_note_name* {.importc: "struct clap_note_name", header: "clap/clap.h", bycopy.} = object
    name*: array[256, cchar]
    port*: int16
    key*: int16
    channel*: int16
  clap_note_name_t* = clap_note_name
  clap_plugin_note_name* {.importc: "struct clap_plugin_note_name", header: "clap/clap.h", bycopy.} = object
    count*: proc(a0: ptr clap_plugin_t): uint32 {.cdecl.}
    get*: proc(a0: ptr clap_plugin_t, a1: uint32, a2: ptr clap_note_name_t): bool {.cdecl.}
  clap_plugin_note_name_t* = clap_plugin_note_name
  clap_host_note_name* {.importc: "struct clap_host_note_name", header: "clap/clap.h", bycopy.} = object
    changed*: proc(a0: ptr clap_host_t) {.cdecl.}
  clap_host_note_name_t* = clap_host_note_name
  clap_note_dialect* {.size: sizeof(cint), importc: "enum clap_note_dialect", header: "clap/clap.h".} = enum
    CLAP_NOTE_DIALECT_CLAP = 1
    CLAP_NOTE_DIALECT_MIDI = 2
    CLAP_NOTE_DIALECT_MIDI_MPE = 4
    CLAP_NOTE_DIALECT_MIDI2 = 8
  clap_note_port_info* {.importc: "struct clap_note_port_info", header: "clap/clap.h", bycopy.} = object
    id*: clap_id
    supported_dialects*: uint32
    preferred_dialect*: uint32
    name*: array[256, cchar]
  clap_note_port_info_t* = clap_note_port_info
  clap_plugin_note_ports* {.importc: "struct clap_plugin_note_ports", header: "clap/clap.h", bycopy.} = object
    count*: proc(a0: ptr clap_plugin_t, a1: bool): uint32 {.cdecl.}
    get*: proc(a0: ptr clap_plugin_t, a1: uint32, a2: bool, a3: ptr clap_note_port_info_t): bool {.cdecl.}
  clap_plugin_note_ports_t* = clap_plugin_note_ports
  clap_host_note_ports* {.importc: "struct clap_host_note_ports", header: "clap/clap.h", bycopy.} = object
    supported_dialects*: proc(a0: ptr clap_host_t): uint32 {.cdecl.}
    rescan*: proc(a0: ptr clap_host_t, a1: uint32) {.cdecl.}
  clap_host_note_ports_t* = clap_host_note_ports
  clap_param_info_flags* = uint32
  clap_param_info* {.importc: "struct clap_param_info", header: "clap/clap.h", bycopy.} = object
    id*: clap_id
    flags*: clap_param_info_flags
    cookie*: pointer
    name*: array[256, cchar]
    module*: array[1024, cchar]
    min_value*: cdouble
    max_value*: cdouble
    default_value*: cdouble
  clap_param_info_t* = clap_param_info
  clap_plugin_params* {.importc: "struct clap_plugin_params", header: "clap/clap.h", bycopy.} = object
    count*: proc(a0: ptr clap_plugin_t): uint32 {.cdecl.}
    get_info*: proc(a0: ptr clap_plugin_t, a1: uint32, a2: ptr clap_param_info_t): bool {.cdecl.}
    get_value*: proc(a0: ptr clap_plugin_t, a1: clap_id, a2: ptr cdouble): bool {.cdecl.}
    value_to_text*: proc(a0: ptr clap_plugin_t, a1: clap_id, a2: cdouble, a3: ptr cchar, a4: uint32): bool {.cdecl.}
    text_to_value*: proc(a0: ptr clap_plugin_t, a1: clap_id, a2: cstring, a3: ptr cdouble): bool {.cdecl.}
    flush*: proc(a0: ptr clap_plugin_t, a1: ptr clap_input_events_t, a2: ptr clap_output_events_t) {.cdecl.}
  clap_plugin_params_t* = clap_plugin_params
  clap_param_rescan_flags* = uint32
  clap_param_clear_flags* = uint32
  clap_host_params* {.importc: "struct clap_host_params", header: "clap/clap.h", bycopy.} = object
    rescan*: proc(a0: ptr clap_host_t, a1: clap_param_rescan_flags) {.cdecl.}
    clear*: proc(a0: ptr clap_host_t, a1: clap_id, a2: clap_param_clear_flags) {.cdecl.}
    request_flush*: proc(a0: ptr clap_host_t) {.cdecl.}
  clap_host_params_t* = clap_host_params
  clap_color* {.importc: "struct clap_color", header: "clap/clap.h", bycopy.} = object
    alpha*: uint8
    red*: uint8
    green*: uint8
    blue*: uint8
  clap_color_t* = clap_color
  clap_plugin_param_indication* {.importc: "struct clap_plugin_param_indication", header: "clap/clap.h", bycopy.} = object
    set_mapping*: proc(a0: ptr clap_plugin_t, a1: clap_id, a2: bool, a3: ptr clap_color_t, a4: cstring, a5: cstring) {.cdecl.}
    set_automation*: proc(a0: ptr clap_plugin_t, a1: clap_id, a2: uint32, a3: ptr clap_color_t) {.cdecl.}
  clap_plugin_param_indication_t* = clap_plugin_param_indication
  clap_posix_fd_flags_t* = uint32
  clap_plugin_posix_fd_support* {.importc: "struct clap_plugin_posix_fd_support", header: "clap/clap.h", bycopy.} = object
    on_fd*: proc(a0: ptr clap_plugin_t, a1: cint, a2: clap_posix_fd_flags_t) {.cdecl.}
  clap_plugin_posix_fd_support_t* = clap_plugin_posix_fd_support
  clap_host_posix_fd_support* {.importc: "struct clap_host_posix_fd_support", header: "clap/clap.h", bycopy.} = object
    register_fd*: proc(a0: ptr clap_host_t, a1: cint, a2: clap_posix_fd_flags_t): bool {.cdecl.}
    modify_fd*: proc(a0: ptr clap_host_t, a1: cint, a2: clap_posix_fd_flags_t): bool {.cdecl.}
    unregister_fd*: proc(a0: ptr clap_host_t, a1: cint): bool {.cdecl.}
  clap_host_posix_fd_support_t* = clap_host_posix_fd_support
  clap_plugin_preset_load* {.importc: "struct clap_plugin_preset_load", header: "clap/clap.h", bycopy.} = object
    from_location*: proc(a0: ptr clap_plugin_t, a1: uint32, a2: cstring, a3: cstring): bool {.cdecl.}
  clap_plugin_preset_load_t* = clap_plugin_preset_load
  clap_host_preset_load* {.importc: "struct clap_host_preset_load", header: "clap/clap.h", bycopy.} = object
    on_error*: proc(a0: ptr clap_host_t, a1: uint32, a2: cstring, a3: cstring, a4: int32, a5: cstring) {.cdecl.}
    loaded*: proc(a0: ptr clap_host_t, a1: uint32, a2: cstring, a3: cstring) {.cdecl.}
  clap_host_preset_load_t* = clap_host_preset_load
  clap_remote_controls_page* {.importc: "struct clap_remote_controls_page", header: "clap/clap.h", bycopy.} = object
    section_name*: array[256, cchar]
    page_id*: clap_id
    page_name*: array[256, cchar]
    param_ids*: array[8, clap_id]
    is_for_preset*: bool
  clap_remote_controls_page_t* = clap_remote_controls_page
  clap_plugin_remote_controls* {.importc: "struct clap_plugin_remote_controls", header: "clap/clap.h", bycopy.} = object
    count*: proc(a0: ptr clap_plugin_t): uint32 {.cdecl.}
    get*: proc(a0: ptr clap_plugin_t, a1: uint32, a2: ptr clap_remote_controls_page_t): bool {.cdecl.}
  clap_plugin_remote_controls_t* = clap_plugin_remote_controls
  clap_host_remote_controls* {.importc: "struct clap_host_remote_controls", header: "clap/clap.h", bycopy.} = object
    changed*: proc(a0: ptr clap_host_t) {.cdecl.}
    suggest_page*: proc(a0: ptr clap_host_t, a1: clap_id) {.cdecl.}
  clap_host_remote_controls_t* = clap_host_remote_controls
  clap_plugin_render_mode* = int32
  clap_plugin_render* {.importc: "struct clap_plugin_render", header: "clap/clap.h", bycopy.} = object
    has_hard_realtime_requirement*: proc(a0: ptr clap_plugin_t): bool {.cdecl.}
    set*: proc(a0: ptr clap_plugin_t, a1: clap_plugin_render_mode): bool {.cdecl.}
  clap_plugin_render_t* = clap_plugin_render
  clap_istream* {.importc: "struct clap_istream", header: "clap/clap.h", bycopy.} = object
    ctx*: pointer
    read*: proc(a0: ptr clap_istream, a1: pointer, a2: uint64): int64 {.cdecl.}
  clap_istream_t* = clap_istream
  clap_ostream* {.importc: "struct clap_ostream", header: "clap/clap.h", bycopy.} = object
    ctx*: pointer
    write*: proc(a0: ptr clap_ostream, a1: pointer, a2: uint64): int64 {.cdecl.}
  clap_ostream_t* = clap_ostream
  clap_plugin_state_context_type* {.size: sizeof(cint), importc: "enum clap_plugin_state_context_type", header: "clap/clap.h".} = enum
    CLAP_STATE_CONTEXT_FOR_PRESET = 1
    CLAP_STATE_CONTEXT_FOR_DUPLICATE = 2
    CLAP_STATE_CONTEXT_FOR_PROJECT = 3
  clap_plugin_state_context* {.importc: "struct clap_plugin_state_context", header: "clap/clap.h", bycopy.} = object
    save*: proc(a0: ptr clap_plugin_t, a1: ptr clap_ostream_t, a2: uint32): bool {.cdecl.}
    load*: proc(a0: ptr clap_plugin_t, a1: ptr clap_istream_t, a2: uint32): bool {.cdecl.}
  clap_plugin_state_context_t* = clap_plugin_state_context
  clap_plugin_state* {.importc: "struct clap_plugin_state", header: "clap/clap.h", bycopy.} = object
    save*: proc(a0: ptr clap_plugin_t, a1: ptr clap_ostream_t): bool {.cdecl.}
    load*: proc(a0: ptr clap_plugin_t, a1: ptr clap_istream_t): bool {.cdecl.}
  clap_plugin_state_t* = clap_plugin_state
  clap_host_state* {.importc: "struct clap_host_state", header: "clap/clap.h", bycopy.} = object
    mark_dirty*: proc(a0: ptr clap_host_t) {.cdecl.}
  clap_host_state_t* = clap_host_state
  clap_plugin_surround* {.importc: "struct clap_plugin_surround", header: "clap/clap.h", bycopy.} = object
    is_channel_mask_supported*: proc(a0: ptr clap_plugin_t, a1: uint64): bool {.cdecl.}
    get_channel_map*: proc(a0: ptr clap_plugin_t, a1: bool, a2: uint32, a3: ptr uint8, a4: uint32): uint32 {.cdecl.}
  clap_plugin_surround_t* = clap_plugin_surround
  clap_host_surround* {.importc: "struct clap_host_surround", header: "clap/clap.h", bycopy.} = object
    changed*: proc(a0: ptr clap_host_t) {.cdecl.}
  clap_host_surround_t* = clap_host_surround
  clap_plugin_tail* {.importc: "struct clap_plugin_tail", header: "clap/clap.h", bycopy.} = object
    get*: proc(a0: ptr clap_plugin_t): uint32 {.cdecl.}
  clap_plugin_tail_t* = clap_plugin_tail
  clap_host_tail* {.importc: "struct clap_host_tail", header: "clap/clap.h", bycopy.} = object
    changed*: proc(a0: ptr clap_host_t) {.cdecl.}
  clap_host_tail_t* = clap_host_tail
  clap_host_thread_check* {.importc: "struct clap_host_thread_check", header: "clap/clap.h", bycopy.} = object
    is_main_thread*: proc(a0: ptr clap_host_t): bool {.cdecl.}
    is_audio_thread*: proc(a0: ptr clap_host_t): bool {.cdecl.}
  clap_host_thread_check_t* = clap_host_thread_check
  clap_plugin_thread_pool* {.importc: "struct clap_plugin_thread_pool", header: "clap/clap.h", bycopy.} = object
    exec*: proc(a0: ptr clap_plugin_t, a1: uint32) {.cdecl.}
  clap_plugin_thread_pool_t* = clap_plugin_thread_pool
  clap_host_thread_pool* {.importc: "struct clap_host_thread_pool", header: "clap/clap.h", bycopy.} = object
    request_exec*: proc(a0: ptr clap_host_t, a1: uint32): bool {.cdecl.}
  clap_host_thread_pool_t* = clap_host_thread_pool
  clap_plugin_timer_support* {.importc: "struct clap_plugin_timer_support", header: "clap/clap.h", bycopy.} = object
    on_timer*: proc(a0: ptr clap_plugin_t, a1: clap_id) {.cdecl.}
  clap_plugin_timer_support_t* = clap_plugin_timer_support
  clap_host_timer_support* {.importc: "struct clap_host_timer_support", header: "clap/clap.h", bycopy.} = object
    register_timer*: proc(a0: ptr clap_host_t, a1: uint32, a2: ptr clap_id): bool {.cdecl.}
    unregister_timer*: proc(a0: ptr clap_host_t, a1: clap_id): bool {.cdecl.}
  clap_host_timer_support_t* = clap_host_timer_support
  clap_track_info* {.importc: "struct clap_track_info", header: "clap/clap.h", bycopy.} = object
    flags*: uint64
    name*: array[256, cchar]
    color*: clap_color_t
    audio_channel_count*: int32
    audio_port_type*: cstring
  clap_track_info_t* = clap_track_info
  clap_plugin_track_info* {.importc: "struct clap_plugin_track_info", header: "clap/clap.h", bycopy.} = object
    changed*: proc(a0: ptr clap_plugin_t) {.cdecl.}
  clap_plugin_track_info_t* = clap_plugin_track_info
  clap_host_track_info* {.importc: "struct clap_host_track_info", header: "clap/clap.h", bycopy.} = object
    get*: proc(a0: ptr clap_host_t, a1: ptr clap_track_info_t): bool {.cdecl.}
  clap_host_track_info_t* = clap_host_track_info
  clap_voice_info* {.importc: "struct clap_voice_info", header: "clap/clap.h", bycopy.} = object
    voice_count*: uint32
    voice_capacity*: uint32
    flags*: uint64
  clap_voice_info_t* = clap_voice_info
  clap_plugin_voice_info* {.importc: "struct clap_plugin_voice_info", header: "clap/clap.h", bycopy.} = object
    get*: proc(a0: ptr clap_plugin_t, a1: ptr clap_voice_info_t): bool {.cdecl.}
  clap_plugin_voice_info_t* = clap_plugin_voice_info
  clap_host_voice_info* {.importc: "struct clap_host_voice_info", header: "clap/clap.h", bycopy.} = object
    changed*: proc(a0: ptr clap_host_t) {.cdecl.}
  clap_host_voice_info_t* = clap_host_voice_info

const
  CLAP_VERSION_MAJOR* = 1
  CLAP_VERSION_MINOR* = 2
  CLAP_VERSION_REVISION* = 10
  CLAP_PLUGIN_FEATURE_INSTRUMENT* = "instrument"
  CLAP_PLUGIN_FEATURE_AUDIO_EFFECT* = "audio-effect"
  CLAP_PLUGIN_FEATURE_NOTE_EFFECT* = "note-effect"
  CLAP_PLUGIN_FEATURE_NOTE_DETECTOR* = "note-detector"
  CLAP_PLUGIN_FEATURE_ANALYZER* = "analyzer"
  CLAP_PLUGIN_FEATURE_SYNTHESIZER* = "synthesizer"
  CLAP_PLUGIN_FEATURE_SAMPLER* = "sampler"
  CLAP_PLUGIN_FEATURE_DRUM* = "drum"
  CLAP_PLUGIN_FEATURE_DRUM_MACHINE* = "drum-machine"
  CLAP_PLUGIN_FEATURE_FILTER* = "filter"
  CLAP_PLUGIN_FEATURE_PHASER* = "phaser"
  CLAP_PLUGIN_FEATURE_EQUALIZER* = "equalizer"
  CLAP_PLUGIN_FEATURE_DEESSER* = "de-esser"
  CLAP_PLUGIN_FEATURE_PHASE_VOCODER* = "phase-vocoder"
  CLAP_PLUGIN_FEATURE_GRANULAR* = "granular"
  CLAP_PLUGIN_FEATURE_FREQUENCY_SHIFTER* = "frequency-shifter"
  CLAP_PLUGIN_FEATURE_PITCH_SHIFTER* = "pitch-shifter"
  CLAP_PLUGIN_FEATURE_DISTORTION* = "distortion"
  CLAP_PLUGIN_FEATURE_TRANSIENT_SHAPER* = "transient-shaper"
  CLAP_PLUGIN_FEATURE_COMPRESSOR* = "compressor"
  CLAP_PLUGIN_FEATURE_EXPANDER* = "expander"
  CLAP_PLUGIN_FEATURE_GATE* = "gate"
  CLAP_PLUGIN_FEATURE_LIMITER* = "limiter"
  CLAP_PLUGIN_FEATURE_FLANGER* = "flanger"
  CLAP_PLUGIN_FEATURE_CHORUS* = "chorus"
  CLAP_PLUGIN_FEATURE_DELAY* = "delay"
  CLAP_PLUGIN_FEATURE_REVERB* = "reverb"
  CLAP_PLUGIN_FEATURE_TREMOLO* = "tremolo"
  CLAP_PLUGIN_FEATURE_GLITCH* = "glitch"
  CLAP_PLUGIN_FEATURE_UTILITY* = "utility"
  CLAP_PLUGIN_FEATURE_PITCH_CORRECTION* = "pitch-correction"
  CLAP_PLUGIN_FEATURE_RESTORATION* = "restoration"
  CLAP_PLUGIN_FEATURE_MULTI_EFFECTS* = "multi-effects"
  CLAP_PLUGIN_FEATURE_MIXING* = "mixing"
  CLAP_PLUGIN_FEATURE_MASTERING* = "mastering"
  CLAP_PLUGIN_FEATURE_MONO* = "mono"
  CLAP_PLUGIN_FEATURE_STEREO* = "stereo"
  CLAP_PLUGIN_FEATURE_SURROUND* = "surround"
  CLAP_PLUGIN_FEATURE_AMBISONIC* = "ambisonic"
  CLAP_EVENT_NOTE_ON* = 0
  CLAP_EVENT_NOTE_OFF* = 1
  CLAP_EVENT_NOTE_CHOKE* = 2
  CLAP_EVENT_NOTE_END* = 3
  CLAP_EVENT_NOTE_EXPRESSION* = 4
  CLAP_EVENT_PARAM_VALUE* = 5
  CLAP_EVENT_PARAM_MOD* = 6
  CLAP_EVENT_PARAM_GESTURE_BEGIN* = 7
  CLAP_EVENT_PARAM_GESTURE_END* = 8
  CLAP_EVENT_TRANSPORT* = 9
  CLAP_EVENT_MIDI* = 10
  CLAP_EVENT_MIDI_SYSEX* = 11
  CLAP_EVENT_MIDI2* = 12
  CLAP_NOTE_EXPRESSION_VOLUME* = 0
  CLAP_NOTE_EXPRESSION_PAN* = 1
  CLAP_NOTE_EXPRESSION_TUNING* = 2
  CLAP_NOTE_EXPRESSION_VIBRATO* = 3
  CLAP_NOTE_EXPRESSION_EXPRESSION* = 4
  CLAP_NOTE_EXPRESSION_BRIGHTNESS* = 5
  CLAP_NOTE_EXPRESSION_PRESSURE* = 6
  CLAP_PROCESS_ERROR* = 0
  CLAP_PROCESS_CONTINUE* = 1
  CLAP_PROCESS_CONTINUE_IF_NOT_QUIET* = 2
  CLAP_PROCESS_TAIL* = 3
  CLAP_PROCESS_SLEEP* = 4
  CLAP_NAME_SIZE* = 256
  CLAP_PATH_SIZE* = 1024
  CLAP_AUDIO_PORT_IS_MAIN* = 1
  CLAP_AUDIO_PORT_SUPPORTS_64BITS* = 2
  CLAP_AUDIO_PORT_PREFERS_64BITS* = 4
  CLAP_AUDIO_PORT_REQUIRES_COMMON_SAMPLE_SIZE* = 8
  CLAP_AUDIO_PORTS_RESCAN_NAMES* = 1
  CLAP_AUDIO_PORTS_RESCAN_FLAGS* = 2
  CLAP_AUDIO_PORTS_RESCAN_CHANNEL_COUNT* = 4
  CLAP_AUDIO_PORTS_RESCAN_PORT_TYPE* = 8
  CLAP_AUDIO_PORTS_RESCAN_IN_PLACE_PAIR* = 16
  CLAP_AUDIO_PORTS_RESCAN_LIST* = 32
  CLAP_CONTEXT_MENU_TARGET_KIND_GLOBAL* = 0
  CLAP_CONTEXT_MENU_TARGET_KIND_PARAM* = 1
  CLAP_CONTEXT_MENU_ITEM_ENTRY* = 0
  CLAP_CONTEXT_MENU_ITEM_CHECK_ENTRY* = 1
  CLAP_CONTEXT_MENU_ITEM_SEPARATOR* = 2
  CLAP_CONTEXT_MENU_ITEM_BEGIN_SUBMENU* = 3
  CLAP_CONTEXT_MENU_ITEM_END_SUBMENU* = 4
  CLAP_CONTEXT_MENU_ITEM_TITLE* = 5
  CLAP_LOG_DEBUG* = 0
  CLAP_LOG_INFO* = 1
  CLAP_LOG_WARNING* = 2
  CLAP_LOG_ERROR* = 3
  CLAP_LOG_FATAL* = 4
  CLAP_LOG_HOST_MISBEHAVING* = 5
  CLAP_LOG_PLUGIN_MISBEHAVING* = 6
  CLAP_NOTE_PORTS_RESCAN_ALL* = 1
  CLAP_NOTE_PORTS_RESCAN_NAMES* = 2
  CLAP_PARAM_IS_STEPPED* = 1
  CLAP_PARAM_IS_PERIODIC* = 2
  CLAP_PARAM_IS_HIDDEN* = 4
  CLAP_PARAM_IS_READONLY* = 8
  CLAP_PARAM_IS_BYPASS* = 16
  CLAP_PARAM_IS_AUTOMATABLE* = 32
  CLAP_PARAM_IS_AUTOMATABLE_PER_NOTE_ID* = 64
  CLAP_PARAM_IS_AUTOMATABLE_PER_KEY* = 128
  CLAP_PARAM_IS_AUTOMATABLE_PER_CHANNEL* = 256
  CLAP_PARAM_IS_AUTOMATABLE_PER_PORT* = 512
  CLAP_PARAM_IS_MODULATABLE* = 1024
  CLAP_PARAM_IS_MODULATABLE_PER_NOTE_ID* = 2048
  CLAP_PARAM_IS_MODULATABLE_PER_KEY* = 4096
  CLAP_PARAM_IS_MODULATABLE_PER_CHANNEL* = 8192
  CLAP_PARAM_IS_MODULATABLE_PER_PORT* = 16384
  CLAP_PARAM_REQUIRES_PROCESS* = 32768
  CLAP_PARAM_IS_ENUM* = 65536
  CLAP_PARAM_RESCAN_VALUES* = 1
  CLAP_PARAM_RESCAN_TEXT* = 2
  CLAP_PARAM_RESCAN_INFO* = 4
  CLAP_PARAM_RESCAN_ALL* = 8
  CLAP_PARAM_CLEAR_ALL* = 1
  CLAP_PARAM_CLEAR_AUTOMATIONS* = 2
  CLAP_PARAM_CLEAR_MODULATIONS* = 4
  CLAP_PARAM_INDICATION_AUTOMATION_NONE* = 0
  CLAP_PARAM_INDICATION_AUTOMATION_PRESENT* = 1
  CLAP_PARAM_INDICATION_AUTOMATION_PLAYING* = 2
  CLAP_PARAM_INDICATION_AUTOMATION_RECORDING* = 3
  CLAP_PARAM_INDICATION_AUTOMATION_OVERRIDING* = 4
  CLAP_POSIX_FD_READ* = 1
  CLAP_POSIX_FD_WRITE* = 2
  CLAP_POSIX_FD_ERROR* = 4
  CLAP_REMOTE_CONTROLS_COUNT* = 8
  CLAP_RENDER_REALTIME* = 0
  CLAP_RENDER_OFFLINE* = 1
  CLAP_SURROUND_FL* = 0
  CLAP_SURROUND_FR* = 1
  CLAP_SURROUND_FC* = 2
  CLAP_SURROUND_LFE* = 3
  CLAP_SURROUND_BL* = 4
  CLAP_SURROUND_BR* = 5
  CLAP_SURROUND_FLC* = 6
  CLAP_SURROUND_FRC* = 7
  CLAP_SURROUND_BC* = 8
  CLAP_SURROUND_SL* = 9
  CLAP_SURROUND_SR* = 10
  CLAP_SURROUND_TC* = 11
  CLAP_SURROUND_TFL* = 12
  CLAP_SURROUND_TFC* = 13
  CLAP_SURROUND_TFR* = 14
  CLAP_SURROUND_TBL* = 15
  CLAP_SURROUND_TBC* = 16
  CLAP_SURROUND_TBR* = 17
  CLAP_SURROUND_TSL* = 18
  CLAP_SURROUND_TSR* = 19
  CLAP_TRACK_INFO_HAS_TRACK_NAME* = 1
  CLAP_TRACK_INFO_HAS_TRACK_COLOR* = 2
  CLAP_TRACK_INFO_HAS_AUDIO_CHANNEL* = 4
  CLAP_TRACK_INFO_IS_FOR_RETURN_TRACK* = 8
  CLAP_TRACK_INFO_IS_FOR_BUS* = 16
  CLAP_TRACK_INFO_IS_FOR_MASTER* = 32
  CLAP_VOICE_INFO_SUPPORTS_OVERLAPPING_NOTES* = 1

var CLAP_VERSION* {.importc: "CLAP_VERSION", header: "clap/clap.h".}: clap_version_t
proc clap_version_is_compatible*(v: clap_version_t): bool {.importc: "clap_version_is_compatible", header: "clap/clap.h", cdecl.}
var clap_entry* {.importc: "clap_entry", header: "clap/clap.h".}: clap_plugin_entry_t
var CLAP_BEATTIME_FACTOR* {.importc: "CLAP_BEATTIME_FACTOR", header: "clap/clap.h".}: int64
var CLAP_SECTIME_FACTOR* {.importc: "CLAP_SECTIME_FACTOR", header: "clap/clap.h".}: int64
var CLAP_INVALID_ID* {.importc: "CLAP_INVALID_ID", header: "clap/clap.h".}: clap_id
var CLAP_CORE_EVENT_SPACE_ID* {.importc: "CLAP_CORE_EVENT_SPACE_ID", header: "clap/clap.h".}: uint16
var CLAP_PLUGIN_FACTORY_ID* {.importc: "CLAP_PLUGIN_FACTORY_ID", header: "clap/clap.h".}: array[20, cchar]
var CLAP_TIMESTAMP_UNKNOWN* {.importc: "CLAP_TIMESTAMP_UNKNOWN", header: "clap/clap.h".}: clap_timestamp
var CLAP_PRESET_DISCOVERY_FACTORY_ID* {.importc: "CLAP_PRESET_DISCOVERY_FACTORY_ID", header: "clap/clap.h".}: array[32, cchar]
var CLAP_PRESET_DISCOVERY_FACTORY_ID_COMPAT* {.importc: "CLAP_PRESET_DISCOVERY_FACTORY_ID_COMPAT", header: "clap/clap.h".}: array[38, cchar]
var CLAP_EXT_AMBISONIC* {.importc: "CLAP_EXT_AMBISONIC", header: "clap/clap.h".}: array[17, cchar]
var CLAP_EXT_AMBISONIC_COMPAT* {.importc: "CLAP_EXT_AMBISONIC_COMPAT", header: "clap/clap.h".}: array[23, cchar]
var CLAP_PORT_AMBISONIC* {.importc: "CLAP_PORT_AMBISONIC", header: "clap/clap.h".}: array[10, cchar]
var CLAP_EXT_AUDIO_PORTS_ACTIVATION* {.importc: "CLAP_EXT_AUDIO_PORTS_ACTIVATION", header: "clap/clap.h".}: array[30, cchar]
var CLAP_EXT_AUDIO_PORTS_ACTIVATION_COMPAT* {.importc: "CLAP_EXT_AUDIO_PORTS_ACTIVATION_COMPAT", header: "clap/clap.h".}: array[36, cchar]
var CLAP_EXT_AUDIO_PORTS* {.importc: "CLAP_EXT_AUDIO_PORTS", header: "clap/clap.h".}: array[17, cchar]
var CLAP_PORT_MONO* {.importc: "CLAP_PORT_MONO", header: "clap/clap.h".}: array[5, cchar]
var CLAP_PORT_STEREO* {.importc: "CLAP_PORT_STEREO", header: "clap/clap.h".}: array[7, cchar]
var CLAP_EXT_AUDIO_PORTS_CONFIG* {.importc: "CLAP_EXT_AUDIO_PORTS_CONFIG", header: "clap/clap.h".}: array[24, cchar]
var CLAP_EXT_AUDIO_PORTS_CONFIG_INFO* {.importc: "CLAP_EXT_AUDIO_PORTS_CONFIG_INFO", header: "clap/clap.h".}: array[31, cchar]
var CLAP_EXT_AUDIO_PORTS_CONFIG_INFO_COMPAT* {.importc: "CLAP_EXT_AUDIO_PORTS_CONFIG_INFO_COMPAT", header: "clap/clap.h".}: array[37, cchar]
var CLAP_EXT_CONFIGURABLE_AUDIO_PORTS* {.importc: "CLAP_EXT_CONFIGURABLE_AUDIO_PORTS", header: "clap/clap.h".}: array[32, cchar]
var CLAP_EXT_CONFIGURABLE_AUDIO_PORTS_COMPAT* {.importc: "CLAP_EXT_CONFIGURABLE_AUDIO_PORTS_COMPAT", header: "clap/clap.h".}: array[37, cchar]
var CLAP_EXT_CONTEXT_MENU* {.importc: "CLAP_EXT_CONTEXT_MENU", header: "clap/clap.h".}: array[20, cchar]
var CLAP_EXT_CONTEXT_MENU_COMPAT* {.importc: "CLAP_EXT_CONTEXT_MENU_COMPAT", header: "clap/clap.h".}: array[26, cchar]
var CLAP_EXT_EVENT_REGISTRY* {.importc: "CLAP_EXT_EVENT_REGISTRY", header: "clap/clap.h".}: array[20, cchar]
var CLAP_EXT_GUI* {.importc: "CLAP_EXT_GUI", header: "clap/clap.h".}: array[9, cchar]
var CLAP_WINDOW_API_WIN32* {.importc: "CLAP_WINDOW_API_WIN32", header: "clap/clap.h".}: array[6, cchar]
var CLAP_WINDOW_API_COCOA* {.importc: "CLAP_WINDOW_API_COCOA", header: "clap/clap.h".}: array[6, cchar]
var CLAP_WINDOW_API_UIKIT* {.importc: "CLAP_WINDOW_API_UIKIT", header: "clap/clap.h".}: array[6, cchar]
var CLAP_WINDOW_API_X11* {.importc: "CLAP_WINDOW_API_X11", header: "clap/clap.h".}: array[4, cchar]
var CLAP_WINDOW_API_WAYLAND* {.importc: "CLAP_WINDOW_API_WAYLAND", header: "clap/clap.h".}: array[8, cchar]
var CLAP_EXT_LATENCY* {.importc: "CLAP_EXT_LATENCY", header: "clap/clap.h".}: array[13, cchar]
var CLAP_EXT_LOG* {.importc: "CLAP_EXT_LOG", header: "clap/clap.h".}: array[9, cchar]
var CLAP_EXT_NOTE_NAME* {.importc: "CLAP_EXT_NOTE_NAME", header: "clap/clap.h".}: array[15, cchar]
var CLAP_EXT_NOTE_PORTS* {.importc: "CLAP_EXT_NOTE_PORTS", header: "clap/clap.h".}: array[16, cchar]
var CLAP_EXT_PARAMS* {.importc: "CLAP_EXT_PARAMS", header: "clap/clap.h".}: array[12, cchar]
var CLAP_COLOR_TRANSPARENT* {.importc: "CLAP_COLOR_TRANSPARENT", header: "clap/clap.h".}: clap_color_t
var CLAP_EXT_PARAM_INDICATION* {.importc: "CLAP_EXT_PARAM_INDICATION", header: "clap/clap.h".}: array[24, cchar]
var CLAP_EXT_PARAM_INDICATION_COMPAT* {.importc: "CLAP_EXT_PARAM_INDICATION_COMPAT", header: "clap/clap.h".}: array[30, cchar]
var CLAP_EXT_POSIX_FD_SUPPORT* {.importc: "CLAP_EXT_POSIX_FD_SUPPORT", header: "clap/clap.h".}: array[22, cchar]
var CLAP_EXT_PRESET_LOAD* {.importc: "CLAP_EXT_PRESET_LOAD", header: "clap/clap.h".}: array[19, cchar]
var CLAP_EXT_PRESET_LOAD_COMPAT* {.importc: "CLAP_EXT_PRESET_LOAD_COMPAT", header: "clap/clap.h".}: array[25, cchar]
var CLAP_EXT_REMOTE_CONTROLS* {.importc: "CLAP_EXT_REMOTE_CONTROLS", header: "clap/clap.h".}: array[23, cchar]
var CLAP_EXT_REMOTE_CONTROLS_COMPAT* {.importc: "CLAP_EXT_REMOTE_CONTROLS_COMPAT", header: "clap/clap.h".}: array[29, cchar]
var CLAP_EXT_RENDER* {.importc: "CLAP_EXT_RENDER", header: "clap/clap.h".}: array[12, cchar]
var CLAP_EXT_STATE_CONTEXT* {.importc: "CLAP_EXT_STATE_CONTEXT", header: "clap/clap.h".}: array[21, cchar]
var CLAP_EXT_STATE* {.importc: "CLAP_EXT_STATE", header: "clap/clap.h".}: array[11, cchar]
var CLAP_EXT_SURROUND* {.importc: "CLAP_EXT_SURROUND", header: "clap/clap.h".}: array[16, cchar]
var CLAP_EXT_SURROUND_COMPAT* {.importc: "CLAP_EXT_SURROUND_COMPAT", header: "clap/clap.h".}: array[22, cchar]
var CLAP_PORT_SURROUND* {.importc: "CLAP_PORT_SURROUND", header: "clap/clap.h".}: array[9, cchar]
var CLAP_EXT_TAIL* {.importc: "CLAP_EXT_TAIL", header: "clap/clap.h".}: array[10, cchar]
var CLAP_EXT_THREAD_CHECK* {.importc: "CLAP_EXT_THREAD_CHECK", header: "clap/clap.h".}: array[18, cchar]
var CLAP_EXT_THREAD_POOL* {.importc: "CLAP_EXT_THREAD_POOL", header: "clap/clap.h".}: array[17, cchar]
var CLAP_EXT_TIMER_SUPPORT* {.importc: "CLAP_EXT_TIMER_SUPPORT", header: "clap/clap.h".}: array[19, cchar]
var CLAP_EXT_TRACK_INFO* {.importc: "CLAP_EXT_TRACK_INFO", header: "clap/clap.h".}: array[18, cchar]
var CLAP_EXT_TRACK_INFO_COMPAT* {.importc: "CLAP_EXT_TRACK_INFO_COMPAT", header: "clap/clap.h".}: array[24, cchar]
var CLAP_EXT_VOICE_INFO* {.importc: "CLAP_EXT_VOICE_INFO", header: "clap/clap.h".}: array[16, cchar]
